var WEB_INCLUDE_TEST=0

var WEB_INCLUDE_MULTI_EWAN=0

var WEB_INCLUDE_DST=1

<<<<<<< HEAD


var INCLUDE_LAN_WLAN=1

var INCLUDE_VOIP

var INCLUDE_FXS_NUM

var INCLUDE_CALLLOG

var INCLUDE_USB_VOICEMAIL

var INCLUDE_PSTN

var INCLUDE_PSTN_GATEWAY

var INCLUDE_PSTN_LIFELINE

var INCLUDE_BRIDGING=1

var INCLUDE_IGMP=1

var INCLUDE_ETHERNET_WAN=1

var INCLUDE_SNMP=1

var INCLUDE_RIP=1

var INCLUDE_DDNS_PH

var INCLUDE_LAN_WLAN_MSSID=1

var INCLUDE_LAN_WLAN_WDS=1

var INCLUDE_IPTV=1

var INCLUDE_CWMP=1

var INCLUDE_DYNDNS=1

var INCLUDE_USB=1

var INCLUDE_USB_STORAGE=1

var INCLUDE_USB_MEDIA_SERVER=1

var INCLUDE_USB_SAMBA_SERVER=1

var INCLUDE_USB_FTP_SERVER=1

var INCLUDE_USB_OVER_IP=1

var INCLUDE_ADSLWAN

var INCLUDE_AUTO_PVC

var INCLUDE_IPV6=1

var INCLUDE_IPV6_SLAAC=1

var INCLUDE_SPECIAL_DIAL_MODE

var INCLUDE_WAN_MODE

var INCLUDE_IPSEC=1

var INCLUDE_NOIPDNS=1

var INCLUDE_ALG_H323=1

var INCLUDE_ALG_SIP=1

var INCLUDE_PON_ETH_WAN

var INCLUDE_EPON_INFO

var INCLUDE_GPON_INFO

var INCLUDE_QOS

var INCLUDE_E8_APP

var INCLUDE_TFC_PERU

var INCLUDE_USB_3G_DONGLE

var INCLUDE_LAN_WLAN_SCHEDULE=1

var INCLUDE_ROUTE_BINDING

var INCLUDE_LAN_WLAN_GUESTNETWORK=1

var INCLUDE_LAN_WLAN_DUALBAND=1

var INCLUDE_LAN_WLAN_AC=1

var INCLUDE_LAN_WLAN_WDS_DETECT

var INCLUDE_L2TP=1

var INCLUDE_PPTP=1

var INCLUDE_IPV6_MLD

var INCLUDE_ACL=1

var INCLUDE_ACL_ADVANCE

var INCLUDE_WAN_DETECT=1

var INCLUDE_VDSLWAN

var INCLUDE_DUAL_ACCESS=1

var INCLUDE_DECT

var INCLUDE_WAN_VLAN

var INCLUDE_GERMANY_SPEC

var INCLUDE_PPP_RECONN

var INCLUDE_CHGINIT_PWD

var INCLUDE_TRACEROUTE_DIAG=1

var INCLUDE_IPPING_DIAG=1

var IGD = "IGD"

var IGD_DEV_INFO = "IGD_DEV_INFO"

var SYSLOG_CFG = "SYSLOG_CFG"

var MANAGEMENT_SERVER = "MANAGEMENT_SERVER"

var ETH_SWITCH = "ETH_SWITCH"

var SYS_CFG = "SYS_CFG"

var NET_CFG = "NET_CFG"

var USER_CFG = "USER_CFG"

var APP_CFG = "APP_CFG"

var HTTP_CFG = "HTTP_CFG"

var PH_DDNS_CFG = "PH_DDNS_CFG"

var PH_RT_DATA = "PH_RT_DATA"

var DYN_DNS_CFG = "DYN_DNS_CFG"

var UPNP_CFG = "UPNP_CFG"

var UPNP_PORTMAPPING = "UPNP_PORTMAPPING"

var DIAG_TOOL = "DIAG_TOOL"

var CWMP_CFG = "CWMP_CFG"

var SNMP_CFG = "SNMP_CFG"

var NOIP_DNS_CFG = "NOIP_DNS_CFG"

var ACL_CFG = "ACL_CFG"

var DMZ_HOST_CFG = "DMZ_HOST_CFG"

var TIME = "TIME"

var HOUR = "HOUR"

var L3_FORWARDING = "L3_FORWARDING"

var L3_FORWARDING_ENTRY = "L3_FORWARDING_ENTRY"

var L3_IP6_FORWARDING = "L3_IP6_FORWARDING"

var L3_IP6_FORWARDING_ENTRY = "L3_IP6_FORWARDING_ENTRY"

var L2_BRIDGING = "L2_BRIDGING"

var L2_BRIDGING_ENTRY = "L2_BRIDGING_ENTRY"

var L2_BRIDGING_FILTER = "L2_BRIDGING_FILTER"

var L2_BRIDGING_INTF = "L2_BRIDGING_INTF"

var LAN_DEV = "LAN_DEV"

var LAN_HOST_CFG = "LAN_HOST_CFG"

var LAN_IP_INTF = "LAN_IP_INTF"

var LAN_DHCP_STATIC_ADDR = "LAN_DHCP_STATIC_ADDR"

var LAN_DHCP_COND_SRV_POOL = "LAN_DHCP_COND_SRV_POOL"

var LAN_DHCP_COND_SRV_POOL_OPT = "LAN_DHCP_COND_SRV_POOL_OPT"

var LAN_IP6_HOST_CFG = "LAN_IP6_HOST_CFG"

var LAN_IP6_INTF = "LAN_IP6_INTF"

var LAN_ETH_INTF = "LAN_ETH_INTF"

var LAN_HOSTS = "LAN_HOSTS"

var LAN_HOST_ENTRY = "LAN_HOST_ENTRY"

var LAN_WLAN = "LAN_WLAN"

var LAN_WLAN_WPS = "LAN_WLAN_WPS"

var LAN_WLAN_MACTABLEENTRY = "LAN_WLAN_MACTABLEENTRY"

var LAN_WLAN_ASSOC_DEV = "LAN_WLAN_ASSOC_DEV"

var LAN_WLAN_BSSDESC_ENTRY = "LAN_WLAN_BSSDESC_ENTRY"

var LAN_WLAN_WEPKEY = "LAN_WLAN_WEPKEY"

var LAN_WLAN_WDSBRIDGE = "LAN_WLAN_WDSBRIDGE"

var LAN_WLAN_MULTISSID = "LAN_WLAN_MULTISSID"

var LAN_WLAN_MSSIDENTRY = "LAN_WLAN_MSSIDENTRY"

var LAN_WLAN_MSSIDWEPKEY = "LAN_WLAN_MSSIDWEPKEY"

var LAN_WLAN_WLBRNAME = "LAN_WLAN_WLBRNAME"

var LAN_WLAN_TASK_SCHEDULE = "LAN_WLAN_TASK_SCHEDULE"

var LAN_WLAN_GUESTNET = "LAN_WLAN_GUESTNET"

var LAN_IGMP_SNOOP = "LAN_IGMP_SNOOP"

var WAN_DEV = "WAN_DEV"

var WAN_COMMON_INTF_CFG = "WAN_COMMON_INTF_CFG"

var WAN_DSL_INTF_CFG = "WAN_DSL_INTF_CFG"

var WAN_DSL_INTF_STATS = "WAN_DSL_INTF_STATS"

var WAN_DSL_INTF_STATS_TOTAL = "WAN_DSL_INTF_STATS_TOTAL"

var WAN_ETH_INTF = "WAN_ETH_INTF"

var WAN_ETH_INTF_STATS = "WAN_ETH_INTF_STATS"

var WAN_PON = "WAN_PON"

var WAN_EPON_INTF = "WAN_EPON_INTF"

var WAN_EPON_INTF_OAM_STATS = "WAN_EPON_INTF_OAM_STATS"

var WAN_EPON_INTF_MPCP_STATS = "WAN_EPON_INTF_MPCP_STATS"

var WAN_EPON_INTF_STATS = "WAN_EPON_INTF_STATS"

var WAN_EPON_INTF_OPTICAL_STATS = "WAN_EPON_INTF_OPTICAL_STATS"

var WAN_GPON_INTF = "WAN_GPON_INTF"

var WAN_GPON_INTF_OMCI_STATS = "WAN_GPON_INTF_OMCI_STATS"

var WAN_GPON_INTF_STATS = "WAN_GPON_INTF_STATS"

var WAN_GPON_INTF_OPTICAL_STATS = "WAN_GPON_INTF_OPTICAL_STATS"

var WAN_CONN_DEVICE = "WAN_CONN_DEVICE"

var WAN_DSL_LINK_CFG = "WAN_DSL_LINK_CFG"

var WAN_PTM_LINK_CFG = "WAN_PTM_LINK_CFG"

var WAN_PTM_LINK_STATS = "WAN_PTM_LINK_STATS"

var WAN_PON_LINK_CFG = "WAN_PON_LINK_CFG"

var WAN_ETH_LINK_CFG = "WAN_ETH_LINK_CFG"

var WAN_USB_3G_LINK_CFG = "WAN_USB_3G_LINK_CFG"

var USB_MODEM_PARAM = "USB_MODEM_PARAM"

var WAN_L2TP_CONN = "WAN_L2TP_CONN"

var WAN_L2TP_CONN_PORTMAPPING = "WAN_L2TP_CONN_PORTMAPPING"

var L2TP_CONN_PORTTRIGGERING = "L2TP_CONN_PORTTRIGGERING"

var WAN_L2TP_CONN_STATS = "WAN_L2TP_CONN_STATS"

var WAN_PPTP_CONN = "WAN_PPTP_CONN"

var WAN_PPTP_CONN_PORTMAPPING = "WAN_PPTP_CONN_PORTMAPPING"

var PPTP_CONN_PORTTRIGGERING = "PPTP_CONN_PORTTRIGGERING"

var WAN_PPTP_CONN_STATS = "WAN_PPTP_CONN_STATS"

var WAN_IP_CONN = "WAN_IP_CONN"

var WAN_IP_CONN_PORTMAPPING = "WAN_IP_CONN_PORTMAPPING"

var IP_CONN_PORTTRIGGERING = "IP_CONN_PORTTRIGGERING"

var WAN_PPP_CONN = "WAN_PPP_CONN"

var WAN_PPP_CONN_PORTMAPPING = "WAN_PPP_CONN_PORTMAPPING"

var PPP_CONN_PORTTRIGGERING = "PPP_CONN_PORTTRIGGERING"

var WAN_PPP_CONN_STATS = "WAN_PPP_CONN_STATS"

var STAT_CFG = "STAT_CFG"

var STAT_ENTRY = "STAT_ENTRY"

var DDOS_CFG = "DDOS_CFG"

var DOS_HOST = "DOS_HOST"

var ARP = "ARP"

var ARP_ENTRY = "ARP_ENTRY"

var ARP_BIND = "ARP_BIND"

var ARP_BIND_ENTRY = "ARP_BIND_ENTRY"

var QUEUE_MANAGEMENT = "QUEUE_MANAGEMENT"

var CLASSIFICATION = "CLASSIFICATION"

var QOS_APP = "QOS_APP"

var QOS_INTF = "QOS_INTF"

var QOS_QUEUE = "QOS_QUEUE"

var TC = "TC"

var TC_RULE = "TC_RULE"

var ALG_CFG = "ALG_CFG"

var IPTV = "IPTV"

var DSL_IPTV_CFG = "DSL_IPTV_CFG"

var ETH_IPTV_CFG = "ETH_IPTV_CFG"

var FIREWALL = "FIREWALL"

var INTERNAL_HOST = "INTERNAL_HOST"

var EXTERNAL_HOST = "EXTERNAL_HOST"

var TASK_SCHEDULE = "TASK_SCHEDULE"

var RULE = "RULE"

var URL_LIST = "URL_LIST"

var URL_CFG = "URL_CFG"

var IP6_FIREWALL = "IP6_FIREWALL"

var IP6_INTERNAL_HOST = "IP6_INTERNAL_HOST"

var IP6_EXTERNAL_HOST = "IP6_EXTERNAL_HOST"

var IP6_TASK_SCHEDULE = "IP6_TASK_SCHEDULE"

var IP6_RULE = "IP6_RULE"

var IP6_TUNNEL = "IP6_TUNNEL"

var DSLITE = "DSLITE"

var SIT_6RD = "SIT_6RD"

var SERVICES = "SERVICES"

var VOICE = "VOICE"

var XTP_VOICE_PROCESS_STS = "XTP_VOICE_PROCESS_STS"

var XTP_VOICE_PROCESS = "XTP_VOICE_PROCESS"

var VOICE_CAP = "VOICE_CAP"

var VOICE_CAP_SIP = "VOICE_CAP_SIP"

var VOICE_CAP_MGCP = "VOICE_CAP_MGCP"

var VOICE_CAP_CODECS = "VOICE_CAP_CODECS"

var VOICE_PROF = "VOICE_PROF"

var VOICE_PROF_PROVIDER = "VOICE_PROF_PROVIDER"

var VOICE_PROF_SIP = "VOICE_PROF_SIP"

var VOICE_PROF_SIP_EVTSUBSCRIBE = "VOICE_PROF_SIP_EVTSUBSCRIBE"

var VOICE_PROF_MGCP = "VOICE_PROF_MGCP"

var VOICE_PROF_RTP = "VOICE_PROF_RTP"

var VOICE_PROF_FAXT38 = "VOICE_PROF_FAXT38"

var XTP_USB_VOICEMAIL_PUBLICCFG = "XTP_USB_VOICEMAIL_PUBLICCFG"

var XTP_MULTI_ISP = "XTP_MULTI_ISP"

var XTP_MULTIISP_CODEC = "XTP_MULTIISP_CODEC"

var XTP_MULTIISP_CODEC_LIST = "XTP_MULTIISP_CODEC_LIST"

var VOICE_PROF_LINE = "VOICE_PROF_LINE"

var VOICE_PROF_LINE_SIP = "VOICE_PROF_LINE_SIP"

var XTP_DECT_HANDSET_INFO = "XTP_DECT_HANDSET_INFO"

var VOICE_PROF_LINE_XTPUSBVM = "VOICE_PROF_LINE_XTPUSBVM"

var VOICE_PROF_LINE_CALLFEAT = "VOICE_PROF_LINE_CALLFEAT"

var VOICE_PROF_LINE_PROC = "VOICE_PROF_LINE_PROC"

var VOICE_PROF_LINE_CODEC = "VOICE_PROF_LINE_CODEC"

var VOICE_PROF_LINE_CODEC_LIST = "VOICE_PROF_LINE_CODEC_LIST"

var VOICE_PROF_LINE_STATS = "VOICE_PROF_LINE_STATS"

var XTP_INCOMING_CALL = "XTP_INCOMING_CALL"

var XTP_OUTGOING_CALL = "XTP_OUTGOING_CALL"

var XTP_FEATURE_CODE = "XTP_FEATURE_CODE"

var VOICE_PHY_INTERFACE = "VOICE_PHY_INTERFACE"

var VOICE_PHYINTERFACE_TESTS = "VOICE_PHYINTERFACE_TESTS"

var XTP_VOICE_MULTI_ISPDIALPLAN = "XTP_VOICE_MULTI_ISPDIALPLAN"

var XTP_VOICE_PSTN = "XTP_VOICE_PSTN"

var XTP_DECT_BASE_STATION = "XTP_DECT_BASE_STATION"

var XTP_TELE_CONTACT = "XTP_TELE_CONTACT"

var STORAGE_SERVICE = "STORAGE_SERVICE"

var CAPABLE = "CAPABLE"

var USER_ACCOUNT = "USER_ACCOUNT"

var USB_DEVICE = "USB_DEVICE"

var LOGICAL_VOLUME = "LOGICAL_VOLUME"

var FOLDER_BROWSE = "FOLDER_BROWSE"

var FOLDER_NODE = "FOLDER_NODE"

var DLNA_MEDIA_SERVER = "DLNA_MEDIA_SERVER"

var DLNA_MEDIA_SERVER_FOLDER = "DLNA_MEDIA_SERVER_FOLDER"

var SMB_SERVICE = "SMB_SERVICE"

var SMB_SERVICE_FOLDER = "SMB_SERVICE_FOLDER"

var SMB_USER_ACCESS = "SMB_USER_ACCESS"

var FTP_SERVER = "FTP_SERVER"

var FTP_SERVER_FOLDER = "FTP_SERVER_FOLDER"

var FTP_USER_ACCESS = "FTP_USER_ACCESS"

var XTP_PRINT_SERVICE = "XTP_PRINT_SERVICE"

var XTP_VOICE_DND = "XTP_VOICE_DND"

var XTP_CALL_FWD = "XTP_CALL_FWD"

var XTP_CALL_FWD_LIST = "XTP_CALL_FWD_LIST"

var XTP_CALL_THROUGH = "XTP_CALL_THROUGH"

var XTP_CALLTHROUGH_NUM = "XTP_CALLTHROUGH_NUM"

var XTP_IGD_CALL_FIREWALL_CFG = "XTP_IGD_CALL_FIREWALL_CFG"

var XTP_IGD_SPEED_DIAL_CFG = "XTP_IGD_SPEED_DIAL_CFG"

var XTP_IGD_MULTI_ISP_DIAL_PLAN = "XTP_IGD_MULTI_ISP_DIAL_PLAN"

var XTP_IGD_MULTIISPDP_LIST = "XTP_IGD_MULTIISPDP_LIST"

var XTP_CALLLOGCFG = "XTP_CALLLOGCFG"

var IPSEC = "IPSEC"

var IPSEC_CFG = "IPSEC_CFG"

var SYS_MODE = "SYS_MODE"

var EWAN = "EWAN"

var USER_INFO = "USER_INFO"

var GPON_USER_INFO = "GPON_USER_INFO"

var GPON_AUTH_CTC = "GPON_AUTH_CTC"

var GPON_AUTH_SN = "GPON_AUTH_SN"

var GPON_AUTH_PWD = "GPON_AUTH_PWD"

var GPON_MAC_INFO = "GPON_MAC_INFO"

var GPON_FWD_RULE = "GPON_FWD_RULE"

var GPON_LOCAL_RULE_ENTRY = "GPON_LOCAL_RULE_ENTRY"

var GPON_REMOTE_RULE_ENTRY = "GPON_REMOTE_RULE_ENTRY"

var GPON_OMCI_IOT = "GPON_OMCI_IOT"

var GPON_OMCI_IOT_ENTRY = "GPON_OMCI_IOT_ENTRY"

var GPON_OMCI_ME_ATTR = "GPON_OMCI_ME_ATTR"

var IPPING_DIAG = "IPPING_DIAG"

var TRACEROUTE_DIAG = "TRACEROUTE_DIAG"

var LOCAL = "LOCAL"

var WAN_DETECT = "WAN_DETECT"

var WAN_DSL_AUTO_PVC_PAIR = "WAN_DSL_AUTO_PVC_PAIR"

var LED_NIGHTMODE = "LED_NIGHTMODE"

=======


var INCLUDE_LAN_WLAN=1

var INCLUDE_VOIP

var INCLUDE_FXS_NUM

var INCLUDE_CALLLOG

var INCLUDE_USB_VOICEMAIL

var INCLUDE_PSTN

var INCLUDE_PSTN_GATEWAY

var INCLUDE_PSTN_LIFELINE

var INCLUDE_BRIDGING=1

var INCLUDE_IGMP=1

var INCLUDE_ETHERNET_WAN=1

var INCLUDE_SNMP=1

var INCLUDE_RIP=1

var INCLUDE_DDNS_PH

var INCLUDE_LAN_WLAN_MSSID=1

var INCLUDE_LAN_WLAN_WDS=1

var INCLUDE_IPTV=1

var INCLUDE_CWMP=1

var INCLUDE_DYNDNS=1

var INCLUDE_USB=1

var INCLUDE_USB_STORAGE=1

var INCLUDE_USB_MEDIA_SERVER=1

var INCLUDE_USB_SAMBA_SERVER=1

var INCLUDE_USB_FTP_SERVER=1

var INCLUDE_USB_OVER_IP=1

var INCLUDE_ADSLWAN

var INCLUDE_AUTO_PVC

var INCLUDE_IPV6=1

var INCLUDE_IPV6_SLAAC=1

var INCLUDE_SPECIAL_DIAL_MODE

var INCLUDE_WAN_MODE

var INCLUDE_IPSEC=1

var INCLUDE_NOIPDNS=1

var INCLUDE_ALG_H323=1

var INCLUDE_ALG_SIP=1

var INCLUDE_PON_ETH_WAN

var INCLUDE_EPON_INFO

var INCLUDE_GPON_INFO

var INCLUDE_QOS

var INCLUDE_E8_APP

var INCLUDE_TFC_PERU

var INCLUDE_USB_3G_DONGLE

var INCLUDE_LAN_WLAN_SCHEDULE=1

var INCLUDE_ROUTE_BINDING

var INCLUDE_LAN_WLAN_GUESTNETWORK=1

var INCLUDE_LAN_WLAN_DUALBAND=1

var INCLUDE_LAN_WLAN_AC=1

var INCLUDE_LAN_WLAN_WDS_DETECT

var INCLUDE_L2TP=1

var INCLUDE_PPTP=1

var INCLUDE_IPV6_MLD

var INCLUDE_ACL=1

var INCLUDE_ACL_ADVANCE

var INCLUDE_WAN_DETECT=1

var INCLUDE_VDSLWAN

var INCLUDE_DUAL_ACCESS=1

var INCLUDE_DECT

var INCLUDE_WAN_VLAN

var INCLUDE_GERMANY_SPEC

var INCLUDE_PPP_RECONN

var INCLUDE_CHGINIT_PWD

var INCLUDE_TRACEROUTE_DIAG=1

var INCLUDE_IPPING_DIAG=1

var IGD = "IGD"

var IGD_DEV_INFO = "IGD_DEV_INFO"

var SYSLOG_CFG = "SYSLOG_CFG"

var MANAGEMENT_SERVER = "MANAGEMENT_SERVER"

var ETH_SWITCH = "ETH_SWITCH"

var SYS_CFG = "SYS_CFG"

var NET_CFG = "NET_CFG"

var USER_CFG = "USER_CFG"

var APP_CFG = "APP_CFG"

var HTTP_CFG = "HTTP_CFG"

var PH_DDNS_CFG = "PH_DDNS_CFG"

var PH_RT_DATA = "PH_RT_DATA"

var DYN_DNS_CFG = "DYN_DNS_CFG"

var UPNP_CFG = "UPNP_CFG"

var UPNP_PORTMAPPING = "UPNP_PORTMAPPING"

var DIAG_TOOL = "DIAG_TOOL"

var CWMP_CFG = "CWMP_CFG"

var SNMP_CFG = "SNMP_CFG"

var NOIP_DNS_CFG = "NOIP_DNS_CFG"

var ACL_CFG = "ACL_CFG"

var DMZ_HOST_CFG = "DMZ_HOST_CFG"

var TIME = "TIME"

var HOUR = "HOUR"

var L3_FORWARDING = "L3_FORWARDING"

var L3_FORWARDING_ENTRY = "L3_FORWARDING_ENTRY"

var L3_IP6_FORWARDING = "L3_IP6_FORWARDING"

var L3_IP6_FORWARDING_ENTRY = "L3_IP6_FORWARDING_ENTRY"

var L2_BRIDGING = "L2_BRIDGING"

var L2_BRIDGING_ENTRY = "L2_BRIDGING_ENTRY"

var L2_BRIDGING_FILTER = "L2_BRIDGING_FILTER"

var L2_BRIDGING_INTF = "L2_BRIDGING_INTF"

var LAN_DEV = "LAN_DEV"

var LAN_HOST_CFG = "LAN_HOST_CFG"

var LAN_IP_INTF = "LAN_IP_INTF"

var LAN_DHCP_STATIC_ADDR = "LAN_DHCP_STATIC_ADDR"

var LAN_DHCP_COND_SRV_POOL = "LAN_DHCP_COND_SRV_POOL"

var LAN_DHCP_COND_SRV_POOL_OPT = "LAN_DHCP_COND_SRV_POOL_OPT"

var LAN_IP6_HOST_CFG = "LAN_IP6_HOST_CFG"

var LAN_IP6_INTF = "LAN_IP6_INTF"

var LAN_ETH_INTF = "LAN_ETH_INTF"

var LAN_HOSTS = "LAN_HOSTS"

var LAN_HOST_ENTRY = "LAN_HOST_ENTRY"

var LAN_WLAN = "LAN_WLAN"

var LAN_WLAN_WPS = "LAN_WLAN_WPS"

var LAN_WLAN_MACTABLEENTRY = "LAN_WLAN_MACTABLEENTRY"

var LAN_WLAN_ASSOC_DEV = "LAN_WLAN_ASSOC_DEV"

var LAN_WLAN_BSSDESC_ENTRY = "LAN_WLAN_BSSDESC_ENTRY"

var LAN_WLAN_WEPKEY = "LAN_WLAN_WEPKEY"

var LAN_WLAN_WDSBRIDGE = "LAN_WLAN_WDSBRIDGE"

var LAN_WLAN_MULTISSID = "LAN_WLAN_MULTISSID"

var LAN_WLAN_MSSIDENTRY = "LAN_WLAN_MSSIDENTRY"

var LAN_WLAN_MSSIDWEPKEY = "LAN_WLAN_MSSIDWEPKEY"

var LAN_WLAN_WLBRNAME = "LAN_WLAN_WLBRNAME"

var LAN_WLAN_TASK_SCHEDULE = "LAN_WLAN_TASK_SCHEDULE"

var LAN_WLAN_GUESTNET = "LAN_WLAN_GUESTNET"

var LAN_IGMP_SNOOP = "LAN_IGMP_SNOOP"

var WAN_DEV = "WAN_DEV"

var WAN_COMMON_INTF_CFG = "WAN_COMMON_INTF_CFG"

var WAN_DSL_INTF_CFG = "WAN_DSL_INTF_CFG"

var WAN_DSL_INTF_STATS = "WAN_DSL_INTF_STATS"

var WAN_DSL_INTF_STATS_TOTAL = "WAN_DSL_INTF_STATS_TOTAL"

var WAN_ETH_INTF = "WAN_ETH_INTF"

var WAN_ETH_INTF_STATS = "WAN_ETH_INTF_STATS"

var WAN_PON = "WAN_PON"

var WAN_EPON_INTF = "WAN_EPON_INTF"

var WAN_EPON_INTF_OAM_STATS = "WAN_EPON_INTF_OAM_STATS"

var WAN_EPON_INTF_MPCP_STATS = "WAN_EPON_INTF_MPCP_STATS"

var WAN_EPON_INTF_STATS = "WAN_EPON_INTF_STATS"

var WAN_EPON_INTF_OPTICAL_STATS = "WAN_EPON_INTF_OPTICAL_STATS"

var WAN_GPON_INTF = "WAN_GPON_INTF"

var WAN_GPON_INTF_OMCI_STATS = "WAN_GPON_INTF_OMCI_STATS"

var WAN_GPON_INTF_STATS = "WAN_GPON_INTF_STATS"

var WAN_GPON_INTF_OPTICAL_STATS = "WAN_GPON_INTF_OPTICAL_STATS"

var WAN_CONN_DEVICE = "WAN_CONN_DEVICE"

var WAN_DSL_LINK_CFG = "WAN_DSL_LINK_CFG"

var WAN_PTM_LINK_CFG = "WAN_PTM_LINK_CFG"

var WAN_PTM_LINK_STATS = "WAN_PTM_LINK_STATS"

var WAN_PON_LINK_CFG = "WAN_PON_LINK_CFG"

var WAN_ETH_LINK_CFG = "WAN_ETH_LINK_CFG"

var WAN_USB_3G_LINK_CFG = "WAN_USB_3G_LINK_CFG"

var USB_MODEM_PARAM = "USB_MODEM_PARAM"

var WAN_L2TP_CONN = "WAN_L2TP_CONN"

var WAN_L2TP_CONN_PORTMAPPING = "WAN_L2TP_CONN_PORTMAPPING"

var L2TP_CONN_PORTTRIGGERING = "L2TP_CONN_PORTTRIGGERING"

var WAN_L2TP_CONN_STATS = "WAN_L2TP_CONN_STATS"

var WAN_PPTP_CONN = "WAN_PPTP_CONN"

var WAN_PPTP_CONN_PORTMAPPING = "WAN_PPTP_CONN_PORTMAPPING"

var PPTP_CONN_PORTTRIGGERING = "PPTP_CONN_PORTTRIGGERING"

var WAN_PPTP_CONN_STATS = "WAN_PPTP_CONN_STATS"

var WAN_IP_CONN = "WAN_IP_CONN"

var WAN_IP_CONN_PORTMAPPING = "WAN_IP_CONN_PORTMAPPING"

var IP_CONN_PORTTRIGGERING = "IP_CONN_PORTTRIGGERING"

var WAN_PPP_CONN = "WAN_PPP_CONN"

var WAN_PPP_CONN_PORTMAPPING = "WAN_PPP_CONN_PORTMAPPING"

var PPP_CONN_PORTTRIGGERING = "PPP_CONN_PORTTRIGGERING"

var WAN_PPP_CONN_STATS = "WAN_PPP_CONN_STATS"

var STAT_CFG = "STAT_CFG"

var STAT_ENTRY = "STAT_ENTRY"

var DDOS_CFG = "DDOS_CFG"

var DOS_HOST = "DOS_HOST"

var ARP = "ARP"

var ARP_ENTRY = "ARP_ENTRY"

var ARP_BIND = "ARP_BIND"

var ARP_BIND_ENTRY = "ARP_BIND_ENTRY"

var QUEUE_MANAGEMENT = "QUEUE_MANAGEMENT"

var CLASSIFICATION = "CLASSIFICATION"

var QOS_APP = "QOS_APP"

var QOS_INTF = "QOS_INTF"

var QOS_QUEUE = "QOS_QUEUE"

var TC = "TC"

var TC_RULE = "TC_RULE"

var ALG_CFG = "ALG_CFG"

var IPTV = "IPTV"

var DSL_IPTV_CFG = "DSL_IPTV_CFG"

var ETH_IPTV_CFG = "ETH_IPTV_CFG"

var FIREWALL = "FIREWALL"

var INTERNAL_HOST = "INTERNAL_HOST"

var EXTERNAL_HOST = "EXTERNAL_HOST"

var TASK_SCHEDULE = "TASK_SCHEDULE"

var RULE = "RULE"

var URL_LIST = "URL_LIST"

var URL_CFG = "URL_CFG"

var IP6_FIREWALL = "IP6_FIREWALL"

var IP6_INTERNAL_HOST = "IP6_INTERNAL_HOST"

var IP6_EXTERNAL_HOST = "IP6_EXTERNAL_HOST"

var IP6_TASK_SCHEDULE = "IP6_TASK_SCHEDULE"

var IP6_RULE = "IP6_RULE"

var IP6_TUNNEL = "IP6_TUNNEL"

var DSLITE = "DSLITE"

var SIT_6RD = "SIT_6RD"

var SERVICES = "SERVICES"

var VOICE = "VOICE"

var XTP_VOICE_PROCESS_STS = "XTP_VOICE_PROCESS_STS"

var XTP_VOICE_PROCESS = "XTP_VOICE_PROCESS"

var VOICE_CAP = "VOICE_CAP"

var VOICE_CAP_SIP = "VOICE_CAP_SIP"

var VOICE_CAP_MGCP = "VOICE_CAP_MGCP"

var VOICE_CAP_CODECS = "VOICE_CAP_CODECS"

var VOICE_PROF = "VOICE_PROF"

var VOICE_PROF_PROVIDER = "VOICE_PROF_PROVIDER"

var VOICE_PROF_SIP = "VOICE_PROF_SIP"

var VOICE_PROF_SIP_EVTSUBSCRIBE = "VOICE_PROF_SIP_EVTSUBSCRIBE"

var VOICE_PROF_MGCP = "VOICE_PROF_MGCP"

var VOICE_PROF_RTP = "VOICE_PROF_RTP"

var VOICE_PROF_FAXT38 = "VOICE_PROF_FAXT38"

var XTP_USB_VOICEMAIL_PUBLICCFG = "XTP_USB_VOICEMAIL_PUBLICCFG"

var XTP_MULTI_ISP = "XTP_MULTI_ISP"

var XTP_MULTIISP_CODEC = "XTP_MULTIISP_CODEC"

var XTP_MULTIISP_CODEC_LIST = "XTP_MULTIISP_CODEC_LIST"

var VOICE_PROF_LINE = "VOICE_PROF_LINE"

var VOICE_PROF_LINE_SIP = "VOICE_PROF_LINE_SIP"

var XTP_DECT_HANDSET_INFO = "XTP_DECT_HANDSET_INFO"

var VOICE_PROF_LINE_XTPUSBVM = "VOICE_PROF_LINE_XTPUSBVM"

var VOICE_PROF_LINE_CALLFEAT = "VOICE_PROF_LINE_CALLFEAT"

var VOICE_PROF_LINE_PROC = "VOICE_PROF_LINE_PROC"

var VOICE_PROF_LINE_CODEC = "VOICE_PROF_LINE_CODEC"

var VOICE_PROF_LINE_CODEC_LIST = "VOICE_PROF_LINE_CODEC_LIST"

var VOICE_PROF_LINE_STATS = "VOICE_PROF_LINE_STATS"

var XTP_INCOMING_CALL = "XTP_INCOMING_CALL"

var XTP_OUTGOING_CALL = "XTP_OUTGOING_CALL"

var XTP_FEATURE_CODE = "XTP_FEATURE_CODE"

var VOICE_PHY_INTERFACE = "VOICE_PHY_INTERFACE"

var VOICE_PHYINTERFACE_TESTS = "VOICE_PHYINTERFACE_TESTS"

var XTP_VOICE_MULTI_ISPDIALPLAN = "XTP_VOICE_MULTI_ISPDIALPLAN"

var XTP_VOICE_PSTN = "XTP_VOICE_PSTN"

var XTP_DECT_BASE_STATION = "XTP_DECT_BASE_STATION"

var XTP_TELE_CONTACT = "XTP_TELE_CONTACT"

var STORAGE_SERVICE = "STORAGE_SERVICE"

var CAPABLE = "CAPABLE"

var USER_ACCOUNT = "USER_ACCOUNT"

var USB_DEVICE = "USB_DEVICE"

var LOGICAL_VOLUME = "LOGICAL_VOLUME"

var FOLDER_BROWSE = "FOLDER_BROWSE"

var FOLDER_NODE = "FOLDER_NODE"

var DLNA_MEDIA_SERVER = "DLNA_MEDIA_SERVER"

var DLNA_MEDIA_SERVER_FOLDER = "DLNA_MEDIA_SERVER_FOLDER"

var SMB_SERVICE = "SMB_SERVICE"

var SMB_SERVICE_FOLDER = "SMB_SERVICE_FOLDER"

var SMB_USER_ACCESS = "SMB_USER_ACCESS"

var FTP_SERVER = "FTP_SERVER"

var FTP_SERVER_FOLDER = "FTP_SERVER_FOLDER"

var FTP_USER_ACCESS = "FTP_USER_ACCESS"

var XTP_PRINT_SERVICE = "XTP_PRINT_SERVICE"

var XTP_VOICE_DND = "XTP_VOICE_DND"

var XTP_CALL_FWD = "XTP_CALL_FWD"

var XTP_CALL_FWD_LIST = "XTP_CALL_FWD_LIST"

var XTP_CALL_THROUGH = "XTP_CALL_THROUGH"

var XTP_CALLTHROUGH_NUM = "XTP_CALLTHROUGH_NUM"

var XTP_IGD_CALL_FIREWALL_CFG = "XTP_IGD_CALL_FIREWALL_CFG"

var XTP_IGD_SPEED_DIAL_CFG = "XTP_IGD_SPEED_DIAL_CFG"

var XTP_IGD_MULTI_ISP_DIAL_PLAN = "XTP_IGD_MULTI_ISP_DIAL_PLAN"

var XTP_IGD_MULTIISPDP_LIST = "XTP_IGD_MULTIISPDP_LIST"

var XTP_CALLLOGCFG = "XTP_CALLLOGCFG"

var IPSEC = "IPSEC"

var IPSEC_CFG = "IPSEC_CFG"

var SYS_MODE = "SYS_MODE"

var EWAN = "EWAN"

var USER_INFO = "USER_INFO"

var GPON_USER_INFO = "GPON_USER_INFO"

var GPON_AUTH_CTC = "GPON_AUTH_CTC"

var GPON_AUTH_SN = "GPON_AUTH_SN"

var GPON_AUTH_PWD = "GPON_AUTH_PWD"

var GPON_MAC_INFO = "GPON_MAC_INFO"

var GPON_FWD_RULE = "GPON_FWD_RULE"

var GPON_LOCAL_RULE_ENTRY = "GPON_LOCAL_RULE_ENTRY"

var GPON_REMOTE_RULE_ENTRY = "GPON_REMOTE_RULE_ENTRY"

var GPON_OMCI_IOT = "GPON_OMCI_IOT"

var GPON_OMCI_IOT_ENTRY = "GPON_OMCI_IOT_ENTRY"

var GPON_OMCI_ME_ATTR = "GPON_OMCI_ME_ATTR"

var IPPING_DIAG = "IPPING_DIAG"

var TRACEROUTE_DIAG = "TRACEROUTE_DIAG"

var LOCAL = "LOCAL"

var WAN_DETECT = "WAN_DETECT"

var WAN_DSL_AUTO_PVC_PAIR = "WAN_DSL_AUTO_PVC_PAIR"

var LED_NIGHTMODE = "LED_NIGHTMODE"

>>>>>>> 59bffef8551d69606b594c223f73f1df7ea23746
