var top_menu = {
    'lang_home': 'Home',
    'lang_setup': 'Setup',
    'lang_advanced': 'Advanced',
    'lang_wireless': 'Wireless',
    'lang_status': 'Status',
    'lang_wizard': 'Wizard',
    'lang_management': 'Management',
    'lang_welcome': 'Welcome',
    'lang_logout': 'Logout'
};

var sub_menu = {
    //status
    'Word_status': "Status",
    'lang_system_msg': 'System Information',
    'lang_dsl_msg': 'DSL Info',
    'lang_lan_clients': "LAN Client List",
    'lang_lan_connection': "LAN Connections Status",
    'lang_lan_status': "LAN Statistics",
    'lang_connection_status': "WAN Connections Status",
    'lang_wan_status': "WAN Statistics",
    'lang_wireless_connection': "Wireless Connections Status",
    'lang_wireless_status': "Wireless Statistics",
    'lang_usb_status': "USB Information",
    //setup
    'Word_setup': 'Setup',
    'lang_submenu_lan': 'LAN Config',
    'lang_lan': 'LAN Basic',
    'lang_lanIPV6': 'IPv6 LAN',
    'lang_wanIPV6': 'IPv6 WAN',
    'lang_lan_advanced': 'WAN Advanced',
    'lang_submenu_wan': 'WAN Config',
    'lang_connected': 'WAN',
    'lang_wan_advanced': 'WAN Advanced',
    'lang_mobile_msg': 'Moblie Network Information',
    'lan_wan_vlan': 'WAN VLAN',
    'lang_dsl_set': 'DSL Configuration',
    'lang_atm_set': 'ATM Configuration',
    //wizard
    'Word_wizard': 'Wizard',
    'langs_wizard': 'Quick Setup',

    //advanced
    'Word_advanced': "Advanced",
    'lang_alg': "ALG",
    'lang_dhcp_filter': "DHCP Filter",
    'lang_mac_list': "MAC Filter",
    'lang_napt': "Virtual Server",
    'lang_dnsAgent': "DNS Proxy",
    'lang_dnsConfig': "DNS Configuration",
    'lang_qosInterface': "QoS Interface",
    'lang_qosQueue': "QoS Queue",
    'lang_qosFlux': "QoS Flux",
    'lang_dos': "Anti Attack",
    'lang_ipList': "IP Filter",
    'lang_ipv4List': "IPV4 Filter",
    'lang_ipv6List': "IPV6 Filter",
    'lang_accessCtrl': "Access Control",
    'lang_local_access_ctrl': "Local Access Control",
    'lang_remote_access_ctrl': "Remote Access Control",
    'lang_QoS': "QoS",
    'lang_igmpAgent': "IGMP Proxy",
    'lang_igmpSnooping': "IGMP Snooping",
    'lang_igmpv6Agent': "MLD Proxy",
    'lang_igmpv6Snooping': "MLD Snooping",
    'lang_Routing': "Routing",
    'lang_staticRouting': "Static Routing",
    'lang_dynamicRouting': "Dynamic Routing",
    'lang_sntp': "Time Server",
    'lang_schedule': "Schedule",
    'lang_vlan': "VLAN",
    'lang_ftpd_setting_title': "FTP Server Setting",
    'lang_ftpd_account_menu': "FTP Server Account",
    'lang_samba_config': "Samba Config",
    'lang_samba_setting_title': "Samba Server Setting",
    'lang_samba_account_menu': "Samba Server Account",
    'lang_ippd': "Print Server",
    'lang_nat_priority': "NAT Priority",
    'lang_dmz': "DMZ",
    'lang_ipunnumber': "IP UNNumber",
    'lang_upnp': "UPnP",
    'lang_urlFilter': "URL Filter",
    'lang_stp': "STP",
    'lang_3G': "3G",

    //wireless
    'Word_wireless': 'Wireless',
    'lang_wireless_setup': 'Basic',
    'lang_wireless_vap': 'SSID',
    'lang_wireless_advanced': 'Advanced',
    'lang_wireless_repeater': 'Repeater',
    'lang_wireless_wds': 'WDS Configuration',
    'lang_wps_setup': 'WPS Configuration',
    //management
    'Word_management': 'Management',
    'lang_system_management': 'System Management',
    'lang_user_management': 'User Management',
    'lang_dgn': 'Diagnosis',
    'lang_ping': 'Ping Diagnosis',
    'lang_dgn_tracert': 'Traceroute Diagnosis',
    'lang_tr069': 'TR069 Configuration',
    'lang_snmp': 'SNMP Configuration',
    'lang_config_update': 'Config Upgrade',
    'lang_3gconfig_update': '3G Config Upgrade',
    'lang_img_update': 'Image Upgrade', //  zp modify  20120517  'Firmware Upgrade',
    'lang_log': 'Log Configuration',
    'lang_logview': 'Log View'
};
