// JavaScript Document
var multiLanguage_setting_array =new Array();
multiLanguage_setting_array = [
							   	[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Apply",
								 "Cancel",
								 "General Setting",
								 "Download to",
								 "Browse",
								 "Refresh rate",
								 "Seconds",
								 "WAN network",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent Setting",
								 "Port",
								 "Use the default port",
								 "Use the following port",
								 "Incoming port:",
								 "Speed Limits:",
								 "Maximum download speed:",
								 "Unlimited",
								 "KB/S",
								 "Maximum upload speed:",
								 "BitTorrent Network setting",
								 "BitTorrent protocol encryption",
								 "Encryption disabled",
								 "Encryption enabled",
								 "Encryption required",
								 "Maximum peers allowed per torrent",
								 "DHT network",
								 "Enable DHT to activate trackerless torrent downloading activities.",
								 "NZB Setting",
								 "Setup USENET server to download NZB files:",
								 "USENET Server",
								 "USENET Server Port",
								 "SSL/TLS connection only",
								 "User name",
								 "Password",
								 "Confirm Password",
								 "Number of connections per NZB tasks",
								 "Notice",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "add"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "套用本頁面設定",
								 "取消",
								 "一般設定",
								 "Download to",
								 "瀏覽",
								 "更新率",
								 "秒",
								 "WAN 網路",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent 設定",
								 "埠號(Port)",
								 "使用預設埠",
								 "使用以下埠",
								 "來源埠",
								 "速度限制",
								 "最大下載速度：",
								 "Unlimited",
								 "KB/S",
								 "最大上傳速度：",
								 "BitTorrent 網路設定",
								 "BitTorrent 協定加密",
								 "加密關閉",
								 "加密開啟",
								 "需要加密",
								 "每 Torrent 允許的最多同伴數",
								 "DHT 網路",
								 "開啟 DHT 以啟用無追蹤的 Torrent 下載活動。",
								 "NZB 設定",
								 "設定 USENET 伺服器來下載 NZB 檔案：",
								 "USENET 伺服器",
								 "USENET 伺服器連接埠",
								 "僅限 SSL/TLS 連線",
								 "帳號",
								 "密碼",
								 "確認密碼",
								 "每項 NZB 任務的連線數",
								 "註：",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "新增"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "应用本页面设置",
								 "取消",
								 "一般设置",
								 "Download to",
								 "浏览",
								 "刷新率",
								 "秒",
								 "WAN 网络",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent 设置",
								 "接口(port)",
								 "使用默认接口",
								 "使用以下接口",
								 "来源接口",
								 "速度限制",
								 "最大下载速度：",
								 "Unlimited",
								 "KB/S",
								 "最大上传速度：",
								 "BitTorrent 网络设置",
								 "BitTorrent 协议加密",
								 "加密关闭",
								 "加密开启",
								 "需要加密",
								 "每 Torrent 允许的最多同伴数",
								 "DHT 网络",
								 "开启 DHT 以激活无追踪的 Torrent 下载活动。",
								 "NZB 设置",
								 "设置 USENET 服务器来下载 NZB 文件：",
								 "USENET 服务器",
								 "USENET 服务器接口",
								 "仅限 SSL/TLS 连接",
								 "帐号",
								 "密码",
								 "确认密码",
								 "每项 NZB 任务的连接数",
								 "注：",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "新增"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Применить ",
								 "Отмена",
								 "Общие настройки",
								 "Download to",
								 "Обзор",
								 "Частота обновления",
								 "Секунды",
								 "WAN сеть",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Настройка BitTorrent",
								 "Порт",
								 "Использовать порт по умолчанию",
								 "Использовать следующий порт",
								 "Входящий порт:",
								 "Ограничения скорости:",
								 "Максимальная скорость загрузки:",
								 "Unlimited",
								 "KB/c",
								 "Максимальная скорость отдачи:",
								 "Настройка сети BitTorrent",
								 "Протокол шифрования BitTorrent",
								 "Шифрование отключено",
								 "Шифрование включено",
								 "Требуется шифрование",
								 "Максимальное количество пиров для торрента",
								 "DHT сеть",
								 "Включить DHT для раздачи без трекера (trackerless)",
								 "Настройка NZB",
								 "Настройка сервера USENET для загрузки файлов NZB:",
								 "Сервера USENET",
								 "Порт сервера USENET",
								 "Только подключения SSL/TLS",
								 "Имя пользователя",
								 "Пароль",
								 "Подтверждение пароля",
								 "Количество подключений для загрузок NZB",
								 "Обратите внимание",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Добавить "
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Appliquer",
								 "Annuler",
								 "Options générales",
								 "Download to",
								 "Parcourir",
								 "Fréquence d'actualisation",
								 "Secondes",
								 "Réseau étendu (WAN)",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Paramètres BitTorrent",
								 "Port",
								 "Utiliser le port par défaut",
								 "Utiliser le port suivant",
								 "Port entrant :",
								 "Limites :",
								 "Vitesse de téléchargement maximum :",
								 "Unlimited",
								 "KB/S",
								 "Vitesse de transmission maximum :",
								 "Paramètres de réseau BitTorrent",
								 "Protocole de chiffrement BitTorrent",
								 "Chiffrement désactivé",
								 "Chiffrement activé",
								 "Chiffrement requis",
								 "Nombre de client maximum autorisés par torrent",
								 "Réseau DHT",
								 "Activez le réseau DHT pour autoriser le téléchargement de torrent sans tracker.",
								 "Paramètres NZB",
								 "Configuration de compte USENET pour le téléchargement de fichiers NZB :",
								 "Serveur USENET",
								 "Port de serveur USENET",
								 "Connexion SSL/TLS uniquement",
								 "Nom d'utilisateur",
								 "Mot de passe",
								 "Confirmation",
								 "Nombre de connexions par tâche NZB",
								 "Remarque :",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Ajouter une tâche"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Anwenden",
								 "Abbrechen",
								 "Allgemeine Einstellungen",
								 "Download to",
								 "Durchsuchen",
								 "Auffrischungsrate",
								 "Sekunden",
								 "WAN-Netzwerk",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent -Einstellungen",
								 "Port",
								 "Standard-Port verwenden",
								 "Folgenden Port verwenden",
								 "Eingehender Port:",
								 "Geschwindigkeitsgrenze:",
								 "Maximale Download-Geschwindigkeit:",
								 "Unlimited",
								 "KB/S",
								 "Maximale Upload-Geschwindigkeit:",
								 "BitTorrent-Netzwerkeinstellungen",
								 "BitTorrent-Protokollverschlüsselung",
								 "Verschlüsselung deaktiviert",
								 "Verschlüsselung aktiviert",
								 "Verschlüsselung erforderlich",
								 "Maximal erlaubte Peer-Anzahl pro Torrent",
								 "DHT-Netzwerk",
								 "DHT aktivieren, um Torrent-Download-Aktivitäten ohne Tracker zu aktivieren.",
								 "NZB-Einstellungen",
								 "USENET-Server zum Herunterladen von NZB-Dateien einrichten:",
								 "USENET-Server",
								 "USENET-Server-Port",
								 "Nur SSL/TLS-Verbindung",
								 "Benutzername",
								 "Kennwort",
								 "Kennwort bestätigen",
								 "Anzahl der Verbindungen pro NZB-Aufgabe",
								 "Hinweis:",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Aufgabe hinzufügen"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Aplicar",
								 "Cancelar",
								 "Configuração geral",
								 "Download to",
								 "Navegar",
								 "Taxa de atualização",
								 "Segundos",
								 "Rede WAN",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Configuração do BitTorrent",
								 "Porta",
								 "Usar a porta padrão",
								 "Use a seguinte porta",
								 "Porta de entrada:",
								 "Limites de velocidade:",
								 "Velocidade máxima de download:",
								 "Unlimited",
								 "KB/S",
								 "Velocidade máxima de upload:",
								 "Configurações de rede BitTorrent ",
								 "Criptografia do protocolo BitTorrent",
								 "Criptografia desabilitada",
								 "Criptografia habilitada",
								 "Criptografia necessária",
								 "Amigos máximos permitos por torrent",
								 "Rede DHT",
								 "Habilitar DHT para ativar atividades de download de torrent sem registro.",
								 "Configuração NZB",
								 "Configurar o servidor USENET para baixar arquivos NZB:",
								 "Servidor USENET",
								 "Porta do servidor USENET",
								 "Conexão SSL/TLS apenas",
								 "Nome de usuário",
								 "Senha",
								 "Confirmar Senha",
								 "Número de conexões por tarefa NZB",
								 "Aviso",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Adicionar"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Použít",
								 "Storno",
								 "Obecné nastavení",
								 "Download to",
								 "Procházet",
								 "Obnovovací frekvence",
								 "Sec",
								 "Síť WAN",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Nastavení BitTorrent",
								 "Port",
								 "Použít výchozí port",
								 "Použít následující port",
								 "Příchozí port:",
								 "Omezení rychlosti:",
								 "Maximální rychlost stahování:",
								 "Unlimited",
								 "KB/S",
								 "Maximální rychlost odesílání:",
								 "Nastavení sítě BitTorrent",
								 "Šifrování protokolu BitTorrent",
								 "Šifrování zakázáno",
								 "Šifrování povoleno",
								 "Šifrování vyžadováno",
								 "Maximální počet rovnocenných spojení na soubor torrent",
								 "Síť DHT",
								 "Povolením DHT budou aktivovány aktivity stahování nesledovaných souborů torrent.",
								 "Nastavení NZB",
								 "Nakonfigurujte server USENET pro stahování souborů NZB:",
								 "Server USENET",
								 "Port serveru USENET",
								 "Pouze připojení SSL/TLS",
								 "Uživatelské jméno",
								 "Heslo",
								 "Potvrzení hesla",
								 "Počet připojení na úkoly NZB",
								 "Oznámení",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Přidat"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Anvend",
								 "Annuller",
								 "Generelle indstillinger",
								 "Download to",
								 "Gennemse",
								 "Opdateringsfrekvens",
								 "Sek.",
								 "WAN-netværk",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Indstillinger for BitTorrent",
								 "Port",
								 "Brug standardporten",
								 "Brug følgende port",
								 "Indgående port:",
								 "Båndbreddebegrænsninger:",
								 "Maks. båndbredde til download:",
								 "Unlimited",
								 "KB/S",
								 "Maks. båndbredde til upload:",
								 "Indstillinger til BitTorrent-netværk",
								 "Protokolkryptering til BitTorrent",
								 "Kryptering deaktiveret",
								 "Kryptering aktiveret",
								 "Kryptering påkrævet",
								 "Maks. peers tilladt per torrent",
								 "DHT-netværk",
								 "Aktiver DHT for at aktivere aktiviteter med torrent-download uden tracker.",
								 "NZB-indstillinger",
								 "Sæt USENET-server op for at downloade NZB-filer:",
								 "USENET-server",
								 "Port til USENET-server",
								 "Kun SSL/TLS-forbindelse",
								 "Brugernavn",
								 "Adgangskode",
								 "Bekræft adgangskode",
								 "Antal forbindelser per NZB-opgave",
								 "Bemærk",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Tilføj"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Käytä",
								 "Peruuta",
								 "Yleinen asetus",
								 "Download to",
								 "Selaa",
								 "Virkistystaajuus",
								 "Sekunnit",
								 "WAN-verkko",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent-asetus",
								 "Portti",
								 "Käytä oletusporttia",
								 "Käytä seuraavaa porttia",
								 "Saapuva-portti:",
								 "Nopeusrajat:",
								 "Maksimi latausnopeus:",
								 "Unlimited",
								 "KB/S",
								 "Maksimi lähetysnopeus:",
								 "BitTorrent-verkkoasetus",
								 "BitTorrent-protokollasalaus",
								 "Salaus otettu pois käytöstä",
								 "Salaus otettu käyttöön",
								 "Salaus vaaditaan",
								 "Maksimi vertaisten sallittu määrä torrenttia kohti",
								 "DHT-verkko",
								 "Ota DHT käyttöön aktivoidaksesi seuraimettomia torrenttitoimintoja.",
								 "NZB-asetus",
								 "Aseta USENET-palvelin lataamaan NZB-tiedostoja:",
								 "USENET-palvelin",
								 "USENET-palvelinportti",
								 "Vain SSL/TLS-yhteys",
								 "Käyttäjänimi",
								 "Salasana",
								 "Vahvista salasana",
								 "Yhteyksien määrä NZB-tehtävää kohti",
								 "Huomaa",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Lisää tehtävä"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Gunakan",
								 "Batal",
								 "Tetapan Umum",
								 "Download to",
								 "Semak imbas",
								 "Kadar segar semula",
								 "Saat",
								 "Rangkaian WAN",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Tetapan BitTorrent",
								 "Port",
								 "Gunakan port lalai",
								 "Gunakan port yang berikut",
								 "Port masuk:",
								 "Hak Kelajuan:",
								 "Kelajuan muat turun maksimum:",
								 "Unlimited",
								 "KB/S",
								 "Kelajuan muat naik maksimum:",
								 "Tetatpan Rangkaian BitTorrent",
								 "Penyulitan protokol BitTorrent",
								 "Penyulitan dinyahdayakan",
								 "Penyulitan didayakan",
								 "Penyulitan diperlukan",
								 "Rakan maksimum dibenarkan bagi setiap torrent",
								 "Rangkaian DHT",
								 "Dayakan DHT untuk mengaktifkan aktiviti muat turun torrent bebas penjejak.",
								 "Tetapan NZB",
								 "Sediakan pelayan USENET untuk memuat turun fail NZB:",
								 "Pelayan USENET",
								 "Port Pelayan USENET",
								 "Sambungan SSL/TLS sahaja",
								 "Nama pengguna",
								 "Kata Laluan",
								 "Sahkan Kata Laluan",
								 "Bilangan sambungan setiap tugas NZB",
								 "Notis",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Tambah"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Bruk",
								 "Avbryt",
								 "Generell innstilling",
								 "Download to",
								 "Utforsk",
								 "Oppdateringshastighet",
								 "Sekunder",
								 "WAN-nettverk",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent-innstilling",
								 "Port",
								 "Bruk standard port",
								 "Bruk følgende port",
								 "Innkommende port:",
								 "Hastighetsgrenser:",
								 "Maks nedlastningshastighet:",
								 "Unlimited",
								 "KB/S",
								 "Maks opplastningshastighet:",
								 "BitTorrent-nettverksinnstilling",
								 "BitTorrent-protokollkryptering",
								 "Kryptering deaktivert",
								 "Kryptering aktivert",
								 "Kryptering kreves",
								 "Maks noder tillatt per torrent",
								 "DHT-nettverk",
								 "Tillat DHT å aktivere torrent-nedlastningsaktiviteter uten sporing.",
								 "NZB-innstilling",
								 "Sett opp USENET-server for å laste ned NZB-filer:",
								 "USENET-server",
								 "USENET-serverport",
								 "Kun SSL/TLS-tilkobling",
								 "Brukernavn",
								 "Passord",
								 "Bekreft passord",
								 "Antall tilkoblinger per NZB-oppgave",
								 "Merknad",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Legg til"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Zastosuj",
								 "Anuluj",
								 "Ustawienia ogólne",
								 "Download to",
								 "Przeglądaj",
								 "Częstotliwość odświeżania",
								 "Sekundy",
								 "Sieć WAN",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "Ustawienia BitTorrent",
								 "Port",
								 "Użyj portu domyślnego",
								 "Użyj następującego portu",
								 "Port przychodzący:",
								 "Ograniczenia prędkości:",
								 "Maksymalna prędkość pobierania:",
								 "Unlimited",
								 "KB/S",
								 "Maksymalna prędkość przesyłania:",
								 "Ustawienia sieci BitTorrent",
								 "Szyfrowanie protokołu BitTorrent",
								 "Szyfrowanie wyłączone",
								 "Szyfrowanie włączone",
								 "Szyfrowanie wymagane",
								 "Maksymalna dopuszczalna liczba pobierających na torrent",
								 "Sieć DHT",
								 "Włącz DHT, aby aktywować czynności pobierania z torrent bez śledzenia.",
								 "Ustawienia NZB",
								 "Ustaw serwer USENET, aby pobierać pliki NZB:",
								 "Serwer USENET",
								 "Port serwera USENET",
								 "Tylko połączenie SSL/TLS",
								 "Nazwa użytkownika",
								 "Hasło",
								 "Potwierdź hasło",
								 "Ilość połączeń na zadanie NZB",
								 "Uwaga",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Dodaj"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Tillämpa",
								 "Avbryt",
								 "Allmän inställning",
								 "Download to",
								 "Bläddra",
								 "Uppdateringsfrekvens",
								 "Sekunder",
								 "WAN-nätverk",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent-inställning",
								 "Port",
								 "Använd standardporten",
								 "Använd följande port",
								 "Inkommande port:",
								 "Hastighetsgränser:",
								 "Max. nedladdningshastighet:",
								 "Unlimited",
								 "KB/S",
								 "Max. uppladdningshastighet:",
								 "BitTorrent nätverksinställning",
								 "BitTorrent protokollkryptering",
								 "Kryptering inaktiverad",
								 "Kryptering aktiverad",
								 "Kryptering krävs",
								 "Max. peers tillåtna per torrent",
								 "DHT-nätverk",
								 "Aktivera DHT för att aktivera spårarlösa torrent nedladdningsaktiviteter.",
								 "NZB-inställning",
								 "Konfigurera USENET-server så att NZB-filerna laddas ner:",
								 "USENET-server",
								 "USENET-serverport",
								 "Endast SSL/TLS-anslutning",
								 "Användarnamn",
								 "Lösenord",
								 "Bekräfta lösenord",
								 "Antal anslutningar per NZB-uppgifter",
								 "Obs",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Lägg till uppgift"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "นำไปใช้",
								 "ยกเลิก",
								 "การตั้งค่าทั่วไป",
								 "Download to",
								 "เรียกดู",
								 "อัตราการรีเฟรช",
								 "วินาที",
								 "เครือข่าย WAN ",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "การตั้งค่า BitTorrent",
								 "พอร์ต",
								 "ใช้พอร์ตเริ่มต้น",
								 "ใช้พอร์ตต่อไปนี้",
								 "พอร์ตขาเข้า:",
								 "ขีดจำกัดความเร็ว:",
								 "ความเร็วการดาวน์โหลดสูงที่สุด:",
								 "Unlimited",
								 "KB/วินาที",
								 "ความเร็วการอัปโหลดสูงที่สุด:",
								 "การตั้งค่าเครือข่าย BitTorrent",
								 "การเข้ารหัสโปรโตคอล BitTorrent",
								 "การเข้ารหัสปิดทำงานแล้ว",
								 "การเข้ารหัสเปิดทำงานแล้ว",
								 "จำเป็นต้องมีการเข้ารหัส",
								 "เพียร์สูงสุดที่อนุญาตต่อทอร์เร้นต์",
								 "เครือข่าย DHT",
								 "เปิดทำงาน DHT เพื่อเปิดทำงานกิจกรรมการดาวน์โหลดทอร์เร้นต์แบบแทร็กเกอร์เลส",
								 "การตั้งค่า NZB",
								 "ตั้งค่า USENET เซิร์ฟเวอร์เพื่อดาวน์โหลดไฟล์ NZB:",
								 "USENET เซิร์ฟเวอร์",
								 "พอร์ต USENET เซิร์ฟเวอร์",
								 "การเชื่อมต่อ SSL/TLS เท่านั้น",
								 "ชื่อผู้ใช้",
								 "รหัสผ่าน",
								 "ยืนยันรหัสผ่าน",
								 "จำนวนของการเชื่อมต่อต่องาน NZB ",
								 "ข้อสังเกต",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "เพิ่ม"
								 ],
								[
								 "Please key in the floder name",
								 "Floder Name:",
								 "Uygula",
								 "İptal",
								 "Genel Ayar",
								 "Download to",
								 "Gözat",
								 "Yenileme hızı",
								 "Saniye",
								 "WAN ağı",
								 "Enable allow connections from the WAN side.",
								 "DownloadMaster Port",
								 "BitTorrent Ayarı",
								 "Bağlantı Noktası",
								 "Varsayılan bağlantı noktasını kullan",
								 "Aşağıdaki bağlantı noktasını kullan",
								 "Gelen bağlantı noktası:",
								 "Hız Sınırları:",
								 "Maksimum indirme hızı:",
								 "Unlimited",
								 "KB/S",
								 "Maksimum yükleme hızı:",
								 "BitTorrent Ağ ayarı",
								 "BitTorrent protokol şifreleme",
								 "Şifreleme engelli",
								 "Şifreleme etkin",
								 "Şifreleme gereklidir",
								 "Torrent başına izin verilen maksimum eşleştirme",
								 "DHT ağı",
								 "İzlemesiz torrent indirme aktivitelerini etkinleştirmek için DHT’yi etkinleştirin.",
								 "NZB Ayarı",
								 "USENET sunucusunu ayarlayarak NZB dosyalarını indirin:",
								 "USENET Sunucusu",
								 "USENET Sunucusu Bağlantı Noktası",
								 "Sadece SSL/TLS bağlantısı",
								 "Kullanıcı adı",
								 "Parola",
								 "Parolayı Onayla ",
								 "NZB görevleri başına bağlantı sayısı",
								 "Uyarı",
								 "please enter the USENET Server!",
								 "please enter the USENET Server Port!",
								 "please enter the Number of connections per NZB tasks!",
								 "Please key in the username.",
								 "Please key in the password.",
								 "Please check the password.",
								 "Please key in the correct USENET server port.",
								 "Please key in the correct maximum download speed.",
								 "Please key in the correct number of connections per NZB tasks.",
								 "Please key in the correct incoming port.",
								 "Please key in the correct maximum upload speed.",
								 "Please key in the correct maximum peers allowed per torrent.",
								 "The Download Master port must be different from the router port.",
								 "Please key in a port range value between 2 to 65535.",
								 "The DM Port is",
								 ".If you changed the Download Master port, please key in the correct port to enter Download Master.",
								 "Share name cannot be blank.",
								 "Share name can only contain alphanumeric/dash/underscore/space characters.",
								 "The share name already exists in this volume.",
								 "Please enter a different name!",
								 "Creating a share with more than 12 characters may make it invisible in some Windows® version.",
								 "Do you want to continue?",
								 "Please select the desire folder",
								 "Refresh",
								 "Ekle"
								 ]
							   
							   ]