// JavaScript Document
var multiLanguage_array =new Array();
multiLanguage_array = [
					   ["Initializing torrent downloading proces...",
						"Please wait a moment",
						"There are no completed tasks.",
						"Notice",
						"The URL is blank.",
						"The URL length must be less than 1024 characters.",
						"Please key in a URL or select a file.",
						"Please select the right file.",
						"Failed to delete the task.",
						"Failed to add the new task.",
						"The task already exists.",
						"The http/ftp task list is full.",
						"The BT task list is full.",
						"The NZB task list is full.",
						"The task list is full.",
						"Are you sure you want to delete?",
						"Add a file or a URL to the download task list",
						"Please select a torrent or NZB file to upload",
						"File:",
						"Key in the HTTP, FTP, Magnet, ed2k, Torrent, or NZB URL",
						"Apply",
						"Cancel",
						"Add",
						"Remove",
						"Pause",
						"Resume",
						"Pause All",
						"Resume All",
						"Clear Completed Tasks",
						"Home",
						"Transfers",
						"All",
						"Downloading",
						"Seeding",
						"Paused",
						"Finished",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Downloaded:",
						"Uploaded:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["初始化 Torrent 下載中…",
						"請稍候",
						"沒有已完成任務。",
						"註：",
						"URL 為空。",
						"URL 的長度必須少於 1024 個字元。",
						"請輸入一個 URL 或選擇一個檔案。",
						"請選擇正確的檔案。",
						"移除任務失敗。",
						"Failed to add the new task.",
						"此任務已存在。",
						"http/ftp 任務清單已滿。",
						"BT 任務清單已滿。",
						"NZB 任務清單已滿。",
						"任務清單已滿。",
						"您確定要移除嗎？",
						"新增一個檔案或 URL 至下載任務清單",
						"請選擇一個要上傳的 Torrent 或 NZB 檔案",
						"檔案:",
						"輸入  HTTP、FTP、Magnet、ed2k、Torrent 或 NZB URL",
						"套用本頁面設定",
						"取消",
						"新增",
						"刪除",
						"暫停",
						"開始",
						"全部暫停",
						"全部開始",
						"清除已完成任務",
						"主頁",
						"傳送",
						"全部",
						"下載中",
						"Seeding",
						"已暫停",
						"已完成",
						"資訊",
						"片段:",
						"無用資訊:",
						"安全性:",
						"評論:",
						"已建立",
						"建立者:",
						"日期:",
						"位置",
						"下載目錄:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"活動",
						"過程:",
						"大小:",
						"狀態:",
						"可用性:",
						"已下載:",
						"已上傳:",
						"下載速度:",
						"上傳速度:",
						"錯誤:",
						"比率:",
						"Peers:",
						"上傳至:",
						"下載自:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"等級",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["正在初始化 Torrent 下载…",
						"请稍候",
						"没有已完成任务。",
						"注：",
						"URL 为空。",
						"URL 的长度必须少于 1024 个字符。",
						"请输入一个 URL 或选择一个文件。",
						"请选择正确的文件。",
						"删除任务失败。",
						"Failed to add the new task.",
						"此任务已存在。",
						"http/ftp 任务列表已满。",
						"BT 任务列表已满。",
						"NZB 任务列表已满。",
						"任务列表已满。",
						"您确定要删除吗？",
						"添加一个文件或 URL 至下载任务列表",
						"请选择一个要上传的 Torrent 或 NZB 文件",
						"文件:",
						"输入 HTTP、FTP、Magnet、ed2k、Torrent 或 NZB URL",
						"应用本页面设置",
						"取消",
						"新增",
						"刪除",
						"暂停",
						"开始",
						"全部暂停",
						"全部开始",
						"清除已完成任务",
						"主页",
						"发送",
						"全部",
						"正在下载",
						"Seeding",
						"已暂停",
						"已完成",
						"信息",
						"片段:",
						"无用信息:",
						"安全性:",
						"评论:",
						"已创建",
						"创建者:",
						"日期:",
						"位置",
						"下载目录:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"活动",
						"过程:",
						"大小:",
						"状态:",
						"可用性:",
						"已下载:",
						"已上传:",
						"下载速度:",
						"上传速度:",
						"错误:",
						"比率:",
						"Peers:",
						"上传至:",
						"下载自:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"等级",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Инициализация процесса загрузки торрента..",
						"Пожалуйста, подождите",
						"Нет завершенных загрузок",
						"Обратите внимание",
						"URL пуст",
						"Длина URL должна быть не менее 1024 символов",
						"Пожалуйста, введите URL или выберите файл",
						"Пожалуйста, выберите правильный файл",
						"Не удалось удалить задачу",
						"Failed to add the new task.",
						"Задача уже существует",
						"Список задач http/ftp заполнен",
						"Список задач BT заполнен",
						"Список задач NZB заполнен",
						"Список задач заполнен",
						"Вы хотите удалить?",
						"Добавить файл или URL в список загрузок",
						"Выберите для загрузки файл torrent или NZB",
						"Файл:",
						"Введите URL для HTTP, FTP, Magnet, ed2k, Torrent или NZB",
						"Применить",
						"Отмена",
						"Добавить",
						"Удалить",
						"Пауза",
						"Возобновить",
						"Приостановить все",
						"Возобновить все",
						"Очистить завершенные загрузки",
						"Главный экран",
						"Передано",
						"Все",
						"Загрузка",
						"Раздача",
						"Приостановлена",
						"Завершена",
						"Информация",
						"Части:",
						"Хэш:",
						"Безопасность:",
						"Комментарий:",
						"Создано",
						"Создатель:",
						"Дата:",
						"Где",
						"Директория для загрузки:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Активность",
						"прогресс:",
						"размер:",
						"статус:",
						"доступность:",
						"Загружено:",
						"Отдано:",
						"Скорость загрузки:",
						"Скорость отдачи:",
						"Ошибка:",
						"Показатель:",
						"Загружающий:",
						"Загрузить на:",
						"Скачать с:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Ряд",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Initialisation du processus de téléchargement de torrent…",
						"Veuillez patienter un instant",
						"Aucune tâche terminée.",
						"Remarque :",
						"Le champ réservé à l'URL est vide",
						"La longueur de l'URL ne doit pas dépasser 1024 caractères",
						"Veuillez entrer une URL ou sélectionner un fichier.",
						"Veuillez sélectionner le bon fichier.",
						"Échec de suppression de la tâche.",
						"Failed to add the new task.",
						"Cette tâche existe déjà.",
						"La liste des tâches HTTP/FTP est pleine.",
						"La liste des tâches BT est pleine.",
						"La liste des tâches NZB est pleine.",
						"La liste des tâches est pleine.",
						"Souhaitez-vous vraiment supprimer ce(s) fichier(s) ?",
						"Ajouter une tâche ou une URL à télécharger",
						"Veuillez sélectionner un fichier Torrent ou NZB à transmettre",
						"Fichier:",
						"Veuillez entrer l'URL du fichier HTTP, FTP, Magnet, ed2k, Torrent ou NZB",
						"Appliquer",
						"Annuler",
						"Ajouter une tâche",
						"Supprimer",
						"Pause",
						"Démarrer",
						"Suspendre tout",
						"Démarrer tout",
						"Effacer les tâches terminées",
						"Accueil",
						"Transferts",
						"Tout",
						"En cours",
						"Seeding",
						"Suspendu",
						"Terminé",
						"Informations",
						"Pièces:",
						"Hash:",
						"Sécurité:",
						"Commentaires:",
						"Créé par",
						"Auteur:",
						"Date:",
						"Emplacement",
						"Répertoire:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activité",
						"Progression:",
						"Taille:",
						"État:",
						"Disponibilité:",
						"Téléchargé:",
						"Transmis:",
						"Vitesse de téléchargement:",
						"Vitesse de transmission:",
						"Erreur:",
						"Ratio:",
						"Peers:",
						"Transmettre vers:",
						"Télécharger de:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Niveau",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						
						],
					   
					   ["Torrent-Download-Prozess wird initialisiert...",
						"Bitte einen Moment warten",
						"Keine fertigen Aufgaben verfügbar.",
						"Hinweis:",
						"Die URL ist leer.",
						"Die URL darf nicht länger als 1024 Zeichen sein.",
						"Bitte geben Sie eine URL ein oder wählen Sie eine Datei aus.",
						"Bitte die richtige Datei auswählen.",
						"Löschen der Aufgabe fehlgeschlagen",
						"Failed to add the new task.",
						"Die Aufgabe existiert schon.",
						"Die HTTP/FTP-Aufgabenliste ist voll.",
						"Die BT-Aufgabenliste ist voll.",
						"Die NZB-Aufgabenliste ist voll.",
						"Die Aufgabenliste ist voll.",
						"Wollen Sie diese wirklich löschen?",
						"Datei oder URL zur Download-Aufgabenliste hinzufügen.",
						"Bitte Torrent- oder NZB-Datei für das Hochkladen auswählen.",
						"Datei:",
						"Geben Sie die HTTP-, FTP-, Magnet-, ed2k-, Torrent- oder NZB-URL ein.",
						"Anwenden",
						"Abbrechen",
						"Aufgabe hinzufügen",
						"Löschen",
						"Pause",
						"Start",
						"Alle pausieren",
						"Alle starten",
						"Fertige Aufgaben löschen",
						"Home",
						"Übertragungen",
						"Alle",
						"Herunterladen",
						"Seeden",
						"Pausiert",
						"Beendet",
						"Information",
						"Teile:",
						"Hash:",
						"Sichern:",
						"Kommentar:",
						"Erstellt",
						"Ersteller:",
						"Datum:",
						"Wo",
						"Download-Verzeichnis:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Aktivität",
						"Fortschritt:",
						"Größe:",
						"status:",
						"Verfügbarkeit:",
						"Heruntergeladen:",
						"Hochgeladen:",
						"Download-Geschwindigkeit:",
						"Uplooad-Geschwindigkeit:",
						"Fehler:",
						"Verhältnis:",
						"Peers:",
						"Hochladen nach:",
						"Herunterladen von:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Ebene",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Inicializando o processo de download de torrent...",
						"Por favor, aguarde um momento",
						"Não há tarefas completas.",
						"Aviso",
						"O URL está em branco.",
						"O URL não pode conter menos do que 1024 ",
						"Digite um URL ou selecione um arquivo.",
						"Seleciona o arquivo correto.",
						"Falha ao excluir a tarefa.",
						"Failed to add the new task.",
						"A tarefa já existe.",
						"A lista de tarefa http/ftp está cheia.",
						"A lista de tarefa BT está cheia.",
						"A lista de tarefa NZB está cheia.",
						"A lista de tarefa está cheia.",
						"Tem certeza de que deseja excluir?",
						"Adicionar um arquivo ou URL à lista de tarefa de download",
						"Selecione um arquivo torrent ou NZB para upload.",
						"Arquivo:",
						"Digite o URL do HTTP, FTP, Magnet, ed2k, Torrent, ou NZB",
						"Aplicar",
						"Cancelar",
						"Adicionar",
						"Remover",
						"Pausa",
						"Continuar",
						"Pausar tudo",
						"Resumir tudo",
						"Limpar tarefas completas",
						"Início",
						"Transferências",
						"Todos",
						"Fazendo Download",
						"Servindo",
						"Pausado",
						"Finalizado",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Baixado:",
						"Carregado:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Inicializace procesu stahování souborů torrent...",
						"Okamžik vyčkejte",
						"Nejsou k dispozici žádné dokončené úkoly.",
						"Oznámení",
						"Adresa URL je prázdná.",
						"Délka adresu URL musí být méně než 1024 znaků.",
						"Zadejte adresu URL nebo vyberte soubor.",
						"Vyberte správný soubor.",
						"Odstranění úkolu se nezdařilo.",
						"Failed to add the new task.",
						"Tento úkol již existuje.",
						"Seznam úkolů http/ftp je plný.",
						"Seznam úkolů BT je plný.",
						"Seznam úkolů NZB je plný.",
						"Seznam úkolů je plný.",
						"Opravdu chcete odstranit?",
						"Přidat soubor nebo adresu URL do seznamu úkolů stahování",
						"Vyberte soubor torrent nebo NZB k odeslání",
						"Soubor:",
						"Zadejte HTTP, FTP, Magnet, ed2k, Torrent nebo NZB URL",
						"Použít",
						"Storno",
						"Přidat",
						"Odstranit",
						"Pozastavit",
						"Obnovit",
						"Pozastavit vše",
						"Obnovit vše",
						"Vymazat dokončené úkoly",
						"Domů",
						"Přenosy",
						"Vše",
						"Stahování",
						"Ohlašování",
						"Pozastaveno",
						"Dokončeno",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Staženo:",
						"Odesláno:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Initialiserer downloadproces for torrent…",
						"Vent et øjeblik",
						"Der er ingen afsluttede opgaver.",
						"Bemærk",
						"URL-en er tom.",
						"URL'en skal være kortere end 1.024 tegn.",
						"Indtast en URL eller vælg en fil.",
						"Vælg den rigtige fil.",
						"Kunne ikke slette opgaven.",
						"Failed to add the new task.",
						"Opgaven findes allerede.",
						"Http/ftp opgavelisten er fyldt.",
						"Bt opgavelisten er fyldt.",
						"NZB opgavelisten er fyldt.",
						"Opgavelisten er fyldt.",
						"Er du sikker på, du vil slette?",
						"Tilføj en fil eller en URL til opgavelisten for download.",
						"Vælg en torrent- eller NZB-fil til upload",
						"Fil:",
						"Indtast HTTP, FTP, Magnet, ed2k, Torrent eller NZB URL",
						"Anvend",
						"Annuller",
						"Tilføj",
						"Fjern",
						"Pause",
						"Genoptag",
						"Sæt alle på pause",
						"Genoptag alle",
						"Ryd afsluttede opgaver",
						"Retur",
						"Overførsler",
						"Alle",
						"Downloader",
						"Seeder",
						"Sat på pause",
						"Afsluttet",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Downloaded:",
						"Uploaded:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Alustetaan torrentin latausprosessia...",
						"Odota hetki",
						"Valmiita tehtäviä ei ole.",
						"Huomaa",
						"URL on tyhjä.",
						"URL-pituuden on oltava alle 1024 merkkiä.",
						"Näppäile kenttään URL tai valitse tiedosto.",
						"Valitse oikea tiedosto.",
						"Tehtävän poistaminen epäonnistui.",
						"Failed to add the new task.",
						"Tehtävä on jo olemassa.",
						"http/ftp-tehtäväluettelo on täynnä.",
						"BT-tehtäväluettelo on täynnä.",
						"NZB-tehtäväluettelo on täynnä.",
						"Tehtäväluettelo on täynnä.",
						"Haluatko varmasti poistaa?",
						"Lisää tiedosto tai URL lataustehtäväluetteloon",
						"Valitse lähetettävä torrentti tai NZB-tiedosto",
						"Tiedosto:",
						"Näppäile HTTP-, FTP-, Magnet-, ed2k-, Torrent-, tai NZB-URL-osoite",
						"Käytä",
						"Peruuta",
						"Lisää tehtävä",
						"Poista",
						"Keskeytä",
						"Käynnistä",
						"Keskeytä kaikki",
						"Käynnistä kaikki",
						"Tyhjennä valmiit tehtävät",
						"Aloitusnäyttö",
						"Siirtää",
						"Kaikki",
						"Ladataan",
						"Alustus",
						"Keskeytetty",
						"Valmis",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Ladatut:",
						"Lähetetyt:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Memulakan proses muat turun torrent...",
						"Sila tunggu sebentar",
						"Tiada tugas yang telah selesai.",
						"Notis",
						"URL kosong.",
						"Panjang URL mesti kurang daripada 1024 aksara.",
						"Sila masukkan URL atau pilih fail.",
						"Sila pilih fail yang betul.",
						"Gagal untuk memadamkan tugas.",
						"Failed to add the new task.",
						"Tugas telah wujud.",
						"Senarai tugas http/ftp penuh.",
						"Senarai tugas BT penuh.",
						"Senarai tugas NZB penuh.",
						"Senarai tugas penuh.",
						"Anda pasti hendak memadamkan?",
						"Tambah fail atau URL pada senarai tugas muat turun",
						"Sila pilih fail torrent atau NZB untuk memuat naik",
						"Fail:",
						"Masukkan URL HTTP, FTP, Magnet, ed2k, Torrent, atau NZB",
						"Gunakan",
						"Batal",
						"Tambah",
						"Keluarkan",
						"Jeda",
						"Sambung",
						"Jeda Semua",
						"Sambung Semua",
						"Kosongkan Tugas yang Telah Selesai",
						"Rumah",
						"Pemindahan",
						"Semua",
						"Memuat turun",
						"Pembenihan",
						"Dijeda",
						"Selesai",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Dimuat turun:",
						"Dimuat naik:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Initialiserer torrent-nedlastningsprosess …",
						"Vent et øyeblikk",
						"Det finnes ingen fullførte oppgaver.",
						"Merknad",
						"URL-en er tom.",
						"URL-lengden må være mindre enn 1024 tegn.",
						"Tast inn en URL eller velg en fil.",
						"Velg riktig fil.",
						"Kunne ikke slette oppgaven.",
						"Failed to add the new task.",
						"Oppgaven finnes allerede.",
						"Http/ftp-oppgavelisten er full.",
						"BT-oppgavelisten er full.",
						"NZB-oppgavelisten er full.",
						"Oppgavelisten er full.",
						"Er du sikker på at du vil slette?",
						"Legg til en fil eller en URL til nedlastningsoppgavelisten",
						"Velg en torrent- eller NZB-fil for opplastning",
						"Fil:",
						"Tast inn HTTP, FTP, Magnet, ed2k, Torrent eller NZB URL",
						"Bruk",
						"Avbryt",
						"Legg til",
						"Fjern",
						"Pause",
						"Gjenoppta",
						"Pause alle",
						"Gjenoppta alle",
						"Fjern fullførte oppgaver",
						"Hjem",
						"Overføringer",
						"Alle",
						"Laster ned",
						"Seeding",
						"Pauset",
						"Fullført",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Nedlastet:",
						"Lastet opp:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Inicjalizacja procesu pobierania torrent...",
						"Proszę chwilę poczekać",
						"Brak zakończonych zadań.",
						"Uwaga",
						"Adres URL jest pusty.",
						"Długość adresu URL musi być krótsza niż 1024 znaków.",
						"Wpisz adres URL lub wybierz plik.",
						"Wybierz poprawny plik.",
						"Niepowodzenie usunięcia zadania.",
						"Failed to add the new task.",
						"Zadanie już istnieje.",
						"Lista zadań http/ftp pełna.",
						"Lista zadań BT pełna.",
						"Lista zadań NZB pełna.",
						"Lista zadań pełna.",
						"Czy jesteś pewien, że chcesz usunąć?",
						"Dodaj plik lub adres URL do listy zadań pobierania",
						"Wybierz plik torrent lub NZB do przesłania",
						"Plik:",
						"Wpisz adres URL HTTP, FTP, ed2k, Magnet, Torrent lub NZB",
						"Zastosuj",
						"Anuluj",
						"Dodaj",
						"Usuń",
						"Pauza",
						"Wznów",
						"Wstrzymaj wszystkie",
						"Wznów wszystkie",
						"Usuń zakończone zadania",
						"Strona główna",
						"Transfery",
						"Wszystkie",
						"Pobieranie",
						"Udostępnianie",
						"Wstrzymane",
						"Zakończone",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Pobrane:",
						"Przesłane:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["Initierar nedladdning av torrent...",
						"Vänta ett ögonblick",
						"Det finns inga slutförda uppgifter.",
						"Obs",
						"Webbadressen är tom.",
						"Längden på webbadressen måste vara mindre än 1024 tecken.",
						"Knappa in en webbadress eller välj en fil.",
						"Välj rätt fil",
						"Det gick inte att ta bort uppgiften.",
						"Failed to add the new task.",
						"Uppgiften finns redan.",
						"Uppgiftslistan http/ftp är full.",
						"Uppgiftslistan BT är full.",
						"Uppgiftslistan NZB är full.",
						"Uppgiftslistan är full.",
						"Är du säker på att du vill ta bort?",
						"Lägg till en fil eller en webbadress i listan över nedladdade uppgifter.",
						"Välj en torrent eller NZB fil att ladda upp",
						"Fil:",
						"Knappa in HTTP, FTP, Magnet, ed2k, Torrent eller NZB webbadressen",
						"Tillämpa",
						"Avbryt",
						"Lägg till uppgift",
						"Ta bort",
						"Paus",
						"Fortsätt",
						"Pausa alla",
						"Fortsätt alla",
						"Rensa slutförda uppgifter",
						"Hem",
						"Överföringar",
						"Alla",
						"Laddar ner",
						"Seeding",
						"Pausat",
						"Slut",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"Nedladdade:",
						"Uppladdade:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						],
					   
					   ["กำลังตั้งค่าเริ่มต้นกระบวนการดาวน์โหลดทอร์เร้นต์...",
						"โปรดรอสักครู่",
						"ไม่มีงานที่สมบูรณ์",
						"ข้อสังเกต",
						"URL ว่าง",
						"ความยาว URL ต้องน้อยกว่า 1024 ตัวอักษร",
						"โปรดป้อน URL หรือเลือกไฟล์",
						"โปรดเลือกไฟล์ที่ถูกต้อง",
						"ไม่สามารถลบงาน",
						"Failed to add the new task.",
						"งานมีอยู่แล้ว",
						"รายงานงาน http/ftp เต็ม",
						"รายงานงาน BT เต็ม",
						"รายงานงาน NZB เต็ม",
						"รายงานงานเต็ม",
						"แน่ใจว่าต้องการลบหรือไม่?",
						"เพิ่มไฟล์หรือ URL เพื่อดาวน์โหลดรายการงาน",
						"โปรดเลือกไฟล์ทอร์เร้นต์หรือไฟล์ NZB เพื่ออัปโหลด",
						"ไฟล์:",
						"ป้อน HTTP, FTP, Magnet, Torrent หรือ NZB URL",
						"นำไปใช้",
						"ยกเลิก",
						"เพิ่ม",
						"ลบ",
						"หยุดชั่วคราว",
						"ดำเนินการต่อ",
						"หยุดชั่วคราวทั้งหมด",
						"ดำเนินการต่อทั้งหมด",
						"ล้างงานที่สมบูรณ์แล้ว",
						"โฮม",
						"ถ่ายโอน",
						"ทั้งหมด",
						"กำลังดาวน์โหลด",
						"กำลังสีด",
						"หยุดชั่วคราว",
						"เสร็จแล้ว",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"ดาวน์โหลดแล้ว:",
						"อัปโหลดแล้ว:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						
						],
					   
					   ["Torrent indirme işlemini başlatıyor...",
						"Lütfen bir an bekleyin",
						"Tamamlanan görev yok.",
						"Uyarı",
						"URL boş.",
						"URL uzunluğu 1024 karakterden kısa olmalıdır.",
						"Lütfen bir URL girin veya bir dosya seçin.",
						"Lütfen doğru dosyayı seçin.",
						"Görevi silinemedi.",
						"Failed to add the new task.",
						"Görev zaten mevcut.",
						"http/ftp görev listesi dolu.",
						"BT görev listesi dolu.",
						"NZB görev listesi dolu.",
						"Görev listesi dolu.",
						"Silmek istediğinizden emin misiniz?",
						"İndirme görev listesine bir dosya veya URL ekleyin",
						"Lütfen bir torrent veya NZB dosyası seçerek yükleyin",
						"Dosya:",
						"HTTP, FTP, Magnet, ed2k, Torrent veya NZB URL girin",
						"Uygula",
						"İptal",
						"Ekle",
						"Kaldır",
						"Duraklat",
						"Devam Et",
						"Tümünü Duraklat",
						"Tümünü Devam Ettir",
						"Tamamlanan Görevleri Temizle",
						"Ana Sayfa",
						"Aktarımlar",
						"Tümü",
						"İndiriliyor",
						"Köklüyor",
						"Duraklatıldı",
						"Bitti",
						"Information",
						"Pieces:",
						"Hash:",
						"Secure:",
						"Comment:",
						"Created",
						"Creator:",
						"Date:",
						"Where",
						"Download Directory:",
						"Destination:",
						"Created time:",
						"File size:",
						"URL:",
						"Activity",
						"progress:",
						"size:",
						"status:",
						"availability:",
						"İndirildi:",
						"Yüklendi:",
						"Download Speed:",
						"Upload Speed:",
						"Error:",
						"Ratio:",
						"Peers:",
						"Upload to:",
						"Download from:",
						"Speed:",
						"start time:",
						"time left:",
						"Log",
						"Tier",
						" Need Username or Password",
						" Check the hostname and port settings",
						" Make sure SSL is turned off",
						" Check the username and password"
						
						]
					   ];