//Language = {};
Language.PT = {
	"common":{
		"all"									:"TUDO",
		"wan_lan_err"							:"Endereço IP em conflito com a WAN! Altere o endereço IP da LAN do router.",
		"channel"                 				:"Canal",
    	"after_map_a"             				:"(Introduza 10 caracteres hexadecimais (qualquer combinação de a-f, A-F, 0-9.))",
    	"after_map_b"             				:'(Introduza 5 caracteres ASCII (qualquer combinação de a-z, A-Z, 0-9.))',
    	"after_map_c"             				:"(Introduza 26 caracteres hexadecimais (qualquer combinação de a-f, A-F, 0-9.))",
    	"after_map_d"             				:'(Introduza 13 caracteres ASCII (qualquer combinação de a-z, A-Z, 0-9.))',
    	"after_map_e"             				:"(Introduza 64 caracteres hexadecimais (qualquer combinação de a-f, A-F, 0-9.))",
    	"after_map_f"             				:'(Introduza 8-63 caracteres ASCII (qualquer combinação de a-z, A-Z, 0-9.))',
    	"after_map_g"             				:'segundos(60-86400)',
		"auto_type"               				:"Auto",
		"welcome_title"           				:"Bem-vindo ao router sem fios netis",
		"advanced_title"          				:"Router sem fios netis",  
		"DDNS_ERR_FAILED"         				:"Falhou",///OK未翻译 to be translated
		"bound"                   				:"Vinculado",//OK adj.  形容词    使用语境 IP & MAC Binding  第790行
		"unbound"                 				:"Desvinculado",//OK adj.形容词
		"bind"                    				:"Vincular",//OKverb动词， 与16 17条目相关
		"timeout_err"							:"A operação falhou! Tente novamente.",
		"use_tip"								:"Hora",
		"restoring"								:"A restaurar definições...",//OK已有翻译的词句 Restore——Restaurar
		"defaulting"							:"A repor...",//OK已有翻译的词句 Are you sure you want to reset to factory defaults?——Tem a certeza de que quer repor as predefinições de fábrica?
		"rebooting"								:"A reiniciar...",//OK已有翻译的词句 System Restart——Reinício sistema
		"days"									:"Dias",//OK已有翻译的词句 Day——Dia
		"hours"									:"Horas",//OK已有翻译的词句 Hour——Hora
		"minutes"								:"Minutos",//OK已有翻译的词句 Mimute——Minutos
		"seconds"								:"Segundos",//OK已有翻译的词句 Second——Segundos
		"search"								:"A procurar...",//OK语境：search for the available wireless signal
		"wel_key_err"							:"(Use os caracteres entre 8 e 63 (à excepção dos caracteres【\'\"\\】).",
		"wel_sele_lan"							:"Selecionar idioma",
		"wel_tips"								:"Configuração rápida",
		"wel_inter_tip"							:"Tipo de ligação à Internet",
		"wel_wirel_tip"							:"Configuração sem fios",
		"wel_pwd_tip"							:"(Introduza entre 8 e 63 caracteres.) ",
		"wel_status_label"						:"Avançada :",

		"wel_static_tip"						:"Se o seu ISP tiver fornecido um endereço IP fixo, escolha a opção Endereço IP estático.",
		"wel_dhcp_tip"							:"Se o seu ISP tiver fornecido um endereço IP automático com servidor DHCP, escolha a opção DHCP.",
		"wel_pppoe_tip"							:"Se o seu ISP fornecer uma ligação PPPoE (ADSL), escolha a opção PPoE.",
		"bind_all"								:"Vincular tudo",
		"advance"								:"Avançadas",
		"text_after"							:"Pacote/s",
		"wps_off"								:"Desativar WPS",
		"wps_on"								:"Ativar WPS",
		"def_pin"								:"Restaurar PIN",
		"new_pin"								:"Criar novo PIN",
		"info"									:"Info",
		"connect"								:"Ligar",
		"disconnect"          					:"Interromper ligação",
		"connected"                             :"Conectado",
        "disconnected"                          :"Desconectados",
		"refresh"                     			:"Atualizar",
		"open"									:"Adicionar dispositivo",	
		"link"									:"Ligar",
		"save_reboot"							:"Guardar & Reiniciar",	
		"add"									:"Adicionar",
		"del"									:"Eliminar",
		"del_all"								:"Eliminar tudo",
		"delAll"								:"Eliminar tudo",
		"mod"									:"Modificar",
		"reboot"								:"Reiniciar",
		"back"									:"Voltar",
		"save"									:"Guardar",
		"keep_all"								:"Manter tudo",
		"wakeup"								:"Ativar",
		"upgrade"								:"Atualizar",
		"backup"								:"Cópia de segurança",
		"recover"                               :"Restaurar",
		"restore"								:"Restaurar",
		"help_more_btn"							:"Mais...",
		"ap_get"								:"Procurar PA",
		"auto_check"							:"Det auto",
		"help_more_null"						:"",
		"on"									:"Ativar",
		"off"									:"Desativar",
		"forbid_s"                              :"Recusar",
		"allow_s"                               :"Permitir",
		"df_mac"								:"MAC predefinido",
		"clone_mac"								:"Clone MAC",
        "start"                                 :"Iniciar",
        "end"								    :"Terminar",
        "browse"                                :"Procurar",
        "current"                               :"Clone endereço MAC",
        "device"                                :"Restaurar MAC predefinido", 
        "set_reserve"                           :"Reservar",
        "cancel_reserve"                        :"Cancelar",
        "reserved"                              :"Reservado",
        "static"                                :"Estático",
        "dynamic"                               :"DHCP",
		"yes"									:"Sim",
		"no"									:"Não",
        "other"                                 :"Outro",
		"total"									:"Total",
        "online"                                :"Online",
        "offline"                               :"Offline",
		"week_0"								:"Dom",
		"week_1"								:"Seg", 
		"week_2"								:"Ter",
		"week_3"								:"Qua",
		"week_4"								:"Quin",
		"week_5"								:"Sex",
		"week_6"								:"Sáb",
		"everday"								:"Todos os dias",
		"all_day"								:"Todo o dia",
//		"Sun"								    :"Dom",
//		"Mon"								    :"Seg", 
//		"Tue"								    :"Ter",
//		"Wed"								    :"Qua",
//		"Thu"								    :"Quin",
//		"Fri"								    :"Sex",
//		"Sat"								    :"Sáb",
//		"week"									:"Semana",
		"check_all_label"						:"Selecionar tudo",
		"max_size_label_a"						:" Atual ",
		"max_size_label_b"						:"&nbsp;página ",
		"size_label"							:"Itens mostrados em todas as páginas",
		"size_set_btn"							:"Aplicar",
		"load_tip"								:"A atualizar...",
		"lock_save"								:"A guardar...",
		"lock_delete"							:"A eliminar...",
		"lock_add"								:"A adicionar...",
		"unlock_save"							:"Guardado com êxito!",
		"unlock_delete"							:"Eliminado com êxito!",
		"unlock_add"							:"Adicionado com êxito!",
		"unlock_err"							:"Valor devolvido não identificado! Tente novamente.",
		"unlock_error"							:"A operação falhou!",
		"time_err"								:"Tempo de inatividade máx deve ser definido entre 1 e 30 min.",
		"dhcp_mtu_err"							:"Tamanho MTU deve ser entre 576 e 1500 bytes. Tente novamente.",
		"pppoe_mtu_err"							:"Tamanho MTU deve ser entre 576 e 1492 bytes. Tente novamente.",
		"static_mtu_err"						:"Tamanho MTU deve ser entre 576 e 1500 bytes. Tente novamente.",
		"l2tp_mtu_err"             				:"Tamanho MTU deve ser entre 576 e 1460 bytes. Tente novamente.",
		"pptp_mtu_err"             				:"Tamanho MTU deve ser entre 576 e 1420 bytes. Tente novamente.",
		"beacon_err"							:"O valor do Intervalo do sinal deve ser entre 20 e 1000.",
		"rts_err"								:"O valor do Limiar RTS deve ser entre 256 e 2347.",
		"frag_err"								:"O valor do Limiar de fragmentação deve ser entre 256 e 2346.",
		"cmp_port_err"							:"O valor da Porta final não pode ser inferior ao da Porta inicial. Tente novamente.",
		"cmp_ip_err"							:"O valor do Endereço final não pode ser inferior ao do Endereço inicial. Tente novamente.",
		"mask_err"								:"Máscara de sub-rede inválida. Tente novamente.",
		"ip_err"								:"Endereço IP inválido. Tente novamente.",
		"key_time_err"							:"O período para Renovação da chave é entre 60 e 86400 segundos. Tente novamente.",
		"addr_err"								:"O intervalo do endereço DHCP não deve ultrapassar o limite máximo. Tente novamente.",
		"lan_ip_err"							:"O intervalo do endereço DHCP deve ser definido para o mesmo segmento de rede do endereço IP da LAN. Tente novamente.",
		"lan_addr_err"							:"O endereço IP da LAN não deve estar incluído no endereço DHCP. Tente novamente.",
		"item_err"								:"Não é possível adicionar mais itens.",
		"ip_used_err"							:"O endereço IP foi usado para outro item. Tente com um endereço novo.",
		"qos_band_err"							:"A Largura de banda deve ser definida entre 0 e 12799. Tente novamente.",
		"qos_up_err"							:"A Largura de banda Uplink restringida não pode ser inferior à Largura de banda Uplink garantida. Tente novamente.",
		"qos_down_err"							:"A Largura de banda Downlink restringida não pode ser inferior à Largura de banda Downlink garantida. Tente novamente.",	
		"key_len_err"							:"O comprimento da senha/chave deve sere:",
		"ddns_start"							:"A ligar...",
		"ddns_failed"							:"A autenticação falhou. Verifique a info da sua conta e tente novamente.",
		"ddns_ok"								:"Ligação feita com êxito! O nome de domínio é:",
		"oray_user_err"							:"Introduza entre 5 e 16 caracteres, em qualquer combinação de a-z, A-Z, 0-9, -(hífen). Não é permitido o uso só de números ou de - (hífens).",
		"oray_pass_err"							:"Introduza entre 6 e 16 caracteres, em qualquer combinação de a-z, A-Z, 0-9, caracteres especiais.",
		"meibu_user_err"						:"Introduza entre 1 e 26 caracteres, em qualquer combinação de a-z, A-Z, 0-9. Não é permitido o uso de palavras chinesas ou de caracteres não autorizados.",
		"meibu_pass_err"						:"Introduza pelo menos 4 caracteres, em qualquer combinação de a-z, A-Z, 0-9.",
		"end_time_err"                          :"Formato de hora errado. Tente novamente.",
		"reserved_keep"                         :"Operação inválida! Este endereço já foi reservado.",
		"reserved_cancel"                       :"Operação inválida! Este endereço não foi reservado.",
		password_null							:"A senha não pode ter um valor nulo. Tente novamente.",
		password_ival							:"Apenas pode usar letras ou números para a senha. Tente novamente!",
		password_length_err						:"A senha deve ter menos de 32 caracteres. Tente novamente.",
		password_err							:"A nova senha introduzida não corresponde. Tente novamente.",
		mtu_err									:"Não são permitidas chaves nulas. Introduza novamente o número completo.",
		mtu_pppoe_null							:"Não são permitidas chaves nulas. Introduza novamente o número completo.",
		pppoe_text_err							:'Não são permitidas chaves nulas ou caracteres não autorizados como \\\'“”‘’. ',
		mtu_ival								:"Tamanho MTU deve ser entre 576 e [1] bytes. Tente novamente.",
		ip_addr_null							:"O endereço IP não ficar vazio ou ser definido como 0.0.0.0. Tente novamente.",
		ip_addr_ival							:"Endereço IP inválido com caracteres não autorizados. Tente novamente.",
		ip_addr_err								:"Endereço IP inválido. Tente novamente.",
		mask_addr_err							:"Máscara de sub-rede inválida. Tente novamente.",
		mac_addr_err							:"Endereço MAC inválido. Tente novamente.",
		gw_err									:"O Gateway  predefinido deve ser definido para o mesmo segmento de rede do endereço IP da WAN. Tente novamente.",
		gw_errs									:"Gateway predefinido inválido. Tente novamente.",
		port_null								:"Especifique endereço da porta.",
		port_err								:"A porta deve ser definida entre 1 e 65535. Tente novamente. ",
		int_number_err							:"Número inválido. Tente novamente.",
		string_null								:" Não são permitidos chaves nulas \n e caracteres não autorizados.",
		string_err								:'Não são permitidos os caracteres \'"\\ ou espaços.',
		string_null_err							:'Não são permitidos os caracteres \'"\\ .',
		route_ip_err							:"O endereço IP e a máscara de sub-rede não estão na mesma rede. Tente novamente.",
		auto_disconnect_time_err				:"Tempo de inatividade máx deve ser definido entre 1 e 30 min.",
		dhcp_reserve_err						:"O endereço IP deve estar incluído no endereço DHCP. Tente novamente.",
		dhcp_reserve_lan_ip						:"O endereço IP não pode ser o endereço IP da LAN do router. Tente novamente. ",
		wireless_key_length						:"O comprimento da senha/chave deve ser :[1].",
		wireless_key_hex_err					:"A senha deve ser composta apenas por caracteres hexadecimais.",
		qos_max_up_err							:"A Largura de banda Uplink restringida não pode ser inferior à Largura de banda Uplink garantida. Tente novamente.",
		qos_max_down_err						:"A Largura de banda Downlink restringida não pode ser inferior à Largura de banda Downlink garantida. Tente novamente.",
		qos_bandwidth_err						:"A Largura de banda deve ser definida entre 0 e 12799. Tente novamente.",
		az09_string_err							:"Use os seguintes caracteres :a-z,A-Z,0-9.",
		string_url_err							:"Use os seguintes caracteres :a-z,A-Z,0-9,-.",
		string_hex_err							:"Use os seguintes caracteres :a-f,A-F,0-9.",
//		wireless_key_length_info				:'(Use os caracteres [1] (à excepção dos caracteres【\'\"\\】))',
	  	wireless_key_length_info1				:"(Use os caracteres hexadecimais [1]  (a-f,A-F,0-9))",
	 	Src_password_err						:"A senha atual não está correta. Tente novamente.",
	  	save_only_need_reboot					:"A definição foi alterada e entrará em vigor após o reinício. Recomendamos-lhe que faça todas as alterações pretendidas antes de reiniciar o router.",
		pin_number_err							:"Introduza 8 números para o código PIN.",
		item_exist								:"Já existe um item com as mesmas definições. Tente novamente.",
		"rule_err"								:"Não são permitidos caracteres não autorizados e espaços.",
		"domain_err"							:"Formato do nome de domínio inválido. Tente novamente.",
		"dns_null_err"							:"Endereço de servidor DNS inválido. Defina pelo menos um servidor DNS.",
		"segment_err"							:"O endereço IP não pode ser o endereço de rede. Tente novamente.",
		"Bcast_err"								:"O endereço IP não pode ser um endereço de emissão. Tente novamente.",
		"segment_len_err"						:"O endereço IP não consta do atual segmento de rede. Tente novamente.",
		"reserver_err"							:"O endereço IP a ser reservado não consta do endereço DHCP. Tente novamente.",
		"pass_err"								:"A senha pode ser qualquer combinação entre a-z, A-Z, 0-9, ou incluir caracteres especiais. Tente novamente.",
		"year_err"								:"Formato do ano errado. Tente novamente (2008~2035).",
		"mon_err"								:"Formato do mês errado. Tente novamente (1~12).",
		"day31_err"								:"Formato do dia errado. Tente novamente (1~31).",
		"day30_err"								:"Formato do dia errado. Tente novamente (1~30).",
		"day29_err"								:"Formato do dia errado. Tente novamente (1~29).",
		"day28_err"								:"Formato do dia errado. Tente novamente (1~28).",
		"hour_err"								:"Formato da hora errado. Tente novamente (0~23).",
		"min_sec_err"							:"Formato dos minutos ou dos segundos errado. Tente novamente (0~59).",
		"page_err"								:"Formato da página errado. Tente novamente (1~100).",

		"DDNS_ERR_CLOSE"						:"Fechado.",
		"DDNS_ERR_CONNECTING"					:"A ligar...",
		"DDNS_ERR_INUPT"						:"Introduza o nome de utilizador e a senha.",
		"DDNS_ERR_GET_NO_IP"					:"Falha na obtenção do endereço do servidor.",
		"DDNS_ERR_SYSTEM"						:"Recursos de sistema limitados.",
		"DDNS_ERR_USER"							:"Nome de utilizador ou senha inválido.",
		"DDNS_ERR_OK"							:"Atualização feita com êxito!",
		"DDNS_ERR_SERVER"						:"Erro do servidor DDNS.",
		"ST"									:"Serviço padrão,  ",
		"PR"									:"Serviço profissional,",

		"del_tip"								:"Tem a certeza de que quer eliminar tudo?",
		"del_one_tip"							:"Tem a certeza de que quer eliminar o item selecionado?",
		"disconnect_tip"						:"Tem a certeza de que quer desligar a rede?",
		"connect_tip"							:"Tem a certeza de que quer ligar a rede?",
		"default_tip"							:"Tem a certeza de que quer repor as predefinições de fábrica?",
		"reboot_tip"							:"Tem a certeza de que quer reiniciar o router?",
		"reboot_web_tip"						:"O router irá reiniciar após mudar a porta. Quer continuar?",
		"backup_tip"							:"Tem a certeza de que quer restaurar as definições?",
		"del_reserve_err"						:"Falha ao cancelar a regra de reserva do endereço.",
		"ip_occupy_err"							:"Este endereço IP já existe. Tente novamente.",
		"mac_occupy_err"						:"Este endereço MAC já existe. Tente novamente.",
		"port_occupy_err"						:"Esta porta já existe. Tente novamente.",
		"port_len_err"							:"O intervalo das portas deve ser igual. e.g. intervalo para porta externa, 1-4; intervalo para porta interna, 6-9.",
		"update_err"							:"Não existe nenhum fich atualiz selecionado.",
		"update_faild"							:"A atualização do firmware falhou.",
		"backup_err"							:"Não existe nenhum fich cópia segurança selecionado.", 
		"backup_faild"							:"A criação da cópia de segurança falhou.",
		"ip_len_err"							:"Endereço IP não tem um intervalo válido. Tente novamente.",
		"add_item_err"							:"Já existe um item com as mesmas definições.",
		"_default"								:"Entrada inválida."
	},
	"status":{
		"txt"									:"Estado",
		"status":{
			"txt"								:"Info da interface",
			
			"status_l2tp_panel"					:"L2TP",
			"l2tp_ip_label"						:"Endereço IP",
			"l2tp_mask_label"					:"Máscara de sub-rede",
			"l2tp_gw_label"						:"Gateway predefinido",
			"status_pptp_panel"					:"PPTP",
			"pptp_ip_label"						:"Endereço IP",
			"pptp_mask_label"					:"Máscara de sub-rede",
			"pptp_gw_label"						:"Gateway predefinido",
			"second_ip_label"					:"Endereço IP secundária",
			"second_mask_label"					:"Máscara de sub-rede secundária",
			
			"status_wan_panel"					:"WAN",
			"conntype_label"					:"Tipo de ligação",
			"mac_addr_label"					:"Endereço MAC",
			"ip_label"							:"Endereço IP",
			"mask_label"						:"Máscara de sub-rede",
			"gw_label"							:"Gateway predefinido",
			"dns_a_label"						:"DNS principal",
			"dns_b_label"						:"DNS secundário",
			"con_time_label"					:"Hora da ligação",
			"connected_label"					:"Estado da ligação",
			"status_lan_panel"					:"LAN",
			"lan_mac_label"						:"Endereço MAC",
			"lan_ip_label"						:"Endereço IP",
			"lan_mask_label"					:"Máscara de sub-rede",
			"dhcp_enable_label"					:"Servidor DHCP",
			"status_wireless_panel"				:"Sem fios",
			"wl_enable_label"					:"Estado sem fios",
			"ssid_label"						:"SSID",
			"net_mode_label"					:"Modo de rádio",
			"sec_mode_label"					:"Tipo de autenticação",
			"channel_label"						:"Canal",
			"wl_mac_label"						:"Endereço MAC",
			"wps_enable_label"					:"Estado WPS"
		}
	},
	"network":{
		"txt"									:"Rede",
		"wan":{
			"txt"								:"WAN",
			"mode_panel"						:"Tipo da WAN",
			"access_mode_label"					:"Tipo da WAN",
			"wire_r"							:"Com fios",
			"wireless_r"						:"Sem fios",

			"wireless_config_panel"				:"Definições WISP",
			"repeater_ssid_label"				:"SSID",
			"channel_label"						:"Canal",
			"channel_options"					:"['Auto','Canal 1 ','Canal 2 ','Canal 3 ','Canal 4 ','Canal 5 ','Canal 6 ','Canal 7 ','Canal 8 ','Canal 9 ','Canal 10','Canal 11']",
			"rp_sec_mode_label"					:"Tipo de autenticação",
			"rp_sec_mode_options"				:"['Nenhuma','WEP','WPA-PSK','WPA2-PSK']",

			"wep_panel"							:"WEP",
			"rp_key_size_label"					:"Comp da chave",
			"rp_key_type_label"					:"Tipo de encriptação",
			"rp_key_mode_wep_label"				:"Modo de chave",
			"rp_key_mode_wpa_label"				:"Modo de chave",
			"rp_key_wep_label"					:"Senha",
			"rp_key_wpa_label"					:"Senha",
			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP e AES",

			"wan_set_panel"						:"Definições WAN",
			"conntype_label"					:"Tipo de ligação à WAN",
			"conntype_options"					:"['DHCP (cable modem)','IP estático','PPPoE','Russia PPPoE','Unifi PPPoE','Maxis PPPoE','PPTP/Russia PPTP','L2TP/Russia L2TP']",
			"conntype_after"					:"LAN 1 apenas para IPTV",

			"pppoe_username_label"				:"Nome de utilizador",
			"pppoe_pwd_label"					:"Senha",
			"l2tp_username_label"				:"Nome de utilizador",
			"l2tp_pwd_label"					:"Senha",
			"l2tp_server_label"					:"IP do servidor/ Nome",
			"l2tp_type_label"					:"Tipo de ligação",
			"l2tp_ip_label"						:"Endereço IP",
			"l2tp_mask_label"					:"Máscara de sub-rede",
			"l2tp_gw_label"						:"Gateway predefinido",

			"pptp_username_label"				:"Nome de utilizador",
			"pptp_pwd_label"					:"Senha",
			"pptp_server_label"					:"IP do servidor/ Nome",
			"pptp_type_label"					:"Tipo de ligação",
			"pptp_ip_label"						:"Endereço IP",
			"pptp_mask_label"					:"Máscara de sub-rede",
			"pptp_gw_label"						:"Gateway predefinido",

			"pppoe_service_name_label"			:"Nome do servidor",
			"pppoe_service_name_after"			:"(Opcional)",
			"pppoe_ac_name_label"				:"Nome do AC PPPoE",
			"pppoe_ac_name_after"				:"(Opcional)",
			"pppoe_mtu_label"					:"Tamanho da MTU",
			"pppoe_mtu_after"					:"(O valor predefinido é 1480, alterar apenas se necessário.)",
			"dns_a_label"						:"DNS principal",
			"dns_a_after"						:"(Opcional)",	
			"dns_b_label"						:"DNS secundário",
			"dns_b_after"						:"(Opcional)",
			"auto_r"							:"Ligar automaticamente",
			"time_r"							:"Ligar a pedido,      Tempo de inatividade máx # minutos (0 significa sempre activo.)",
			"hand_r"							:"Ligar manualmente",
			"dhcp_mtu_label"					:"Tamanho da MTU",
			"dhcp_mtu_after"					:"(O valor predefinido é 1500, alterar apenas se necessário.)",
			"wan_ip_label"						:"Endereço IP da WAN",
			"wan_mask_label"					:"Máscara de sub-rede",
			"wan_gw_label"						:"Gateway predefinido",
			"mac_addr_label"					:"Endereço MAC",
			"static_mtu_label"					:"Tamanho da MTU",
			"static_mtu_after"					:"(O valor predefinido é 1500, alterar apenas se necessário.)",
			"l2tp_mtu_label"					:"Tamanho da MTU",
			"l2tp_mtu_after"					:"(O valor predefinido é 1460, alterar apenas se necessário.)",
			"pptp_mtu_label"					:"Tamanho da MTU",
			"pptp_mtu_after"					:"(O valor predefinido é 1420, alterar apenas se necessário.)",

			"second_in_panel"					:"Ligação secundária",
			"second_in_type_label"				:"Tipo de ligação",
			"dy_r"								:"Dinâmico",
			"st_r"								:"Estático",

			"ap_get_thead"						:"['ID','Nome da rede','BSSID','Canal (banda de rádio)','Modo de rádio','Tipo de autenticação','Potência do sinal','Ligar']"
		},
		"lan":{
			"txt"								:"LAN",
			"lan_set_panel"						:"LAN",
			"lan_ip_label"						:"Endereço IP",
			"lan_mask_label"					:"Máscara de sub-rede",
			"servie_panel"						:"Servidor DHCP",
			"dhcp_enable_label"					:"Estado DHCP",
			"dhcp_start_ip_label"				:"Endereço IP inicial",
			"dhcp_end_ip_label"					:"Endereço IP final",

			"dhcp_list_panel"					:"Lista de clientes DHCP",
			"dhcp_client_list_thead"			:"['ID','Endereço IP','Endereço MAC','Nome do anfitrião','Reservado','Estado','Operação']",
			"load_panel"						:"Reiniciar o router"
		},
		"iptv":{
			"txt"								:"IPTV",
			"iptv_set_panel"					:"Modo IPTV",
			"iptv_mode_label"					:"Modo IPTV",
			"iptv_mode_options"					:"['Automático','Ponte','VLAN Tag 802.1Q']",
			"iptv_port_label"					:"Porta IPTV",
			"iptv_port_options"					:"['LAN1','LAN1 & LAN2']",
			"vlan_set_panel"					:"Definições VLAN",
			"vlan_tag_enable_label"				:"VLAN Tag do Internet",
			"vlan_id_inter_label"				:"ID VLAN do Internet",
			"vlan_pri_inter_label"				:"Prioridade do VLAN",
			"vlan_pri_inter_options"			:"[0,1,2,3,4,5,6,7]",
			
			"vlan_id_iptv_label"				:"ID VLAN do IPTV",
			"vlan_pri_iptv_label"				:"Prioridade do VLAN",
			"vlan_pri_iptv_options"				:"[0,1,2,3,4,5,6,7]",

			"mvlan_id_iptv_label"				:"ID Multi-VLAN do IPTV",
			"mvlan_pri_iptv_label"				:"Prioridade do VLAN",
			"mvlan_pri_iptv_options"			:"[0,1,2,3,4,5,6,7]",

			"vlan_id_phone_label"				:"ID VLAN do Telefone IP",
			"vlan_pri_phone_label"				:"Prioridade do VLAN",
			"vlan_pri_phone_options"			:"[0,1,2,3,4,5,6,7]",

			"port_set_panel"					:"Definições Porta",
			"iptv_lan1_mode_label"				:"Modo Porta LAN1",
			"iptv_lan1_mode_options"			:"['Internet','IPTV','Telefone IP']",
			"iptv_lan2_mode_label"				:"Modo Porta LAN2",
			"iptv_lan2_mode_options"			:"['Internet','IPTV','Telefone IP']",
			"iptv_lan3_mode_label"				:"Modo Porta LAN3",
			"iptv_lan3_mode_options"			:"['Internet','IPTV','Telefone IP']",
			"iptv_lan4_mode_label"				:"Modo Porta LAN4",
			"iptv_lan4_mode_options"			:"['Internet','IPTV','Telefone IP']"
		},
		"address_reservation":{
			"txt"								:"Reserva de endereço",
			"reservation_panel"					:"Reserva de endereço",
			"reserve_des_label"					:"Descrição",
			"reserve_ip_label"					:"Endereço IP",
			"reserve_mac_label"					:"Endereço MAC",

			"reservation_list_panel"			:"Lista de reserva de endereço",
			"reservation_list_thead"			:"['ID','Descrição','Endereço IP','Endereço MAC','Modificar']"
		},
		"opmode":{
			"txt"                               :"Modo de Operação",
			"opmode_panel"                      :"Modo de Operação",
			"access_mode_label"                 :"Modo",
			"router_r"                          :"Router",
			"bridge_r"                          :"Ponte"
		}
	},
	"wireless":{
		"txt"									:"Sem fios",
		"base":{
			"txt"								:"Definições sem fios",
			"base_panel"						:"Definições sem fios",	
			"wl_enable_label"					:"Estado sem fios",
			"ssid_label"						:"SSID",
			"wl_stand_label"					:"Banda de rádio",
			"wl_stand_options"					:"['802.11b','802.11g','802.11n','802.11b+g','802.11g+n','802.11b+g+n']",
			"net_mode_label"					:"Modo de rádio",
			"net_mode_options"					:"['Ponto de acesso','Repetidor','AP+WDS','WDS','Cliente']",
		//	"wl_config_label"					:"Configuração",
			"cl_config_label"					:"Configuração",
			"rp_config_label"					:"Configuração",
			"auto_r"							:"Automático",
			"hand_r"							:"Manual",
			"repeater_ssid_label"				:"Nome AP remoto", 
			"repeater_mac_label"				:"Endereço MAC AP remoto ",
			"wl_mac_label"						:"Endereço MAC",
			"ssid_broad_label"					:"Transmitir SSID",
			"channel_width_label"				:"Largura do canal",
			"20_r"								:"20 MHz",
			"40_r"								:"40 MHz",
			"channel_bind_label"				:"Controle Sideband",
			"down_r"							:"Inferior",
			"up_r"								:"Superior",
		//"repeater_ssid_label"				:"Repetidor SSID",
			"region_label"						:"Região",
			"region_options"					:"['US','EU','MKK','IC']",
			"channel_label"						:"Canal",
			"channel_options"					:"['Auto','Canal 1 ','Canal 2 ','Canal 3 ','Canal 4 ','Canal 5 ','Canal 6 ','Canal 7 ','Canal 8 ','Canal 9 ','Canal 10','Canal 11']",

			"ap_security_panel"					:"Defin seg ponto acesso",
			"tips_info"							:"Para uma maior segurança da sua rede sem fios, recomendamos que escolha WPA2-PSK como Tipo de autenticação, e AES ou TKIP e AES como Tipo de encriptação.",
			"sec_mode_label"					:"Tipo de autenticação",
			"sec_mode_options"					:"['Nenhuma','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Quando a opção WPS está ativada, não deve escolher WEP como Tipo de autenticação.",
			"key_size_label"					:"Comp da chave",
			"key_type_label"					:"Tipo de encriptação",
			"key_mode_wep_label"				:"Modo de chave",
			"key_mode_wpa_label"				:"Modo de chave",
			"key_wep_label"						:"Senha",
			"key_wpa_label"						:"Senha",
			"key_time_label"					:"Renovação da chave",

			"wds_security_panel"				:"Defin seg WDS",
			"wds_sec_mode_label"				:"Tipo de autenticação",
			"wds_sec_mode_options"				:"['Nenhuma','WEP 64 bits','WEP 128 bits','WPA (TKIP)','WPA2 (AES)']",
			"wds_key_mode_wep_label"			:"Modo de chave",
			"wds_key_mode_wpa_label"			:"Modo de chave",
			"wds_key_wep_label"					:"Senha",				
			"wds_key_wpa_label"					:"Senha",				

			"client_security_panel"				:"Defin seg do cliente",
			"cl_sec_mode_label"					:"Tipo de autenticação",
			"cl_sec_mode_options"				:"['Nenhuma','WEP','WPA-PSK','WPA2-PSK']",
			"cl_key_size_label"					:"Comp da chave",
			"cl_key_type_label"					:"Tipo de encriptação",
			"cl_key_mode_wep_label"				:"Modo de chave",
			"cl_key_mode_wpa_label"				:"Modo de chave",
			"cl_key_wep_label"					:"Senha",
			"cl_key_wpa_label"					:"Senha",
			"cl_key_auto_label"					:"Senha",
			"cl_key_time_label"					:"Renovação da chave",

			"repeater_security_panel"			:"Defin seg repetidor",
			"rp_sec_mode_label"					:"Tipo de autenticação",
			"rp_sec_mode_options"				:"['Nenhuma','WEP','WPA-PSK','WPA2-PSK']",
			"rp_key_size_label"					:"Comp da chave",
			"rp_key_type_label"					:"Tipo de encriptação",
			"rp_key_mode_wep_label"				:"Modo de chave",
			"rp_key_mode_wpa_label"				:"Modo de chave",
			"rp_key_wep_label"					:"Senha",
			"rp_key_wpa_label"					:"Senha",
			"rp_key_auto_label"					:"Senha",
			"rp_key_time_label"					:"Renovação da chave",

			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP e AES",
			"ap_get_thead"						:"['ID','Nome da rede','BSSID','Canal (banda de rádio)','Modo de rádio','Tipo de autenticação','Potência do sinal','Ligar']"
		},
		"wl_mac_filter":{
			"txt"								:"Filtragem MAC",
			"filter_set_panel"					:"Filtragem MAC sem fios",
			"wl_mac_filter_enable_label"		:"Estado",
			"wl_mac_filter_rule_label"			:"Regra de filtragem",
			"deny_r"							:"Negar Acesso à rede aos Dispositivos listados, outros serão permitidos.",//OK EN原句 Deny the listed devices to access the network, others are permitted. 如490句子结构变化大，需参考490行进行变更。
			"allow_r"							:"Permitir acesso à rede aos dispositivos listados, outros serão Bloqueados.", //OK 修改，最长字符为 Permitir acesso à rede pelos dispositivos listados, os outros não têm     EN原句 Permit the listed devices to access the network, others are denied.
			"contr_des_panel"					:"Gestão da lista de filtragem MAC sem fios",
			"mac_des_label"						:"Descrição",
			"macaddr_label"						:"Endereço MAC",
			"mac_tab_panel"						:"Lista de filtragem MAC sem fios",
			"wl_mac_filter_list_thead"			:"['ID','Descrição','Endereço MAC','Modificar']"
		},
		"wds":{
			"txt"								:"Definições WDS",
			"wds_set_panel"						:"Definições WDS",
			"wds_name_label"					:"WDS SSID",
			"wds_mac_label"						:"Endereço MAC WDS",
			"wds_tab_panel"						:"Lista de clientes WDS",
			"wl_wds_list_thead"					:"['ID','WDS SSID','Endereço MAC WDS','Modificar']",
			"ap_get_thead"						:"['ID','Nome da rede','BSSID','Canal (banda de rádio)','Modo de rádio','Tipo de autenticação','Potência do sinal','Ligar']"
		},
		"advance":{
			"txt"								:"Sem fios avançada",
			"advance_set_panel"					:"Definições sem fios avançadas",
			"wlan_partition_label"				:"Isolamento do PA",
			"iapp_label"						:"Roaming sem fios",
			"shortGi_label"						:"GI curto",
			"protection_label"					:"Proteção",
			"out_power_label"					:"Potência de transmissão",
			"a_r"								:"100%",
			"b_r"								:"70%",
			"c_r"								:"50%",
			"d_r"								:"35%",
			"e_r"								:"15%",
			"wmm_label"							:"WMM"
		},
		"multiple_ssid":{
			"txt"								:"Múltiplos SSID",
			"ap1_multiple_status_panel"  		:"Múltiplos SSID",
			"multiple_status_label"    			:"Estado",
			"multiple_sele_label"      			:"Selecionar AP",//OK翻译 to be translated
			"multiple_sele_options"    			:"['AP1','AP2','AP3']",
			"para_set_panel"					:"Definições dos múltiplos SSID",
			"ap1_wl_enable_label"				:"Estado",
			"ap1_wl_mac_label"					:"Endereço MAC",
			"ap1_ssid_label"					:"SSID",
			"ap1_ssid_broad_label"				:"Transmitir SSID",
			"ap1_sec_contr_label"				:"Controlo do acesso",
			"ap1_sec_contr_options"				:"['LAN+WAN','WAN']",
			"ap1_encryption_label"				:"Tipo de encriptação",
			"ap1_encryption_options"			:"['Nenhuma','TKIP','AES']",
			"ap1_password_label"				:"Senha",

			"safe_set_panel"					:"Definições de segurança múltiplos SSID",
			"ap1_sec_mode_label"				:"Tipo de autenticação",
			"ap1_sec_mode_options"				:"['Nenhuma','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Quando a opção WPS está ativada, não deve escolher WEP como Tipo de autenticação.",
			"ap1_key_size_label"				:"Comp da chave",
			"ap1_key_type_label"				:"Comp da chave",
			"ap1_key_mode_wep_label"			:"Modo de chave",
			"ap1_key_mode_wpa_label"			:"Modo de chave",
			"ap1_key_wep_label"					:"Senha",
			"ap1_key_wpa_label"					:"Senha",
			"ap1_key_time_label"				:"Renovação da chave",
			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP e AES",
			"ap_link_tab_panel"					:"Lista múltiplos SSID",
			"wl_link_ap1_list_thead"			:"['ID','SSID','Endereço MAC','Transmitir SSID','Controlo do acesso','Tipo de autenticação','Modificar']"
		},
		"wps":{
			"txt"								:"Definições WPS",
			"wps_security_panel"				:"Definições WPS",
			"wps_enable_label"					:"Estado WPS",
			"wps_pin_label"						:"Código PIN",
			"hand_add_label"					:"Adicionar novo dispositivo",

			"hand_add_p_panel"					:"Adicionar novo dispositivo",
			"hand_r"							:"Introduza o PIN do novo dispositivo: ",
			"press_r"							:"Prima o botão do novo dispositivo dentro de dois minutos"
		},
		"list":{
			"txt"								:"Lista de clientes", 
			"list_panel"						:"Lista de clientes sem fios",
			"wl_link_ap0_list_thead"			:"['ID','SSID','Nome do anfitrião','Endereço MAC','Pacotes enviados','Pacotes recebidos']"
		}
	},
	"management":{
		"txt"									:" Controlo do acesso",
	    "attack_defense":{
			"txt"								:"Segurança avançada",
			"attack_defense_panel"				:"Segurança avançada",
			"ping_wan_label"					:"Ignorar pacotes PING da porta WAN",
			"ping_lan_label"					:"Ignorar Gateway PING",
			"port_packet_label"				    :"Ignorar pacotes de análise de portas",
			"icmp_flood_label"				    :"Prevenção de ataque do ICMP-Flood",
			"icmp_flood_after"					:"Limiar de pacotes (5-3000)",
			"tcp_flood_label"				    :"Prevenção de ataque do TCP-SYN-Flood",
			"tcp_flood_after"					:"Limiar de pacotes (5-3000)",
			"udp_flood_label"				    :"Prevenção de ataque do UDP-Flood",
			"udp_flood_after"					:"Limiar de pacotes (5-3000)",
			"virus_filter_label"		        :"Filtragem de vírus",
			"arp_attack_label"				    :"Prevenção de ataque do ARP",
			"attack_log_tab_panel"              :"Registo ataques do ARP",
			"attack_log_list_thead"             :"['ID','Hora','Registo']"
		},
		"ip_filter":{
			"txt"								:"Filtragem IP",
			"ip_filter_panel"					:"Filtragem IP",
			"ip_filter_enable_label"			:"Estado",
			"ip_filter_rule_label"				:"Regra de filtragem",
			"deny_r"							:"Negar acesso à rede aos dispositivos (IP) não listados em baixo.",
			"permit_r"							:"Permitir acesso à rede pelos dispositivos (IP) não listados em baixo.",
			"ip_filter_list_panel"				:"Definições da Regra de Filtragem de IP",
			"ip_describe_label"					:"Descrição",
			"ip_status_label"					:"Estado",
			"ip_status_options"					:"['Ativar','Desativar']",
			"ip_rule_label"						:"Regra",
			"ip_rule_options"					:"['Permitir','Negar']",
			"ip_src_sele_label"					:"Anfitrião de origem",
			"ip_src_sele_options"      			:"['Todos anfitriões','Anfitriões específicos','Sub-rede do\\ anfitrião','Segmento do\\ anfitrião']",
			"ip_src_ip_label"                 	:"Endereço IP",
			"ip_src_mask_label"            		:"Máscara de sub-rede",
			"ip_src_start_label"				:"Endereço IP inicial",
			"ip_src_end_label"					:"Endereço IP final",
			"ip_des_sele_label"                 :"Anfitrião de destino",
			"ip_des_sele_options"               :"['Todos anfitriões','Anfitriões específicos','Sub-rede do\\ anfitrião','Segmento do\\ anfitrião']",
			"ip_des_ip_label"                   :"Endereço IP",
			"ip_des_mask_label"                 :"Máscara de sub-rede",
			"ip_des_start_label"				:"Endereço IP inicial",
			"ip_des_end_label"               	:"Endereço IP final",
			"ip_proto_label"					:"Protocolo",
			"ip_port_label"						:"Porta",
			"ip_proto_options"					:"['TUDO','TCP','UDP','ICMP']",
			"ip_day_label"						:"Dia",
			"ip_day_btn"						:"TUDO",
			"ip_time_label"						:"Hora",
			"ip_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"ip_filter_tab_panel"				:"Lista de filtragem IP",
			"ip_filter_list_thead"				:"['ID','Descrição','Regra','IP de origem','IP de destino','Protocolo','Porta','Dia','Hora','Modificar']"
		},
		"mac_filter":{
			"txt"								:"Filtragem MAC",
			"mac_filter_panel"					:"Filtragem endereço MAC",
			"mac_filter_enable_label"			:"Estado",
			"mac_filter_rule_label"				:"Regra de filtragem",
			"deny_r"							:"Negar acesso à rede aos dispositivos (MAC) não listados em baixo.",
			"permit_r"							:"Permitir acesso à rede pelos dispositivos (MAC) não listados em baixo.",
			"mac_filter_list_panel"				:"Definições da Regra de Filtragem de MAC",
			"mac_describe_label"				:"Descrição",
			"mac_status_label"					:"Estado",
			"mac_status_options"				:"['Ativar','Desativar']",
			"mac_rule_label"					:"Regra",
			"mac_rule_options"					:"['Permitir','Negar']",
			"mac_filter_label"					:"Endereço MAC de origem",
			"mac_day_label"						:"Dia",
			"mac_time_label"					:"Hora",
			"mac_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"mac_filter_tab_panel"				:"Lista filtragem MAC",
			"mac_filter_list_thead"					:"['ID','Descrição','Regra','Endereço MAC','Dia','Hora','Modificar']"
		},
		"dns_filter":{
			"txt"								:"Filtragem de domínio",
			"domain_filter_panel"				:"Filtragem de domínio",
			"dns_filter_enable_label"			:"Estado",
			"dns_filter_rule_label"				:"Regra de filtragem",
			"deny_r"							:"Negar acesso com as palavras-chave DNS não listadas em baixo.",	
			"permit_r"							:"Permitir acesso com as palavras-chave DNS não listadas em baixo.",
			"domain_filter_list_panel"			:"Definições da Regra de Filtragem  de domínio",
			"dns_des_label"						:"Descrição",
			"dns_status_label"					:"Estado",
			"dns_status_options"				:"['Ativar','Desativar']",
			"dns_rule_label"					:"Regra",
			"dns_rule_options"					:"['Permitir','Negar']",
			"dns_key_label"						:"Palavras-chave DNS",
			"dns_day_label"						:"Dia",
			"dns_time_label"					:"Hora",
			"dns_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"domain_filter_tab_panel"			:"Lista filtragem domínio",
			"dns_filter_list_thead"				:"['ID','Descrição','Regra','Palavras-chave DNS','Dia','Hora','Modificar']"		
		}
	},
	"qos":{
		"txt"									:"Controle de Banda", 
		"qos":{
			"config_panel"						:"Configuração da largura de banda",
			"qos_enable_label"					:"Estado",
			"qos_rule_label"					:"Regra",
			"qos_rule_label_a"					:"Uplink",
			"qos_rule_label_b"					:"Downlink",
			"qos_rule_label_c"					:"(KB/s) (0 significa sem limites.)",
			"qos_rule_label_d"					:"(KB/s) (0 significa sem limites.)",

			"qos_set_panel"						:"Regras do controle da largura de banda",
			"qos_des_label"						:"Descrição",
			"qos_status_label"					:"Estado",
			"qos_status_options"				:"['Ativar','Desativar']",
			"qos_sele_label"					:"Anfitrião",
			"qos_sele_options"					:"['Todos anfitriões','Anfitriões específicos','Sub-rede do\\ anfitrião','Segmento do\\ anfitrião']",
			"qos_ip_label"						:"Endereço IP",
			"qos_mask_label"					:"Máscara de sub-rede",
			"qos_ip_start_label"				:"Endereço IP inicial",
			"qos_ip_end_label"					:"Endereço IP final",
			"qos_min_label"						:"Garantida",  
			"qos_min_label_a"					:"Uplink",
			"qos_min_label_b"					:"Downlink",
			"qos_min_label_c"					:"(KB/s) (0 significa sem limites.)",
			"qos_min_label_d"					:"(KB/s) (0 significa sem limites.)",
			"qos_max_label"						:"Restringida",
			"qos_max_label_a"					:"Uplink",
			"qos_max_label_b"					:"Downlink",
			"qos_max_label_c"					:"(KB/s) (0 significa sem limites.)",
			"qos_max_label_d"					:"(KB/s) (0 significa sem limites.)",

			"qos_list_panel"					:"Lista de controle da largura de banda",
			"qos_rule_list_thead"				:"['ID','Descrição','Estado','Intervalo endereço IP',{head:'Largura de banda garantida',con:['Uplink','Downlink']},{head:'Largura de banda restringida',con:['Uplink','Downlink']},'Modificar']"
		}
	},
	"ddns":{
		"txt"									:"DNS dinâmico",
		"ddns":{
			"txt"								:"DNS dinâmico",
			"ddns_panel"						:"DNS dinâmico",
			"ddns_enable_label"					:"Estado DDNS",
			"ddns_sp_label"						:"Fornecedor serviço",
			"ddns_sp_options"					:"['No-IP','Dyndns']",
			"ddns_sp_after"						:"<a href='http://www.meibu.com/reg.asp'>www.noip.com</a>",
			"ddns_username_label"				:"Nome de utilizador",
			"ddns_password_label"				:"Senha",
			"ddns_domain_label"					:"Nome de domínio",
			"ddns_port_label"					:"Porta",
			"ddns_info_label"					:"Estado da ligação",
			"ddns_tips_info"					:"Sugestões: Após iniciar com êxito sessão no DDNS, termine a sessão antes de mudar para outra conta."
		}
	},
	"forward":{
		"txt"									:"Encaminhamento",
		"virtual":{
			"txt"								:"Servidores virtuais",
			"vir_server_panel"					:"Defin regra servidores virtuais",
			"vir_name_label"					:"Descrição",
			"vir_ip_label"						:"Endereço IP",
			"vir_proto_label"					:"Protocolo",
			"vir_proto_options"					:"['TUDO','TCP','UDP','HTTP','HTTPS','FTP','POP3','SMTP','DNS','TELENT','IPSEC','PPTP','Cliente terminal Windows','GuruGuru','H323 VoIP Phone','Soribada']",
			"vir_outport_label"					:"Porta externa",
			"vir_inport_label"					:"Porta interna",
			"vir_tab_panel"						:"Lista servidores virtuais",
			"virtual_server_list_thead"			:"['ID','Descrição','Endereço IP','Protocolo','Porta externa','Porta interna','Modificar']"
		}
	},
	"advanced":{
		"txt"									:"Avançadas",
		"vpn":{
			"txt"								:"VPN",
			"vpn_panel"							:"Definições VPN Pass-through",
			"pptp_enable_label"					:"PPTP Pass-through",
			"l2tp_enable_label"					:"L2TP Pass-through",
			"ipsec_enable_label"				:"IPSEC Pass-through"
		},
		"igmp":{
			"txt"								:"IGMP",
			"igmp_panel"						:"IGMP",
			"igmp_enable_label"					:"Estado"
		},
		"dmz":{
			"txt"								:"DMZ",
			"dmz_panel"							:"DMZ",
			"dmz_enable_label"					:"Estado",
			"dmz_ip_label"						:"Endereço IP",

			"super_dmz_panel"					:"Super DMZ",
			"super_dmz_enable_label"			:"Estado",
			"super_dmz_addr_label"				:"Endereço MAC"		
		},
		"portTrigger":{
			"txt"								:"Ativação de portas",
			"port_trigger_panel"				:"Defin regra ativação de portas",
			"port_select_label"					:"Regra predefinida",
			"port_select_options"				:"['--Selecionar um--','GuruGuru','BuddyBuddy','Enppy','Pruna TCP','Pruna UDP']",
			"app_name_label"					:"Descrição",
			"trigger_proto_label"				:"Ativar protocolo",
			"trigger_proto_options"				:"['TCP','UDP']",
			"app_port_label"					:"Ativar porta",
			"forward_proto_label"				:"Protocolo de forwarding",
			"forward_proto_options"				:"['TCP','UDP']",
			"forward_port_label"				:"Porta encaminhamento",
		
			"trigger_tab_panel"					:"Lista ativação portas",
			"app_port_list_thead"				:"['ID','Descrição','Ativar protocolo','Ativar porta','Protocolo de forwarding','Porta encaminhamento','Modificar']"
		},
		"ftp":{
			"txt"								:"Porta privada FTP",
			"ftp_port_panel"					:"Porta privada FTP",
			"ftp_enable_label"					:"Estado",
			"ftp_port_label"					:"Porta"
		},
		"upnp":{
			"txt"								:"UPnP",
			"upnp_panel"						:"Defin UPnP",
			"upnp_enable_label"					:"Estado"
		},
		"binds":{
			"txt"								:"Vinculação IP e MAC",
			"binds_set_panel"					:"Vinculação IP e MAC",
			"binds_rule_label"					:"Regra de filtragem",
			"deny_r"							:"Permitir acesso à Internet pelos dispositivos não listados.",
			"allow_r"							:"Negar acesso à Internet aos dispositivos não listados.",

			"contr_binds_panel"					:"Defin regra vinculação IP e MAC",
			"binds_des_label"					:"Descrição",
			"binds_ip_label"					:"Endereço IP",
			"binds_mac_label"					:"Endereço MAC",
			"binds_port_label"					:"Interface",
			"binds_port_options"				:"['LAN','WAN']",
			"binds_tab_panel"					:"Lista vinculação IP e MAC",
			"binds_list_thead"					:"['ID','Descrição','Endereço IP','Endereço MAC','Interface','Modificar']"
		},
		"arp_list":{
			"txt"								:"Lista ARP",
			"arp_list_panel"					:"Lista ARP",
			"arp_list_thead"					:"['ID','Endereço IP','Endereço MAC']"
		},
		"routing":{
			"txt"								:"Encaminh estático",
			"routing_panel"						:"Definições da Regra de encaminhamento estático",
			"route_des_label"					:"Descrição",
			"route_type_label"					:"Tipo",
			"route_type_options"				:"['REDE','ANFITRIÃO']",
			"ip_value_label"					:"Endereço IP de destino",
			"mask_value_label"					:"Máscara de sub-rede",
			"gateway_value_label"				:"Gateway predefinido",
			"route_tab_panel"					:"Lista encaminh estático",
			"static_routing_list_thead"			:"['ID','Descrição','Tipo','Endereço IP','Máscara sub-rede','Gateway predefinido','Modificar']"
		},
		"interface_mode":{
			"txt"								:"Definições da porta",
			"mode_panel"						:"Definições da porta WAN",
			"wan_label"							:"Porta WAN",
			"wan_options"						:"['Auto','10M Duplex','10M Semi-Duplex','100M Duplex','100M Semi-Duplex']"
		},
		"wakeup":{
			"txt"								:"WOL",
			"wakeup_panel"						:"WOL",
			"wakeup_mac_label"					:"Endereço MAC"
		}
	},
	"misc":{
		"txt"									:"Ferramentas sistema",
		"update":{
			"txt"								:"Atualização firmware",
			"update_panel"						:"Atualização firmware",
			"version_label"						:"Versão atual",
			"file_label"						:"Ficheiro atualização",
			"updata_file_label"                 :"Ficheiro atualização",
			"load_panel"						:"Atualização firmware",
			"tip_update_info"					:"Sugestões: Não desligue o router durante a atualização do firmware."
		},
		"sys_time":{
			"txt"								:"Definições hora",
			"time_set_panel"					:"Definição da hora",
			"time_now_label"					:"Hora atual",
			"time_type_label"					:"Tipo",
			"ntp_r"								:"NTP",
			"hand_r"							:"Manual",
			"time_date_label"					:"Data",
			"time_date_after"					:"Ano",
			"time_date_after2"					:"Mês",
			"time_date_after3"					:"Dia",
			"time_time_label"					:"Hora",
			"time_time_after"					:"Hora",
			"time_time_after2"					:"Minutos",
			"time_time_after3"					:"Segundos",
			"timezone_label"					:"GMT",
			"timezone_options"					:"['(GMT-12:00) Eniwetok, Kwajalein','(GMT-11:00) Midway Is., Samoa','(GMT-10:00) Hawaii','(GMT-09:00) Alasca','(GMT-08:00) Hora do pacífico (EU-Canadá); Los Angeles','(GMT-07:00) Hora das regiões montanhosas (EU- Canadá); Arizona','(GMT-06:00) Hora central (EU-Canadá); Cidade do México','(GMT-05:00) Hora do Leste (EU-Canadá); Bogotá, Nova Iorque, Lima','(GMT-04:00) Hora do Atlântico (Canadá); Caracas, La Pax','(GMT-03:00) Brasília, Buenos Aires, Georgetown, Gronelândia','(GMT-02:00) Atlântico central','(GMT-01:00) Ilha de Cabo Verde., Açores','(GMT) Meridiano de Greenwich; Dublin, Edimburgo, Londres, Lisboa','(GMT+1:00) Amsterdão, Berlim, Roma, Estocolmo, Paris','(GMT+2:00) Cairo, Atenas, Istambul, Minsk, Jerusalém','(GMT+3:00) Bagdad, Kuwait, Riade, Moscovo, S.Petersburgo','(GMT+4:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan','(GMT+5:00) Ekaterinburg, Islamabade, Karachi, Tashkent','(GMT+6:00) Almaty, Novosibirsk, Astana, Dhaka','(GMT+7:00) Banguecoque, Jacarta, Hanoi','(GMT+8:00) Pequim, Hong Kong, Taipé, Singapura','(GMT+9:00) Tóquio, Osaka, Sapporo, Seul, Yakutsk','(GMT+10:00) Brisbane, Guam, Canberra, Melbourne, Sidnei','(GMT+11:00) Magadan, Ilhas Salomão., Nova Caledónia','(GMT+12:00) Fiji, Ilhas Marshall, Auckland, Wellington','(GMT+13:00) Nukualofa']",
			"ntp_panel"							:"Servidor NTP",
			"time_server_label"					:"IP/Nome servidor NTP",
			"time_server_after"					:"(Opcional)"
		},
		"diagnostic":{
			"txt"								:"Ferram diagnóstico",
			"diagnostic_panel"					:"Ferramenta de diagnóstico",
			"tools_type_label"						:"Ferramenta diagnóstico",
			"ping_r"							:"Ping",
			"trac_r"							:"Tracert",
			"tools_ip_url_label"						:"IP/Nome domínio", 
			"result_head_info"					:"Resultados diagnóstico",
			"result_info"						:" "
		},
		"remote":{
			"txt"								:"Acesso Remoto",
			"remote_panel"						:"Acesso Remoto",	
			"remote_enable_label"				:"Estado",
			"remote_port_label"					:"Porta"	
		},
		"passwd":{
			"txt"								:"Senha",
			"change_pwd_panel"					:"Senha",
			"old_user_label"					:"Nome de utilizador",
			"old_pwd_label"						:"Senha atual",
			"old_pwd_after"					    :"(Use caracteres: a-z,A-Z,0-9.)",
			"new_user_label"					:"Novo nome utilizador",
			"new_user_after"					:"(Use caracteres: a-z,A-Z,0-9.)",
			"new_pwd_label"						:"Nova senha",
			"new_pwd_after"						:"(Use caracteres: a-z,A-Z,0-9.)",
			"new_pwd_confirm_label"				:"Confirmar nova senha",
			"new_pwd_confirm_after"				:"(Use caracteres: a-z,A-Z,0-9.)"
		},
		"backup":{
			"txt"								:"Backup e restaurar", 
			"backup_panel"						:"Backup",
			
			"restore_panel"						:"Restaurar",
			"tip_restore_info"					:"Sugestões: A operação de restauração demorará cerca de 1 minuto. Durante esta operação, não desligue a alimentação ou pressione o botão Default no Router para não causar danos.",
			"file_label"						:"Ficheiro de backup de",
			"file_up_label"						:"Ficheiro de backup de",
			"load_panel"						:"Restaurar"
			
		},
		"sys_log":{
			"txt"								:"Registro do sistema",
			"sys_log_panel"						:"Registro do sistema",
			"sys_log_thead"						:"['ID','Hora','Registo']"
		},
		"statistics":{
			"txt"								:"Estatísticas",
			"status_sys_panel"					:"Estado do Roteador",
			"run_time_label"					:"Tempo utiliz sistema",
			"cpu_label"							:"Utilização do CPU",
			"mem_label"							:"Utilização da Memoria",

			"statistics_panel"					:"Estatísticas tráfego",
			"statistics_list_thead"				:"['Tipo','Pacotes enviados','Pacotes recebidos','Dados enviados (KBytes)','Dados recebidos (KBytes)']"
		},
		"default":{
			"txt"								:"Padrões de Fábrica",
			"tip_default_info"					:"Sugestões: Todas as opções de configuração serão repostas para os valores predefinidos.",
			"default_panel"						:"Padrões de Fábrica",
			"load_panel"						:"Padrões de Fábrica"
		},
		"reboot":{
			"txt"								:"Reiniciar o sistema",
			"tip_reboot_info"					:"Sugestões: A rede será temporariamente desligada durante o reinício.",
			"reboot_panel"						:"Reiniciar o sistema"
		}
	}
};



//Extra part（to be translated）           ：“Bem-vindo ao router sem fios netis”
//Extra part（to be translated）           ：“Selecionar idioma”
//Extra part（to be translated）           ：“Configuração rápida”
//Extra part（to be translated）           ：“Tipo de ligação à Internet”
//Extra part（to be translated）           ：“Configuração sem fios”
//Extra part（to be translated）           ：“Ir para página de registo...”
//Extra part（to be translated）           ：“Nome de utilizador e senha incorretos”
//Extra part（to be translated）           ：“Endereço IP em conflito com a WAN! Altere o endereço IP da LAN do router.”
