//Language = {};
Language.DU = {
	"common":{
		"all"									:"ALLE",
		"wan_lan_err"							:"Conflict IP-adres met WAN! Verander het LAN IP-adres van de router.",
		"channel"                 				:"Kanaal",
    	"after_map_a"             				:"(voer 10 hexadecimale tekens in (elke combinatie van a-f, A-F, 0-9.))",
    	"after_map_b"             				:'(voer 5 ASCII-tekens in (elke combinatie van a-f, A-F, 0-9.))',
    	"after_map_c"             				:"(voer 26 hexadecimale tekens in (elke combinatie van a-f, A-F, 0-9.))",
    	"after_map_d"             				:'(voer 13 ASCII-tekens in (elke combinatie van a-f, A-F, 0-9.))',
    	"after_map_e"             				:"(voer 64 hexadecimale tekens in (elke combinatie van a-f, A-F, 0-9.))",
    	"after_map_f"             				:'(voer 8-63 ASCII-tekens in (elke combinatie van a-f, A-F, 0-9.))',
    	"after_map_g"             				:'seconden (60-86400)',
		"auto_type"               				:"Auto",
		"welcome_title"           				:"Welkom-netis Draadloze N-router",
		"advanced_title"          				:"netis Draadloze N-router",  
		"DDNS_ERR_FAILED"         				:"Mislukt",//未翻译  to be translated
		"bound"                   				:"Verbonden",//adj. 形容词    已有翻译的词句  bind MAC & IP,  IP & MAC Binding——IP & MAC Binding
		"unbound"                 				:"Verbinding verbroken",//adj.形容词
		"bind"                    				:"Verbinden",//verb 动词， 与16 17条目相关
		"timeout_err"							:"Bewerking mislukt. Probeer het opnieuw.",
		"use_tip"								:"Tijd",
		"restoring"								:"Instellingen worden hersteld...",//已有翻译的词句 Restore——Herstellen
		"defaulting"							:"Herstelt...",//已有翻译的词句 Are you sure you want to reset to factory defaults?——Weet u zeker dat u de fabrieksinstellingen wilt herstellen?
		"rebooting"								:"Herstart...",//已有翻译的词句 System Restart——Systeemherstart
		"days"									:"Dagen",//已有翻译的词句 Day——Dag
		"hours"									:"Uren",//已有翻译的词句 Hour——Uur
		"minutes"								:"Minuten",//已有翻译的词句 Minute——Minuut
		"seconds"								:"Seconden",//已有翻译的词句 Second——Seconde
		"search"								:"Zoekt...",//语境： search for the available wireless signal
		"wel_key_err"							:"(voer 8 tot 63 tekens in behalve bijzondere tekens 【\'\"\\】))",
		"wel_sele_lan"							:"Taal selecteren",
		"wel_tips"								:"Snelle Installatie",
		"wel_inter_tip"							:"Type Internetverbinding",
		"wel_wirel_tip"							:"Draadloos instellen",
		"wel_pwd_tip"							:"(Typ 8 tot 63 tekens.) ",
		"wel_status_label"						:"Beveiliging :",

		"wel_static_tip"						:"Als uw ISP u een vast IP-adres heeft gegeven, kiest u de optie Statisch IP.",
		"wel_dhcp_tip"							:"Als uw ISP u automatisch een IP-adres geeft met een DHCP-server, kiest u de optie DHCP.",
		"wel_pppoe_tip"							:"Als uw ISP een PPPoE (ADSL)-verbinding geeft, kiest u de optie PPPoE.",
		"bind_all"								:"Bind All",
		"advance"								:"Geavanceerd",
		"text_after"							:"Packets/s",
		"wps_off"								:"WPS uitschakelen",
		"wps_on"								:"WPS inschakelen",
		"def_pin"								:"PIN herstellen",
		"new_pin"								:"Nieuwe PIN-code genereren",
		"info"									:"Info",
		"connect"								:"Verbinden",
		"disconnect"          					:"Verbinding verbreken",
		"connected"                             :"Aangesloten",
        "disconnected"                          :"Losgekoppeld",
		"refresh"                     			:"Vernieuwen",
		"open"									:"Apparaat toevoegen",
		"link"									:"Verbinden",
		"save_reboot"							:"Opslaan en herstarten",	
		"add"									:"Toevoegen",
		"del"									:"Verwijderen",
		"del_all"								:"Alles verwijderen",
		"delAll"								:"Alles verwijderen",
		"mod"									:"Wijzigen",
		"reboot"								:"Opnieuw starten",
		"back"									:"Terug",
		"save"									:"Opslaan",
		"keep_all"								:"Alles behouden",
		"wakeup"								:"Wekken",
		"upgrade"								:"Upgraden",
		"backup"								:"Back-up",
		"recover"                               :"Herstellen",
		"restore"								:"Herstellen",
		"help_more_btn"							:"Meer...",
		"ap_get"								:"AP-scan",
		"auto_check"							:"Automatische detectie",
		"help_more_null"						:"",
		"on"									:"Inschakelen",
		"off"									:"Uitschakelen",
		"forbid_s"                              :"Weigeren",
		"allow_s"                               :"Toestaan",
		"df_mac"								:"Standaard MAC",
		"clone_mac"								:"MAC-kloon",
        "start"                                 :"Begin",
        "end"								    :"Einde",
        "browse"                                :"Bladeren",
        "current"                               :"MAC adres kloon",
        "device"                                :"Standaard MAC herstellen",
        "set_reserve"                           :"Reserveren",
        "cancel_reserve"                        :"Annuleren",
        "reserved"                              :"Gereserveerd",
        "static"                                :"Statisch",
        "dynamic"                               :"DHCP",
		"yes"									:"Ja",
		"no"									:"Nee",
        "other"                                 :"Overige",
		"total"									:"Totaal",
        "online"                                :"Online",
        "offline"                               :"Offline",
		"week_0"								:"Zo",
		"week_1"								:"Ma", 
		"week_2"								:"Di",
		"week_3"								:"Wo",
		"week_4"								:"Do",
		"week_5"								:"Vr",
		"week_6"								:"Za",
		"everday"								:"Dagelijks",
		"all_day"								:"Hele dag",
//		"Sun"								    :"Zo",
//		"Mon"								    :"Ma", 
//		"Tue"								    :"Di",
//		"Wed"								    :"Wo",
//		"Thu"								    :"Do",
//		"Fri"								    :"Vr",
//		"Sat"								    :"Za",
//		"week"									:"Week",
		"check_all_label"						:"Alles selecteren",
		"max_size_label_a"						:" Huidige",
		"max_size_label_b"						:"&nbsp;pagina ",
		"size_label"							:"Items weergegeven op elke pagina",
		"size_set_btn"							:"Toepassen",
		"load_tip"								:"Nu bijwerken...",
		"lock_save"								:"Bezig met opslaan",
		"lock_delete"							:"Verwijderen...",
		"lock_add"								:"Toevoegen...",
		"unlock_save"							:"Opslaan gelukt",
		"unlock_delete"							:"Verwijderen gelukt",
		"unlock_add"							:"Toevoegen gelukt",
		"unlock_err"							:"Onbekende waarde teruggegeven. Probeer het opnieuw.",
		"unlock_error"							:"Bewerking mislukt.",
		"time_err"								:"Max niet-actieve tijd moet worden ingesteld tussen 1 en 30 minuten.",
		"dhcp_mtu_err"							:"MTU-grootte moet tussen 576 en 1500 bytes liggen. Probeer het opnieuw.",
		"pppoe_mtu_err"							:"MTU-grootte moet tussen 576 en 1492 bytes liggen. Probeer het opnieuw.",
		"static_mtu_err"						:"MTU-grootte moet tussen 576 en 1500 bytes liggen. Probeer het opnieuw.",
		"l2tp_mtu_err"             				:"MTU-grootte moet tussen 576 en 1460 bytes liggen. Probeer het opnieuw.",
		"pptp_mtu_err"             				:"MTU-grootte moet tussen 576 en 1420 bytes liggen. Probeer het opnieuw.",
		"beacon_err"							:"Waarde Beacon Interval moet tussen 20 en 1000 liggen.",
		"rts_err"								:"Waarde RTS-drempel moet tussen 256 en 2347 liggen.",
		"frag_err"								:"Waarde Fragmentatiedrempel moet tussen 256 en 2346 liggen.",
		"cmp_port_err"							:"De Eindpoort mag niet kleiner zijn dan de Beginpoort. Voer opnieuw in.",
		"cmp_ip_err"							:"Het eindadres mag niet kleiner zijn dan het beginadres. Voer opnieuw in.",
		"mask_err"								:"Het subnetmasker is ongeldig. Geef een ander op.",
		"ip_err"								:"Het IP-adres is ongeldig. Geef een ander op.",
		"key_time_err"							:"De periode voor sleutelvernieuwing ligt tussen 60 en 86400 seconden. Voer opnieuw in.",
		"addr_err"								:"Het adresbereik voor DHCP mag niet groter zijn dan de maximale limiet. Voer opnieuw in.",
		"lan_ip_err"							:"Het adresbereik voor DHCP moet worden ingesteld op hetzelfde netwerksegment als het LAN IP-adres. Voer opnieuw in.",
		"lan_addr_err"							:"Het LAN IP-adres mag geen deel uitmaken van het adresbereik voor DHCP. Voer opnieuw in.",
		"item_err"								:"Meer items kunnen niet worden toegevoegd.",
		"ip_used_err"							:"Het IP-adres is voor een ander item gebruikt. Probeer een nieuw.",
		"qos_band_err"							:"De Bandbreedte moet zijn ingesteld tussen 0 en 12799. Voer opnieuw in.",
		"qos_up_err"							:"De Beperkte Uplink Bandbreedte mag niet kleiner zijn dan de Gegarandeerde Uplink Bandbreedte. Voer opnieuw in.",
		"qos_down_err"							:"De Beperkte Downlink Bandbreedte mag niet kleiner zijn dan de Gegarandeerde Downlink Bandbreedte. Voer opnieuw in.",	
		"key_len_err"							:"De lengte van de wachtwoordsleutel moet zijn:",
		"ddns_start"							:"Bezig met verbinding maken....",
		"ddns_failed"							:"Verificatie mislukt. Controleer de accountgegevens en probeer het opnieuw.",
		"ddns_ok"								:"De verbinding is geslaagd. De domeinnaam is:",
		"oray_user_err"							:"Typ 5 tot 16 tekens, elke combinatie van a-z, A-Z, 0-9, -(koppelteken). Alleen cijfers of alleen - (koppeltekens) is niet toegestaan.",
		"oray_pass_err"							:"Typ 6 tot 16 tekens, elke combinatie van a-z, A-Z, 0-9, bijzondere tekens.",
		"meibu_user_err"						:"Typ 1 tot 26 tekens, elke combinatie van a-z, A-Z, 0-9. Chinese woorden of ongeldige tekens zijn niet toegestaan.",
		"meibu_pass_err"						:"Typ minimaal 4 tekens, elke combinatie van a-z, A-Z, 0-9.",
		"end_time_err"                          :"Onjuiste tijdindeling. Probeer het opnieuw.",
		"reserved_keep"                         :"Ongeldige bewerking. Dit adres is al gereserveerd.",
		"reserved_cancel"                       :"Ongeldige bewerking. Dit adres is niet gereserveerd.",
		password_null							:"Wachtwoord kan niet leeg zijn. Voer opnieuw in.",
		password_ival							:"Voor een wachtwoord alleen letters of cijfers gebruiken. Voer opnieuw in!",
		password_length_err						:"Het wachtwoord moet minder dan 32 tekens lang zijn.. Voer opnieuw in.",
		password_err							:"Het nieuwe ingevoerde wachtwoord komt niet overeen. Voer opnieuw in.",
		mtu_err									:"Lege sleutel is niet toegestaan. Voer het gehele getal opnieuw in.",
		mtu_pppoe_null							:"Lege sleutel is niet toegestaan. Voer het gehele getal opnieuw in.",
		pppoe_text_err							:'Lege sleutel en illegale tekens zoals \\\'“”‘’zijn iet toegestaan. ',
		mtu_ival								:"MTU-grootte moet tussen 576 en [1] bytes liggen. Probeer het opnieuw.",
		ip_addr_null							:"Het IP -adres mag niet leeg of 0.0.0.0 zijn. Voer opnieuw in.",
		ip_addr_ival							:"Ongeldig IP-adres met illegale tekens. Geef een ander op.",
		ip_addr_err								:"Ongeldig IP-adres. Geef een ander op.",
		mask_addr_err							:"Het subnetmasker is ongeldig. Geef een ander op.",
		mac_addr_err							:"Het MAC-adres is ongeldig. Geef een ander op.",
		gw_err									:"De standaard gateway moet worden ingesteld op hetzelfde netwerksegment als het WAN IP-adres. Voer opnieuw in.",
		gw_errs									:"Ongeldige standaard gateway. Geef een andere op.",
		port_null								:"Voer poordres in.",
		port_err								:"De poort moet zijn ingesteld tussen 1 en 65535. Voer opnieuw in.",
		int_number_err							:"Ongeldig nummer. Geef een ander op.",
		string_null								:"Lege sleutel \n en onherkenbare tekens zijn niet toegestaan.",
		string_err								:'Speciale tekens \'"\\ of spaties zijn toegestaan.',
		string_null_err							:'Speciale tekens \'"\\ of spaties zijn niet toegestaan.',
		route_ip_err							:"IP-adres en subnetmasker bevinden zich niet in hetzelfde netwerk. Geef een ander op.",
		auto_disconnect_time_err				:"Max niet-actieve tijd moet worden ingesteld tussen 1 en 30 minuten.",
		dhcp_reserve_err						:"Het IP-adres moet deel uitmaken van het adresbereik voor DHCP. Geef een ander op.",
		dhcp_reserve_lan_ip						:"Het IP -adres mag niet het IP-adres van de router zijn. Geef een ander op. ",
		wireless_key_length						:"De lengte van wachtwoord/sleutel moet :[1] zijn.",
		wireless_key_hex_err					:"Het wachtwoord moet geheel uit hexadecimale tekens betaan.",
		qos_max_up_err							:"De Beperkte Uplink Bandbreedte mag niet kleiner zijn dan de Gegarandeerde Uplink Bandbreedte. Voer opnieuw in.",
		qos_max_down_err						:"De Beperkte Downlink Bandbreedte mag niet kleiner zijn dan de Gegarandeerde Downlink Bandbreedte. Voer opnieuw in.",
		qos_bandwidth_err						:"De Bandbreedte moet zijn ingesteld tussen 0 en 12799. Voer opnieuw in.",
		az09_string_err							:"Voer de volgende tekens in :a-z,A-Z,0-9.",
		string_url_err							:"Voer de volgende tekens in :a-z,A-Z,0-9.",
		string_hex_err							:"Voer de volgende tekens in :a-f,A-F,0-9.",
//		wireless_key_length_info				:'(voer [1] tekens in behalve bijzondere tekens 【\'\"\\】))',
	  	wireless_key_length_info1				:"(Voer [1] hexadecimale tekens in (a-f,A-F,0-9))",
	 	Src_password_err						:"Het huidige wachtwoord is onjuist. Voer opnieuw in.",
	  	save_only_need_reboot					:"De gewijzigde instelling is pas van kracht na herstarten.. We raden aan om eerst de nadere instellingen in te vullen en daarna als laatste stap de router opnieuw te starten.",
		pin_number_err							:"Typ 8 cijfers voor de PIN-code.",
		item_exist								:"Er bestaat reeds een item met deze instellingen. Geef een ander op.",
		"rule_err"								:"Geen illegale tekens en spacties.",
		"domain_err"							:"Ongeldige indeling domeinnaam. Geef een ander op.",
		"dns_null_err"							:"Ongeldig adres DNS-server. Stel minimaal één DNS-server in.",
		"segment_err"							:"Het IP-adres mag niet het netwerkadres zijn. Geef een ander op.",
		"Bcast_err"								:"Het IP-adres mag niet een broadcast-adres zijn. Geef een ander op.",
		"segment_len_err"						:"Het IP-adres bevindt zich niet in het huidige netwerksegment. Geef een ander op.",
		"reserver_err"							:"Het te reserveren IP-adres maakt geen deel uit van het adresbereik voor DHCP. Geef een ander op.",
		"pass_err"								:"Het wachtwoord mag elke combinatie zijn van a-z, A-Z, 0-9, of speciale tekens. Probeer het opnieuw.",
		"year_err"								:"Onjuiste jaarindeling. Geef een ander op (20018-2035).",
		"mon_err"								:"Onjuiste maandindeling. Geef een ander op (1 - 12).",
		"day31_err"								:"Onjuiste dagindeling. Geef een ander op (1 - 31).",
		"day30_err"								:"Onjuiste dagindeling. Geef een ander op (1 - 30).",
		"day29_err"								:"Onjuiste dagindeling. Geef een ander op (1 - 29).",
		"day28_err"								:"Onjuiste dagindeling. Geef een ander op (1 - 28).",
		"hour_err"								:"Onjuiste uurindeling. Geef een ander op (0 - 23).",
		"min_sec_err"							:"Onjuiste indeling minuut of seconde. Geef een ander op (0 - 59).",
		"page_err"								:"Onjuiste pagina-indeling. Geef een ander op (1 - 100).",

		"DDNS_ERR_CLOSE"						:"Gesloten.",
		"DDNS_ERR_CONNECTING"					:"Bezig met verbinding maken....",
		"DDNS_ERR_INUPT"						:"Voer zowel gebruikersnaam als wachtwoord in.",
		"DDNS_ERR_GET_NO_IP"					:"Verkrijgen van serveradres is mislukt.",
		"DDNS_ERR_SYSTEM"						:"Systeemresource is beperkt.",
		"DDNS_ERR_USER"							:"Uw gebruikersnaam of wachtwoord is ongeldig.",
		"DDNS_ERR_OK"							:"Update geslaagd.",
		"DDNS_ERR_SERVER"						:"Fout in DDNS-server.",
		"ST"									:"Standaard service,  ",
		"PR"									:"Professionele service,",

		"del_tip"								:"Weet u zeker dat u alles wilt verwijderen?",
		"del_one_tip"							:"weet u zeker dat u het geselecteerde item wilt verwijderen?",
		"disconnect_tip"						:"Weet u zeker dat u de verbinding met het netwerk wilt verbreken?",
		"connect_tip"							:"Weet u zeker dat u verbinding met het netwerk wilt maken?",
		"default_tip"							:"Weet u zeker dat u de fabrieksinstellingen wilt herstellen?",
		"reboot_tip"							:"Weet u zeker dat u de router wilt herstarten?",
		"reboot_web_tip"						:"De router start opnieuw nadat u de poort hebt gewijzigd. Wilt u doorgaan?",
		"backup_tip"							:"Weet u zeker dat u de instellingen wilt herstellen?",
		"del_reserve_err"						:"Annuleren regel voor adresreservering mislukt.",
		"ip_occupy_err"							:"IP-adres bestaat reeds. Geef een ander op.",
		"mac_occupy_err"						:"MAC-adres bestaat reeds. Geef een ander op.",
		"port_occupy_err"						:"Poort bestaat reeds. Geef een ander op.",
		"port_len_err"							:"Het numerieke bereik van poorten moet gelijk zijn. Bijvoorbeeld bereik externe poort 1-4; bereik interne poort 6-9.",
		"update_err"							:"Geen upgrade-bestand geselecteerd.",
		"update_faild"							:"Firmware upgrade mislukt.",
		"backup_err"							:"Geen back-up bestand geselecteerd.",
		"backup_faild"							:"Back-up mislukt.",
		"ip_len_err"							:"IP-adres niet in bereik. Geef een ander op.",
		"add_item_err"							:"Er bestaat reeds een item met deze instellingen.",
		"_default"								:"Ongeldige invoer."
	},
	"status":{
		"txt"									:"Status",
		"status":{
			"txt"								:"Interface info",
			
			"status_l2tp_panel"					:"L2TP",
			"l2tp_ip_label"						:"IP-adres",
			"l2tp_mask_label"					:"Subnetmasker",
			"l2tp_gw_label"						:"Standaard Gateway",
			"status_pptp_panel"					:"PPTP",
			"pptp_ip_label"						:"IP-adress",
			"pptp_mask_label"					:"Subnetmasker",
			"pptp_gw_label"						:"Standaard Gateway",
			"second_ip_label"					:"Secundaire IP-adres",
			"second_mask_label"					:"Secundaire Subnetmasker",
			
			"status_wan_panel"					:"WAN",
			"conntype_label"					:"Verbindingstype",
			"mac_addr_label"					:"MAC-adres",
			"ip_label"							:"IP-adres",
			"mask_label"						:"Subnetmasker",
			"gw_label"							:"Standaard Gateway",
			"dns_a_label"						:"Primaire DNS",
			"dns_b_label"						:"Secundaire DNS",
			"con_time_label"					:"Tijd koppeling",
			"connected_label"					:"Status koppeling",
			"status_lan_panel"					:"LAN",
			"lan_mac_label"						:"MAC-adres",
			"lan_ip_label"						:"IP-adres",
			"lan_mask_label"					:"Subnetmasker",
			"dhcp_enable_label"					:"DHCP-server",
			"status_wireless_panel"				:"Draadloos",
			"wl_enable_label"					:"Status draadloos",
			"ssid_label"						:"SSID",
			"net_mode_label"					:"Radio modus",
			"sec_mode_label"					:"Type verificatie",
			"channel_label"						:"Kanaal",
			"wl_mac_label"						:"MAC-adres",
			"wps_enable_label"					:"WPS-status"
		}
	},
	"network":{
		"txt"									:"Netwerk",
		"wan":{
			"txt"								:"WAN",
			"mode_panel"						:"WAN-type",
			"access_mode_label"					:"WAN-type",
			"wire_r"							:"Kabel",//字符最长允许至Toegang via ，EN原句为Wired Access， 如果字符长度调整不了，请只翻译 Wired
			"wireless_r"						:"Draadloos",//字符最长允许至Draadloze ，EN原句为Wireless Access， 如果字符长度调整不了，请只翻译 Wireless

			"wireless_config_panel"				:"WISP-instellingen",
			"repeater_ssid_label"				:"SSID",
			"channel_label"						:"Kanaal",
			"channel_options"					:"['Auto','Kanaal 1 ','Kanaal 2 ','Kanaal 3 ','Kanaal 4 ','Kanaal 5 ','Kanaal 6 ','Kanaal 7 ','Kanaal 8 ','Kanaal 9 ','Kanaal 10','Kanaal 11']",
			"rp_sec_mode_label"					:"Type verificatie",
			"rp_sec_mode_options"				:"['Geen','WEP','WPA-PSK','WPA2-PSK']",

			"wep_panel"							:"WEP",
			"rp_key_size_label"					:"Lengte sleutel",
			"rp_key_type_label"					:"Soort encryptie",
			"rp_key_mode_wep_label"				:"Sleutelmodus",
			"rp_key_mode_wpa_label"				:"Sleutelmodus",
			"rp_key_wep_label"					:"Wachtwoord",
			"rp_key_wpa_label"					:"Wachtwoord",
			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",

			"wan_set_panel"						:"WAN-instellingen",
			"conntype_label"					:"WAN-verbindingstype",
			"conntype_options"					:"['DHCP (kabelmodem)','Statisch IP','PPPoE','Rusland PPPoE','Unifi PPPoE','Maxis PPPoE','PPTP/Rusland PPTP','L2TP/Rusland L2TP']",
			"conntype_after"					:"LAN 1 alleen voor IPTV",

			"pppoe_username_label"				:"Gebruikersnaam",
			"pppoe_pwd_label"					:"Wachtwoord",
			"l2tp_username_label"				:"Gebruikersnaam",
			"l2tp_pwd_label"					:"Wachtwoord",
			"l2tp_server_label"					:"Server IP-adres/naam",
			"l2tp_type_label"					:"Verbindingstype",
			"l2tp_ip_label"						:"IP-adres",
			"l2tp_mask_label"					:"Subnetmasker",
			"l2tp_gw_label"						:"Standaard Gateway",

			"pptp_username_label"				:"Gebruikersnaam",
			"pptp_pwd_label"					:"Wachtwoord",
			"pptp_server_label"					:"Server IP-adres/naam",
			"pptp_type_label"					:"Verbindingstype",
			"pptp_ip_label"						:"IP-adres",
			"pptp_mask_label"					:"Subnetmasker",
			"pptp_gw_label"						:"Standaard Gateway",

			"pppoe_service_name_label"			:"Servernaam",
			"pppoe_service_name_after"			:"(Optioneel)",
			"pppoe_ac_name_label"				:"PPPoE AC-naam",
			"pppoe_ac_name_after"				:"(Optioneel)",
			"pppoe_mtu_label"					:"MTU-grootte",
			"pppoe_mtu_after"					:"(De standaardwaarde is 1480, alleen wijzigen als dit noodzakelijk is.)",
			"dns_a_label"						:"Primaire DNS",
			"dns_a_after"						:"(Optioneel)",	
			"dns_b_label"						:"Secundaire DNS",
			"dns_b_after"						:"(Optioneel)",
			"auto_r"							:"Automatisch verbinden",
			"time_r"							:"Op aanvraag verbinden,      Max tijd inactiviteit # minuten (0 betekent altijd actief blijven.)",
			"hand_r"							:"Handmatig verbinden",
			"dhcp_mtu_label"					:"MTU-grootte",
			"dhcp_mtu_after"					:"(De standaardwaarde is 1500, alleen wijzigen als dit noodzakelijk is.)",
			"wan_ip_label"						:"WAN IP-adres",
			"wan_mask_label"					:"Subnetmasker",
			"wan_gw_label"						:"Standaard Gateway",
			"mac_addr_label"					:"MAC-adres",
			"static_mtu_label"					:"MTU-grootte",
			"static_mtu_after"					:"(De standaardwaarde is 1500, alleen wijzigen als dit noodzakelijk is.)",
			"l2tp_mtu_label"					:"MTU-grootte",
			"l2tp_mtu_after"					:"(De standaardwaarde is 1460, alleen wijzigen als dit noodzakelijk is.)",
			"pptp_mtu_label"					:"MTU-grootte",
			"pptp_mtu_after"					:"(De standaardwaarde is 1420, alleen wijzigen als dit noodzakelijk is.)",

			"second_in_panel"					:"Secundaire verbinding",
			"second_in_type_label"				:"Verbindingstype",
			"dy_r"								:"Dynamisch",
			"st_r"								:"Statisch",

			"ap_get_thead"						:"['ID','Netwerknaam','BSSID','Kanaal (Radioband)','Radio modus','Verificatietype','Signaalsterkte','Verbinden']"
		},
		"lan":{
			"txt"								:"LAN",
			"lan_set_panel"						:"LAN",
			"lan_ip_label"						:"IP-adres",
			"lan_mask_label"					:"Subnetmasker",
			"servie_panel"						:"DHCP-server",
			"dhcp_enable_label"					:"DHCP-status",
			"dhcp_start_ip_label"				:"Start IP-adres",
			"dhcp_end_ip_label"					:"Eind IP-adres",

			"dhcp_list_panel"					:"Lijst met DHCP-clients",
			"dhcp_client_list_thead"			:"['ID','IP-adres','MAC-adres','Hostnaam','Gereserveerd','Status','Actie']",
			"load_panel"						:"Router opnieuw starten"
		},
		"iptv":{
			"txt"								:"IPTV",
			"iptv_set_panel"					:"IPTV Mode",
			"iptv_mode_label"					:"IPTV Mode",
			"iptv_mode_options"					:"['Automatisch','Bridge','802.1Q VLAN Tag']",
			"iptv_port_label"					:"IPTV-Poort",
			"iptv_port_options"					:"['LAN1','LAN1 & LAN2']",
			"vlan_set_panel"					:"VLAN Instellingen",
			"vlan_tag_enable_label"				:"VLAN Tag van Internet",
			"vlan_id_inter_label"				:"VLAN ID van Internet",
			"vlan_pri_inter_label"				:"Prioriteit van VLAN",
			"vlan_pri_inter_options"			:"[0,1,2,3,4,5,6,7]",
			
			"vlan_id_iptv_label"				:"VLAN ID van IPTV",
			"vlan_pri_iptv_label"				:"Prioriteit van VLAN",
			"vlan_pri_iptv_options"				:"[0,1,2,3,4,5,6,7]",

			"mvlan_id_iptv_label"				:"Multi-VLAN ID van IPTV",
			"mvlan_pri_iptv_label"				:"Prioriteit van VLAN",
			"mvlan_pri_iptv_options"			:"[0,1,2,3,4,5,6,7]",

			"vlan_id_phone_label"				:"VLAN ID van IP Phone",
			"vlan_pri_phone_label"				:"Prioriteit van VLAN",
			"vlan_pri_phone_options"			:"[0,1,2,3,4,5,6,7]",

			"port_set_panel"					:"Poort Instellingen",
			"iptv_lan1_mode_label"				:"LAN1-Poort Mode",
			"iptv_lan1_mode_options"			:"['Internet','IPTV','IP Phone']",
			"iptv_lan2_mode_label"				:"LAN2-Poort Mode",
			"iptv_lan2_mode_options"			:"['Internet','IPTV','IP Phone']",
			"iptv_lan3_mode_label"				:"LAN3-Poort Mode",
			"iptv_lan3_mode_options"			:"['Internet','IPTV','IP Phone']",
			"iptv_lan4_mode_label"				:"LAN4-Poort Mode",
			"iptv_lan4_mode_options"			:"['Internet','IPTV','IP Phone']"
		},
		"address_reservation":{
			"txt"								:"Adresreservering",
			"reservation_panel"					:"Adresreservering",
			"reserve_des_label"					:"Beschrijving",
			"reserve_ip_label"					:"IP-adres",
			"reserve_mac_label"					:"MAC-adres",

			"reservation_list_panel"			:"Lijst met adresreserveringen",
			"reservation_list_thead"			:"['ID','Beschrijving','IP-adres','MAC-adres','Aanpassen']"
		},
		"opmode":{
			"txt"                               :"Werkingsmodi",
			"opmode_panel"                      :"Werkingsmodi",
			"access_mode_label"                 :"Modus",
			"router_r"                          :"Router",
			"bridge_r"                          :"Bridge"
		}
	},
	"wireless":{
		"txt"									:"Draadloos",
		"base":{
			"txt"								:"Draadloze instellingen",
			"base_panel"						:"Draadloze instellingen",	
			"wl_enable_label"					:"Status draadloos",
			"ssid_label"						:"SSID",
			"wl_stand_label"					:"Radioband",
			"wl_stand_options"					:"['802.11b','802.11g','802.11n','802.11b+g','802.11g+n','802.11b+g+n']",
			"net_mode_label"					:"Radio modus",
			"net_mode_options"					:"['Access Point','Repeater','AP+WDS','WDS','Client']",
		//	"wl_config_label"					:"Configuratie",
			"cl_config_label"					:"Configuratie",
			"rp_config_label"					:"Configuratie",
			"auto_r"							:"Automatisch",
			"hand_r"							:"Handmatig",
			"repeater_ssid_label"				:"Naam externe AP",
			"repeater_mac_label"				:"MAC-adres externe AP",
			"wl_mac_label"						:"MAC-adres",
			"ssid_broad_label"					:"SSID Broadcast",
			"channel_width_label"				:"Kanaalbreedte",
			"20_r"								:"20 MHz",
			"40_r"								:"40 MHz",
			"channel_bind_label"				:"Zijband Regeling",
			"down_r"							:"Lager",
			"up_r"								:"Hoger",
		//"repeater_ssid_label"				:"Repeater SSID",
			"region_label"						:"Regio",
			"region_options"					:"['US','EU','MKK','IC']",
			"channel_label"						:"Kanaal",
			"channel_options"					:"['Auto','Kanaal 1 ','Kanaal 2 ','Kanaal 3 ','Kanaal 4 ','Kanaal 5 ','Kanaal 6 ','Kanaal 7 ','Kanaal 8 ','Kanaal 9 ','Kanaal 10','Kanaal 11']",

			"ap_security_panel"					:"Beveiligingsinstellingen AP",
			"tips_info"							:"Voor de beste beveiliging van uw draadloze netwerk raden we aan om WPA2-PSK in te stellen als verificatietype en AES of TKIP & AES als versleutelingstype.",
			"sec_mode_label"					:"Type verificatie",
			"sec_mode_options"					:"['Geen','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Als WPS is ingeschakeld, wordt het gebruik van WEP als verificatietype afgeraden.",
			"key_size_label"					:"Lengte sleutel",
			"key_type_label"					:"Soort encryptie",
			"key_mode_wep_label"				:"Sleutelmodus",
			"key_mode_wpa_label"				:"Sleutelmodus",
			"key_wep_label"						:"Wachtwoord",
			"key_wpa_label"						:"Wachtwoord",
			"key_time_label"					:"Sleutel vernieuwen",

			"wds_security_panel"				:"WDS beveiligingsinstellingen",
			"wds_sec_mode_label"				:"Type verificatie",
			"wds_sec_mode_options"				:"['Geen','WEP 64 bits','WEP 128 bits','WPA (TKIP)','WPA2 (AES)']",
			"wds_key_mode_wep_label"			:"Sleutelmodus",
			"wds_key_mode_wpa_label"			:"Sleutelmodus",
			"wds_key_wep_label"					:"Wachtwoord",				
			"wds_key_wpa_label"					:"Wachtwoord",				

			"client_security_panel"				:"Beveiligingsinstellingen client",
			"cl_sec_mode_label"					:"Type verificatie",
			"cl_sec_mode_options"				:"['Geen','WEP','WPA-PSK','WPA2-PSK']",
			"cl_key_size_label"					:"Lengte sleutel",
			"cl_key_type_label"					:"Soort encryptie",
			"cl_key_mode_wep_label"				:"Sleutelmodus",
			"cl_key_mode_wpa_label"				:"Sleutelmodus",
			"cl_key_wep_label"					:"Wachtwoord",
			"cl_key_wpa_label"					:"Wachtwoord",
			"cl_key_auto_label"					:"Wachtwoord",
			"cl_key_time_label"					:"Sleutel vernieuwen",

			"repeater_security_panel"			:"Beveiligingsinstellingen repeater",
			"rp_sec_mode_label"					:"Type verificatie",
			"rp_sec_mode_options"				:"['Geen','WEP','WPA-PSK','WPA2-PSK']",
			"rp_key_size_label"					:"Lengte sleutel",
			"rp_key_type_label"					:"Soort encryptie",
			"rp_key_mode_wep_label"				:"Sleutelmodus",
			"rp_key_mode_wpa_label"				:"Sleutelmodus",
			"rp_key_wep_label"					:"Wachtwoord",
			"rp_key_wpa_label"					:"Wachtwoord",
			"rp_key_auto_label"					:"Wachtwoord",
			"rp_key_time_label"					:"Sleutel vernieuwen",

			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_get_thead"						:"['ID','Netwerknaam','BSSID','Kanaal (Radioband)','Radio modus','Verificatietype','Signaalsterkte','Verbinden']"
		},
		"wl_mac_filter":{
			"txt"								:"MAC-filtering",
			"filter_set_panel"					:"Draadloze MAC-filtering",
			"wl_mac_filter_enable_label"		:"Status",
			"wl_mac_filter_rule_label"			:"Filterregel",
			"deny_r"							:"Apparaten in lijst toegang tot netwerk weigeren, andere zijn toegestaan.", //修改，最长字符截至  De apparaten in de lijst de toegang tot het netwerk weigeren, andere zijn t  EN原句为 Deny the listed devices to access the network, others are permitted.
			"allow_r"							:"Apparaten in lijst toegang tot netwerk toestaan, andere worden geweigerd.", //修改，最长字符截至  De apparaten in de lijst de toegang tot het netwerk toestaan, andere worde  EN原句为 Permit the listed devices to access the network, others are denied.
			"contr_des_panel"					:"Beheer lijst draadloze MAC-filtering",
			"mac_des_label"						:"Beschrijving",
			"macaddr_label"						:"MAC-adres",
			"mac_tab_panel"						:"Lijst draadloze MAC-filtering",
			"wl_mac_filter_list_thead"			:"['ID','Beschrijving','MAC-adres','Aanpassen']"
		},
		"wds":{
			"txt"								:"WDS-instellingen",
			"wds_set_panel"						:"WDS-instellingen",
			"wds_name_label"					:"WDS SSID",
			"wds_mac_label"						:"WDS MAC-adres",
			"wds_tab_panel"						:"Lijst met WDS-clients",
			"wl_wds_list_thead"					:"['ID','WDS SSID','WDS MAC-adres','Aanpassen']",
			"ap_get_thead"						:"['ID','Netwerknaam','BSSID','Kanaal (Radioband)','Radio modus','Verificatietype','Signaalsterkte','Verbinden']"
		},
		"advance":{
			"txt"								:"Geavanceerd", //修改，最长字符截至 Draadloos geavancee  ，EN原句为 Wireless Advanced
			"advance_set_panel"					:"Instellingen draadloos geavanceerd",
			"wlan_partition_label"				:"AP-isolatie",
			"iapp_label"						:"Draadloos roaming",
			"shortGi_label"						:"Korte GI",
			"protection_label"					:"Bescherming",
			"out_power_label"					:"Overdraagvermogen",
			"a_r"								:"100%",
			"b_r"								:"70%",
			"c_r"								:"50%",
			"d_r"								:"35%",
			"e_r"								:"15%",
			"wmm_label"							:"WMM"
		},
		"multiple_ssid":{
			"txt"								:"Meervoudige SSID",
			"ap1_multiple_status_panel"  		:"Meervoudige SSID",
			"multiple_status_label"    			:"Status",
			"multiple_sele_label"      			:"Kies AP",//翻译 to be translated
			"multiple_sele_options"    			:"['AP1','AP2','AP3']",
			"para_set_panel"					:"Instellingen meervoudige SSID",
			"ap1_wl_enable_label"				:"Status",
			"ap1_wl_mac_label"					:"MAC-adres",
			"ap1_ssid_label"					:"SSID",
			"ap1_ssid_broad_label"				:"SSID Broadcast",
			"ap1_sec_contr_label"				:"Toegangsbeheer",
			"ap1_sec_contr_options"				:"['LAN+WAN','WAN']",
			"ap1_encryption_label"				:"Soort encryptie",
			"ap1_encryption_options"			:"['Geen','TKIP','AES']",
			"ap1_password_label"				:"Wachtwoord",

			"safe_set_panel"					:"Beveiligingsinstellingen meervoudige SSID",
			"ap1_sec_mode_label"				:"Type verificatie",
			"ap1_sec_mode_options"				:"['Geen','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Als WPS is ingeschakeld, wordt het gebruik van WEP als verificatietype afgeraden.",
			"ap1_key_size_label"				:"Lengte sleutel",
			"ap1_key_type_label"				:"Lengte sleutel",
			"ap1_key_mode_wep_label"			:"Sleutelmodus",
			"ap1_key_mode_wpa_label"			:"Sleutelmodus",
			"ap1_key_wep_label"					:"Wachtwoord",
			"ap1_key_wpa_label"					:"Wachtwoord",
			"ap1_key_time_label"				:"Sleutel vernieuwen",
			"64_r"								:"64 bits",
			"128_r"								:"128 bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_link_tab_panel"					:"Lijst meervoudige SSID",
			"wl_link_ap1_list_thead"			:"['ID','SSID','MAC-adres','SSID Broadcast','Toegangsbeheer','Verificatietype','Aanpassen']"
		},
		"wps":{
			"txt"								:"WPS-instelling",
			"wps_security_panel"				:"WPS-instelling",
			"wps_enable_label"					:"WPS-status",
			"wps_pin_label"						:"PIN-code",
			"hand_add_label"					:"Nieuw apparaat toevoegen",

			"hand_add_p_panel"					:"Nieuw apparaat toevoegen",
			"hand_r"							:"Typ PIN-code nieuw apparaat: ",
			"press_r"							:"Druk binnen twee minuten op de knop van het nieuwe apparaat"
		},
		"list":{
			"txt"								:"Lijst draadloze clients",
			"list_panel"						:"Lijst draadloze clients",
			"wl_link_ap0_list_thead"			:"['ID','SSID','Hostnaam','MAC-adres','Verzonden packets','Ontvangen packets']"
		}
	},
	"management":{
		"txt"									:" Toegangsbeheer",
	    "attack_defense":{
			"txt"								:"Geavanceerde beveiliging",
			"attack_defense_panel"				:"Geavanceerde beveiliging",
			"ping_wan_label"					:"PING-packets van WAN-poort negeren",
			"ping_lan_label"					:"PING Gateway negeren",
			"port_packet_label"				    :"Port Scanning Packets negeren",
			"icmp_flood_label"				    :"Preventie ICMP-Flood Attack",
			"icmp_flood_after"					:"Packets drempel (5-3000)",
			"tcp_flood_label"				    :"Preventie TCP-SYN-Flood Attack",
			"tcp_flood_after"					:"Packets drempel (5-3000)",
			"udp_flood_label"				    :"Preventie UDP-Flood Attack",
			"udp_flood_after"					:"Packets drempel (5-3000)",
			"virus_filter_label"		        :"Virusfiltering",
			"arp_attack_label"				    :"Preventie ARP-aanval",
			"attack_log_tab_panel"              :"Log ARP-aanval",
			"attack_log_list_thead"             :"['ID','Tijd','Inhoud log']"
		},
		"ip_filter":{
			"txt"								:"IP-filtering ",
			"ip_filter_panel"					:"IP-filtering ",
			"ip_filter_enable_label"			:"Status",
			"ip_filter_rule_label"				:"Filterregel",
			"deny_r"							:"Netwerktoegang weigeren voor niet hieronder opgenomen apparaten.", //修改，最长字符截至  Netwerktoegang weigeren voor apparaten die niet hieronder zijn opg   EN翻译原句为 Deny the network access for the devices not listed below.
			"permit_r"							:"Netwerktoegang toestaan voor niet hieronder opgenomen apparaten.", //修改，最长字符截至  Netwerktoegang toestaan voor apparaten die niet hieronder zijn opge  EN翻译原句为 Permit the network access for the devices not listed below.
			"ip_filter_list_panel"				:"Instellingen regels IP-filtering ",
			"ip_describe_label"					:"Beschrijving",
			"ip_status_label"					:"Status",
			"ip_status_options"					:"['Inschakelen','Uitschakelen']",
			"ip_rule_label"						:"Regel",
			"ip_rule_options"					:"['Toestaan','Weigeren']",
			"ip_src_sele_label"					:"Bronhost",
			"ip_src_sele_options"      			:"['Alle hosts','Specifieke hosts','Subnet host','Segment host']",
			"ip_src_ip_label"                 	:"IP-adres",
			"ip_src_mask_label"            		:"Subnetmasker",
			"ip_src_start_label"				:"Start IP-adres",
			"ip_src_end_label"					:"Eind IP-adres",
			"ip_des_sele_label"                 :"Bestemmingshost",
			"ip_des_sele_options"               :"['Alle hosts','Specifieke hosts','Subnet host','Segment host']",
			"ip_des_ip_label"                   :"IP-adres",
			"ip_des_mask_label"                 :"Subnetmasker",
			"ip_des_start_label"				:"Start IP-adres",
			"ip_des_end_label"               	:"Eind IP-adres",
			"ip_proto_label"					:"Protocol",
			"ip_port_label"						:"Poort",
			"ip_proto_options"					:"['ALLE','TCP','UDP','ICMP']",
			"ip_day_label"						:"Dag",
			"ip_day_btn"						:"ALLE",
			"ip_time_label"						:"Tijd",
			"ip_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"ip_filter_tab_panel"				:"Lijst IP-filtering ",
			"ip_filter_list_thead"				:"['ID','Beschrijving','Regel','Bron-IP','Bestemmings-IP','Protocol','Poort','Dag','Tijd','Aanpassen']"
		},
		"mac_filter":{
			"txt"								:"MAC-filtering",
			"mac_filter_panel"					:"MAC-adres filtering",
			"mac_filter_enable_label"			:"Status",
			"mac_filter_rule_label"				:"Filterregel",
			"deny_r"							:"Netwerktoegang weigeren voor niet hieronder opgenomen apparaten.", //修改，最长字符截至  Netwerktoegang weigeren voor apparaten die niet hieronder zijn opg   EN翻译原句为 Deny the network access for the devices not listed below.
			"permit_r"							:"Netwerktoegang toestaan voor niet hieronder opgenomen apparaten.", //修改，最长字符截至  Netwerktoegang toestaan voor apparaten die niet hieronder zijn opge  EN翻译原句为 Permit the network access for the devices not listed below.
			"mac_filter_list_panel"				:"Instellingen regels MAC-filtering ",
			"mac_describe_label"				:"Beschrijving",
			"mac_status_label"					:"Status",
			"mac_status_options"				:"['Inschakelen','Uitschakelen']",
			"mac_rule_label"					:"Regel",
			"mac_rule_options"					:"['Toestaan','Weigeren']",
			"mac_filter_label"					:"MAC-adres bron",
			"mac_day_label"						:"Dag",
			"mac_time_label"					:"Tijd",
			"mac_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"mac_filter_tab_panel"				:"Lijst MAC-filtering",
			"mac_filter_list_thead"					:"['ID','Beschrijving','Regel','MAC-adres','Dag','Tijd','Aanpassen']"
		},
		"dns_filter":{
			"txt"								:"Domeinfiltering ",
			"domain_filter_panel"				:"Domeinfiltering ",
			"dns_filter_enable_label"			:"Status",
			"dns_filter_rule_label"				:"Filterregel",
			"deny_r"							:"Toegang weigeren met niet hieronder opgenomen DNS-trefwoorden.",	 //修改，最长字符截至 Toegang weigeren met DNS-trefwoorden die niet hieronder zijn opgenome   EN翻译原句为 Deny the access with the DNS Keywords not listed below.
			"permit_r"							:"Toegang toestaan met niet hieronder opgenomen DNS-trefwoorden.", //修改，最长字符截至 Toegang toestaan met DNS-trefwoorden die niet hieronder zijn opgenome  EN翻译原句为 Permit the access with the DNS Keywords not listed below.
			"domain_filter_list_panel"			:"Instellingen regels Domeinfiltering ",
			"dns_des_label"						:"Beschrijving",
			"dns_status_label"					:"Status",
			"dns_status_options"				:"['Inschakelen','Uitschakelen']",
			"dns_rule_label"					:"Regel",
			"dns_rule_options"					:"['Toestaan','Weigeren']",
			"dns_key_label"						:"DNS-trefwoorden",
			"dns_day_label"						:"Dag",
			"dns_time_label"					:"Tijd",
			"dns_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"domain_filter_tab_panel"			:"Lijst domeinfiltering ",
			"dns_filter_list_thead"				:"['ID','Beschrijving','Regel','DNS-trefwoorden','Dag','Tijd','Aanpassen']"		
		}
	},
	"qos":{
		"txt"									:"Bandbreedteregeling", // 匹配691行的翻译，更改Bandwidth翻译  EN原句为 Bandwidth Control
		"qos":{
			"config_panel"						:"Configuratie bandbreedteregeling", // 匹配691行的翻译，更改Bandwidth翻译  EN原句为 Bandwidth Control Configuration
			"qos_enable_label"					:"Status",
			"qos_rule_label"					:"Regel",
			"qos_rule_label_a"					:"Uplink",
			"qos_rule_label_b"					:"Downlink",
			"qos_rule_label_c"					:"(KB/s) (0 betekent geen beperkingen.)",
			"qos_rule_label_d"					:"(KB/s) (0 betekent geen beperkingen.)",

			"qos_set_panel"						:"Instellingen regels bandbreedteregeling",// 匹配691行的翻译，更改Bandwidth翻译  EN原句为 Bandwidth Control Rule Settings
			"qos_des_label"						:"Beschrijving",
			"qos_status_label"					:"Status",
			"qos_status_options"				:"['Inschakelen','Uitschakelen']",
			"qos_sele_label"					:"Host",
			"qos_sele_options"					:"['Alle hosts','Specifieke hosts','Subnet host','Segment host']",
			"qos_ip_label"						:"IP-adres",
			"qos_mask_label"					:"Subnetmasker",
			"qos_ip_start_label"				:"Start IP-adres",
			"qos_ip_end_label"					:"Eind IP-adres",
			"qos_min_label"						:"Gegarandeerde bandbr.", //修改，最长字符为 Gegarandeerde bandbree  EN原句为 Guaranteed Bandwidth 
			"qos_min_label_a"					:"Uplink",
			"qos_min_label_b"					:"Downlink",
			"qos_min_label_c"					:"(KB/s) (0 betekent geen beperkingen.) ",
			"qos_min_label_d"					:"(KB/s) (0 betekent geen beperkingen.)",
			"qos_max_label"						:"Beperkte bandbreedte", // 匹配691行的翻译，更改Bandwidth翻译 EN原句为 Restricted Bandwidth
			"qos_max_label_a"					:"Uplink",
			"qos_max_label_b"					:"Downlink",
			"qos_max_label_c"					:"(KB/s) (0 betekent geen beperkingen.) ",
			"qos_max_label_d"					:"(KB/s) (0 betekent geen beperkingen.)",

			"qos_list_panel"					:"Lijst bandbreedteregeling",// 匹配691行的翻译，更改Bandwidth翻译 EN原句为 Bandwidth Control List
			"qos_rule_list_thead"				:"['ID','Beschrijving','Status','Bereik IP-adressen',{head:'Gegarandeerde bandbreedte',con:['Uplink','Downlink']},{head:'Beperkte bandbreedte',con:['Uplink','Downlink']},'Aanpassen']" //待调整691
		}
	},
	"ddns":{
		"txt"									:"Dynamisch DNS",
		"ddns":{
			"txt"								:"Dynamisch DNS",
			"ddns_panel"						:"Dynamisch DNS",
			"ddns_enable_label"					:"DDNS status",
			"ddns_sp_label"						:"Serviceprovider",
			"ddns_sp_options"					:"['No-IP','Dyndns']",
			"ddns_sp_after"						:"<a href='http://www.meibu.com/reg.asp'>www.noip.com</a>",
			"ddns_username_label"				:"Gebruikersnaam",
			"ddns_password_label"				:"Wachtwoord",
			"ddns_domain_label"					:"Domeinnaam",
			"ddns_port_label"					:"Poort",
			"ddns_info_label"					:"Verbindingsstatus",
			"ddns_tips_info"					:"Tips: Nadat u bent aangemeld bij DDNS, kunt u zich beter afmelden voordat u naar een andere account wisselt."
		}
	},
	"forward":{
		"txt"									:"Doorsturen",
		"virtual":{
			"txt"								:"Virtuele servers",
			"vir_server_panel"					:"Instellingen regels virtuele servers",
			"vir_name_label"					:"Beschrijving",
			"vir_ip_label"						:"IP-adres",
			"vir_proto_label"					:"Protocol",
			"vir_proto_options"					:"['ALLE','TCP','UDP','HTTP','HTTPS','FTP','POP3','SMTP','DNS','TELENT','IPSEC','PPTP','Windows Terminal Client','GuruGuru','H323 VoIP-telefoon','Soribada']",
			"vir_outport_label"					:"Externe poort",
			"vir_inport_label"					:"Interne poort",
			"vir_tab_panel"						:"Lijst virtuele servers",
			"virtual_server_list_thead"			:"['ID','Beschrijving','IP-adres','Protocol','Externe poort','Interne poort','Aanpassen']"
		}
	},
	"advanced":{
		"txt"									:"Geavanceerd",
		"vpn":{
			"txt"								:"VPN",
			"vpn_panel"							:"VPN Pass-through instellingen",
			"pptp_enable_label"					:"PPTP Pass-through",
			"l2tp_enable_label"					:"L2TP Pass-through",
			"ipsec_enable_label"				:"IPSEC Pass-through"
		},
		"igmp":{
			"txt"								:"IGMP",
			"igmp_panel"						:"IGMP",
			"igmp_enable_label"					:"Status"
		},
		"dmz":{
			"txt"								:"DMZ",
			"dmz_panel"							:"DMZ",
			"dmz_enable_label"					:"Status",
			"dmz_ip_label"						:"IP-adres",

			"super_dmz_panel"					:"Super DMZ",
			"super_dmz_enable_label"			:"Status",
			"super_dmz_addr_label"				:"MAC-adres"
		},
		"portTrigger":{
			"txt"								:"Poortactivering",
			"port_trigger_panel"				:"Instellingen regels poortactivering",
			"port_select_label"					:"Voorgedefinieerde regel",
			"port_select_options"				:"['--Maak een keuze--','GuruGuru','BuddyBuddy','Enppy','Pruna TCP','Pruna UDP']",
			"app_name_label"					:"Beschrijving",
			"trigger_proto_label"				:"Activeringsprotocol",
			"trigger_proto_options"				:"['TCP','UDP']",
			"app_port_label"					:"Activeringspoort",
			"forward_proto_label"				:"Doorstuurprotocol",
			"forward_proto_options"				:"['TCP','UDP']",
			"forward_port_label"				:"Doorstuurpoort",
		
			"trigger_tab_panel"					:"Lijst poortactivering",
			"app_port_list_thead"				:"['ID','Beschrijving','Activeringsprotocol','Activeringspoort','Doorstuurprotocol','Doorstuurpoort','Aanpassen']"
		},
		"ftp":{
			"txt"								:"FTP privépoort",
			"ftp_port_panel"					:"FTP privépoort",
			"ftp_enable_label"					:"Status",
			"ftp_port_label"					:"Poort"
		},
		"upnp":{
			"txt"								:"UPnP",
			"upnp_panel"						:"Instelling UPnP",
			"upnp_enable_label"					:"Status"
		},
		"binds":{
			"txt"								:"IP & MAC Binding",
			"binds_set_panel"					:"IP & MAC Binding",
			"binds_rule_label"					:"Filterregel",
			"deny_r"							:"Internettoegang toestaan voor apparaten die niet in de lijst voorkomen.",
			"allow_r"							:"Internettoegang weigeren voor apparaten die niet in de lijst voorkomen.",

			"contr_binds_panel"					:"Instellingen regels IP & MAC Binding",
			"binds_des_label"					:"Beschrijving",
			"binds_ip_label"					:"IP-adres",
			"binds_mac_label"					:"MAC-adres",
			"binds_port_label"					:"Interface",
			"binds_port_options"				:"['LAN','WAN']",
			"binds_tab_panel"					:"Lijst IP & MAC Binding",
			"binds_list_thead"					:"['ID','Beschrijving','IP-adres','MAC-adres','Interface','Aanpassen']"
		},
		"arp_list":{
			"txt"								:"ARP-lijst",
			"arp_list_panel"					:"ARP-lijst",
			"arp_list_thead"					:"['ID','IP-adres','MAC-adres']"
		},
		"routing":{
			"txt"								:"Statische routering",
			"routing_panel"						:"Instellingen regels statische routering",
			"route_des_label"					:"Beschrijving",
			"route_type_label"					:"Type",
			"route_type_options"				:"['NET','HOST']",
			"ip_value_label"					:"IP-adres bestemming",
			"mask_value_label"					:"Subnetmasker",
			"gateway_value_label"				:"Standaard Gateway",
			"route_tab_panel"					:"Lijst statische routering",
			"static_routing_list_thead"			:"['ID','Beschrijving','Type','IP-adres','Subnetmasker','Standaard gateway','Aanpassen']"
		},
		"interface_mode":{
			"txt"								:"Poortinstellingen",
			"mode_panel"						:"Instellingen WAN-poort",
			"wan_label"							:"WAN-poort",
			"wan_options"						:"['Auto','10 M Duplex','10 M Half-Duplex','100 M Duplex','100 M Half-Duplex']"
		},
		"wakeup":{
			"txt"								:"WOL",
			"wakeup_panel"						:"WOL",
			"wakeup_mac_label"					:"MAC-adres"
		}
	},
	"misc":{
		"txt"									:"Systeemtools",
		"update":{
			"txt"								:"Firmware-upgrade",
			"update_panel"						:"Firmware-upgrade",
			"version_label"						:"Huidige versie",
			"file_label"						:"Upgradebestand",
			"updata_file_label"                 :"Upgradebestand",
			"load_panel"						:"Firmware-upgrade",
			"tip_update_info"					:"Tips: Schakel de router niet uit tijdens het opwaarderen van de firmware."
		},
		"sys_time":{
			"txt"								:"Tijdinstellingen",
			"time_set_panel"					:"Tijdinstellingen",
			"time_now_label"					:"Huidige tijd",
			"time_type_label"					:"Type",
			"ntp_r"								:"NTP",
			"hand_r"							:"Handmatig",
			"time_date_label"					:"Datum",
			"time_date_after"					:"Jaar",
			"time_date_after2"					:"Maand",
			"time_date_after3"					:"Dag",
			"time_time_label"					:"Tijd",
			"time_time_after"					:"Uur",
			"time_time_after2"					:"Minuut",
			"time_time_after3"					:"Seconde",
			"timezone_label"					:"GMT",
			"timezone_options"					:"['(GMT-12:00) Eniwetok, Kwajalein','(GMT-11:00) Midway Is., Samoa','(GMT-10:00) Hawaii','(GMT-09:00) Alaska','(GMT-08:00) Pacific Time (US Canada); Los Angeles','(GMT-07:00) Mountain Time (US Canada); Arizona','(GMT-06:00) Central Time (US Canada); Mexico City','(GMT-05:00) Eastern Time(US Canada); Bogota, New York, Lima','(GMT-04:00) Atlantic Time (Canada); Caracas, La Pax','(GMT-03:00) Brasilia, Buenos Aires, Georgetown, Greenland','(GMT-02:00) Mid-Atlantic','(GMT-01:00) Kaap Verdische eill, Azoren','(GMT) Greenwich Mean Time; Dublin, Edinburgh, Londen, Lissabon','(GMT+1:00) Amsterdam, Berlijn, Rome, Stockholm, Parijs','(GMT+2:00) Cairo, Athene, Istanboel, Minsk, Jerusalem','(GMT+3:00) Bagdad, Koeweit, Riyad, Moskou, St.Petersburg','(GMT+4:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan','(GMT+5:00) Ekaterinburg, Islamabad, Karachi, Tashkent','(GMT+6:00) Almaty, Novosibirsk, Astana, Dhaka','(GMT+7:00) Bangkok, Djakarta, Hanoi','(GMT+8:00) Beijing, Hong Kong, Taipei, Singapore','(GMT+9:00) Tokio, Osaka, Sapporo, Seoul, Yakutsk','(GMT+10:00) Brisbane, Guam, Canberra, Melbourne, Sydney','(GMT+11:00) Magadan, Salomon eil., New Caledonia','(GMT+12:00) Fiji, Marshall eil., Auckland, Wellington','(GMT+13:00) Nukualofa']",
			"ntp_panel"							:"NTP-Server",
			"time_server_label"					:"IP/naam NTP-servernaam",
			"time_server_after"					:"(Optioneel)"
		},
		"diagnostic":{
			"txt"								:"Diagnostische", //修改，最长字符截至 Diagnostische hulppr  EN原句为 Diagnostic Tools
			"diagnostic_panel"					:"Diagnostische hulpprogramma's", // 匹配867行的翻译，EN原句为 Diagnostic Tools
			"tools_type_label"					:"Hulpprogramma's", //修改，最长字符截至 Diagnostisch hulpprogra  EN原句为 Diagnostic Tool ，如无法满足，只翻译 Tool
			"ping_r"							:"Ping",
			"trac_r"							:"Tracert",
			"tools_ip_url_label"				:"IP-adres/domeinnaam",
			"result_head_info"					:"Diagnostische resultaten ",
			"result_info"						:" "
		},
		"remote":{
			"txt"								:"Extern beheer",
			"remote_panel"						:"Extern beheer",	
			"remote_enable_label"				:"Status",
			"remote_port_label"					:"Poort"	
		},
		"passwd":{
			"txt"								:"Wachtwoord",
			"change_pwd_panel"					:"Wachtwoord",
			"old_user_label"					:"Gebruikersnaam",
			"old_pwd_label"						:"Huidig wachtwoord",
			"old_pwd_after"					    :"(Voer de volgende tekens in :a-z,A-Z,0-9.)",
			"new_user_label"					:"Nieuwe gebruikersnaam",
			"new_user_after"					:"(Voer de volgende tekens in :a-z,A-Z,0-9.)",
			"new_pwd_label"						:"Nieuw wachtwoord",
			"new_pwd_after"						:"(Voer de volgende tekens in :a-z,A-Z,0-9.)",
			"new_pwd_confirm_label"				:"Bevestig wachtwoord",
			"new_pwd_confirm_after"				:"(Voer de volgende tekens in :a-z,A-Z,0-9.)"
		},
		"backup":{
			"txt"								:"Back-up en herstellen",
			"backup_panel"						:"Back-up",//翻译错误 ， 要翻译的是 Backup
			
			"restore_panel"						:"Herstel",//翻译错误 ， 要翻译的是 Restore
			"tip_restore_info"					:"Tips: Het herstelproces duurt ongeveer 1 minuut. Tijdens het proces de stroom niet uitschakelen of op de knop Default op de router drukken om schade te voorkomen.",
			"file_label"						:"Back-upbestand",
			"file_up_label"						:"Back-upbestand",
			"load_panel"						:"Herstellen"
			
		},
		"sys_log":{
			"txt"								:"Systeemlogboek",
			"sys_log_panel"						:"Systeemlogboek",
			"sys_log_thead"						:"['ID','Tijd','Inhoud log']"
		},
		"statistics":{
			"txt"								:"Statistieken",
			"status_sys_panel"					:"Routerstatus",
			"run_time_label"					:"Systeem uptime",
			"cpu_label"							:"CPU-gebruik",
			"mem_label"							:"Geheugengebruik",

			"statistics_panel"					:"Verkeersstatistieken",
			"statistics_list_thead"				:"['Type','Verzonden packets','Ontvangen packets','Verzonden data (KBytes)','Ontvangen data (KBytes)']"
		},
		"default":{
			"txt"								:"Fabrieksinstellingen",
			"tip_default_info"					:"Tips: Voor alle configuratie-instellingen worden de standaardwaarden teruggezet.",
			"default_panel"						:"Fabrieksinstellingen",
			"load_panel"						:"Fabrieksinstellingen"
		},
		"reboot":{
			"txt"								:"Systeemherstart",
			"tip_reboot_info"					:"Tips: Tijdens het herstarten is de verbinding met het netwerk verbroken.",
			"reboot_panel"						:"Systeemherstart"
		}
	}
};



//Extra part（to be translated）           ：“Welkom-netis Draadloze N-router”
//Extra part（to be translated）           ：“Taal selecteren”
//Extra part（to be translated）           ：“Snelle installatie”
//Extra part（to be translated）           ：“Type internetverbinding”
//Extra part（to be translated）           ：“Draadloos instellen”
//Extra part（to be translated）           ：“Ga naar registratie...”
//Extra part（to be translated）           ：“Onjuiste gebruikersnaam of wachtwoord”
//Extra part（to be translated）           ：“Conflict IP-adres met WAN! Verander het LAN IP-adres van de router.”
