//Language = {};
Language.FR = {
	"common":{
		"all"									:"TOUS",
		"wan_lan_err"							:"Conflit d'adresse IP avec WAN! Veuillez changer l'adresse IP LAN du routeur.",
		"channel"                 				:"Canal",
		"after_map_a"             				:"(Veuillez entrer 10 caractères hexadécimaux (a-f, A-F, 0-9))",
    	"after_map_b"             				:"(Veuillez entrer 5 caractères ASCII (a-z, A-Z, 0-9))",
    	"after_map_c"             				:"(Veuillez entrer 26 caractères hexadécimaux (a-f, A-F, 0-9))",
    	"after_map_d"             				:"(Veuillez entrer 13 caractères ASCII (a-z, A-Z, 0-9))",
    	"after_map_e"             				:"(Veuillez entrer 64 caractères hexadécimaux (a-f, A-F, 0-9))",
    	"after_map_f"             				:"(Veuillez entrer 8-63 caractères ASCII (a-z, A-Z, 0-9))",
    	"after_map_g"             				:'secondes(60-86400)',
		"auto_type"               				:"Auto",
		"welcome_title"           				:"Bienvenue au Routeur sans fil N-netis",
		"advanced_title"          				:"Routeur sans fil N-netis",  
		"DDNS_ERR_FAILED"         				:"Échec",//OK
		"bound"                   				:"Lien",//OK
		"unbound"                 				:"Délier",//OK
		"bind"                    				:"Lier",//OK
		"timeout_err"							:"Échec d'opération ! Veuillez réessayer.",
		"use_tip"								:"Heure",
		"restoring"								:"Restauration réglages...",//OK
		"defaulting"							:"Réinitialisation....",//OK
		"rebooting"								:"Redémarrage...",//OK
		"days"									:"Jour",//OK
		"hours"									:"Heures",//OK
		"minutes"								:"Minutes",//OK
		"seconds"								:"Secondes",//OK
		"search"								:"Recherche...",//OK
		"wel_key_err"							:"(Veuillez entrer between 8 and 63 caractères (sauf les caractères spéciaux 【\'\"\\】))",
		"wel_sele_lan"							:"Sélectionner la langue",
		"wel_tips"								:"Configuration rapide",
		"wel_inter_tip"							:"Type de connexion Internet",
		"wel_wirel_tip"							:"Configuration sans fil",
		"wel_pwd_tip"							:"(Veuillez entrer entre 8 et 63 caractères.) ",
		"wel_status_label"						:"Avancés :",
		
		"wel_static_tip"						:"Si votre ISP fournit les infos d'une adresse IP fixe, veuillez sélectionner l'option IP statique.",
		"wel_dhcp_tip"							:"Si votre ISP fournit une adresse IP automatique avec un serveur DHCP, veuillez sélectionner l'option DHCP.",
		"wel_pppoe_tip"							:"Si votre ISP fournit une connexion PPPoE(ADSL), veuillez sélectionner l'option PPPoE.",
		"bind_all"								:"Attacher tous",
		"advance"								:"Avancé",
		"text_after"							:"Paquet/s",
		"wps_off"								:"Désactiver WPS",
		"wps_on"								:"Activer WPS",
		"def_pin"								:"Restaurer PI",
		"new_pin"								:"Générer nouveau PIN",
		"info"									:"Info",
		"connect"								:"Connecter",
		"disconnect"          					:"Déconnecter",
		"connected"                             :"Connecté",
        "disconnected"                          :"Déconnecté",
		"refresh"                     			:"Rafraîchir",
		"open"									:"Ajouter appareil",	
		"link"									:"Connecter",
		"save_reboot"							:"Enregistrer & redémarrer",	
		"add"									:"Ajouter",
		"del"									:"Supprimer",
		"del_all"								:"Effacer tous",
		"delAll"								:"Effacer tous",
		"mod"									:"Modifier",
		"reboot"								:"Redémarrer",
		"back"									:"Retour",
		"save"									:"Enregistrer",
		"keep_all"								:"Conserver tous",
		"wakeup"								:"Réveiller",
		"upgrade"								:"Mettre à jour",
		"backup"								:"Sauvegarder",
		"recover"                               :"Restaurer",
		"restore"								:"Restaurer",
		"help_more_btn"							:"Autres...",
		"ap_get"								:"Scan AP",
		"auto_check"							:"Détection auto",
		"help_more_null"						:"",
		"on"									:"Activer",
		"off"									:"Désactiver",
		"forbid_s"                              :"Refuser",
		"allow_s"                               :"Autoriser",
		"df_mac"								:"MAC par défaut",
		"clone_mac"								:"Clone MAC",
        "start"                                 :"Début",
        "end"								    :"Fin",
        "browse"                                :"Parcourir",
        "current"                               :"Clone adresse MAC",
        "device"                                :"Restaurer MAC par défaut",
        "set_reserve"                           :"Réserver",
        "cancel_reserve"                        :"Annuler",
        "reserved"                              :"Réservé",
        "static"                                :"Statique",
        "dynamic"                               :"DHCP",
		"yes"									:"Oui",
		"no"									:"Non",
        "other"                                 :"Autre",
		"total"									:"Total",
        "online"                                :"En ligne",
        "offline"                               :"Hors ligne",
		"week_0"								:"Dim",
		"week_1"								:"Lun", 
		"week_2"								:"Mar",
		"week_3"								:"Mer",
		"week_4"								:"Jeu",
		"week_5"								:"Ven",
		"week_6"								:"Sam",
		"everday"								:"Tous les jours",
		"all_day"								:"Toute la journée",
//		"Sun"								    :"Dim",
//		"Mon"								    :"Lun", 
//		"Tue"								    :"Mar",
//		"Wed"								    :"Mer",
//		"Thu"								    :"Jeu",
//		"Fri"								    :"Ven",
//		"Sat"								    :"Sam",
//		"week"									:"Semaine",
		"check_all_label"						:"Sélectionner tout",
		"max_size_label_a"						:"Actuel",
		"max_size_label_b"						:"&nbsp;page ",
		"size_label"							:"Éléments affichés dans chaque page",
		"size_set_btn"							:"Appliquer",
		"load_tip"								:"Mettre à jour maintenant...",
		"lock_save"								:"Enregistrement…",
		"lock_delete"							:"Suppression...",
		"lock_add"								:"Ajout...",
		"unlock_save"							:"Enregistrement réussi !",
		"unlock_delete"							:"Suppression réussie !",
		"unlock_add"							:"Ajout réussi !",
		"unlock_err"							:"Valeur retour non identifiée ! Veuillez réessayer.",
		"unlock_error"							:"Échec d'opération !",
		"time_err"								:"La Durée d'attente max. doit être réglée entre 1 et 30 minutes.",
		"dhcp_mtu_err"							:"La Taille MTU doit être entre 576 et 1500 octets. Veuillez réessayer.",
		"pppoe_mtu_err"							:"La Taille MTU doit être entre 576 et 1492 octets. Veuillez réessayer.",
		"static_mtu_err"						:"La Taille MTU doit être entre 576 et 1500 octets. Veuillez réessayer.",
		"l2tp_mtu_err"             				:"La Taille MTU doit être entre 576 et 1460 octets. Veuillez réessayer.",
		"pptp_mtu_err"             				:"La Taille MTU doit être entre 576 et 1420 octets. Veuillez réessayer.",
		"beacon_err"							:"La valeur de Intervalle du beacon doit être entre 20 et 1000.",
		"rts_err"								:"La valeur de Seuil RTS doit être entre 256 et 2347.",
		"frag_err"								:"La valeur de Seuil de fragmentation doit être entre 256 et 2346.",
		"cmp_port_err"							:"Le Port de fin ne peut pas être inférieure au Port de début. Veuillez entrer à nouveau.",
		"cmp_ip_err"							:"L'Adresse de fin ne peut pas être inférieure à l'Adresse de début. Veuillez entrer à nouveau.",
		"mask_err"								:"Le Masque de sous-réseau n'est pas valide. Veuillez entrer un autre.",
		"ip_err"								:"L'adresse IP n'est pas valide. Veuillez entrer un autre.",
		"key_time_err"							:"La Période de renouvellement de touche est entre 60 et 86400 secondes. Veuillez entrer à nouveau.",
		"addr_err"								:"La Plage d'adresse DHCP ne doit pas être plus que la limite max. Veuillez entrer à nouveau.",
		"lan_ip_err"							:"La Plage d'adresse DHCP doit être sur le même segment de réseau que l’adresse IP LAN. Veuillez entrer à nouveau.",
		"lan_addr_err"							:"L’adresse IP LAN ne peut pas être incluse dans la plage d'adresse DHCP. Veuillez entrer à nouveau.",
		"item_err"								:"Impossible d'ajouter d'autres éléments.",
		"ip_used_err"							:"L'Adresse IP a été utilisé avec un autre élément. Veuillez essayer une autre.",
		"qos_band_err"							:"La Bande passante doit être entre 0 et 12799. Veuillez entrer à nouveau.",
		"qos_up_err"							:"La Bande passante de chargement limitée ne peut pas être moins que la Bande passante de chargement garantie. Veuillez entrer à nouveau.",
		"qos_down_err"							:"La Bande passante de téléchargement limitée ne peut pas être moins que la Bande passante de téléchargement garantie. Veuillez entrer à nouveau.",	
		"key_len_err"							:"La longueur du Mot de passe/Clé doit être:",
		"ddns_start"							:"Connexion...",
		"ddns_failed"							:"Échec d'authentification. Veuillez vérifier les infos de votre compte et réessayer.",
		"ddns_ok"								:"Vous vous êtes connectés avec succès ! Le Nom du domaine est:",
		"oray_user_err"							:"Veuillez entrer entre 5 et 16 caractères, n'importe quelle combinaison avec a-z, A-Z, 0-9, -(tiret). Il n'est pas possible de n'utiliser que des chiffres ou des - (tiret).",
		"oray_pass_err"							:"Veuillez entrer entre 6 et 16 caractères, n'importe quelle combinaison avec a-z, A-Z, 0-9, caractères spéciaux.",
		"meibu_user_err"						:"Veuillez entrer entre 1 et 26 caractères, n'importe quelle combinaison avec a-z, A-Z, 0-9, caractères spéciaux.",
		"meibu_pass_err"						:"Veuillez entrer au moins 4 caractères, n'importe quelle combinaison avec a-z, A-Z, 0-9.",
		"end_time_err"                          :"Format de l'heure incorrect. Veuillez réessayer.",
		"reserved_keep"                         :"Opération non valide ! Cette adresse a déjà été réservé.",
		"reserved_cancel"                       :"Opération non valide ! Cette adresse n'a pas été réservé.",
		password_null							:"Le mot de passe ne peut pas être vide. Veuillez entrer à nouveau.",
		password_ival							:"Seulement des chiffres ou des lettres peuvent être utilisés pour le mot de passe. Veuillez entrer à nouveau!",
		password_length_err						:"Le mot de passe doit avoir moins de 32 caractères. Veuillez entrer à nouveau.",
		password_err							:"Le nouveau mot de passe que vous avez entré ne correspond pas. Veuillez entrer à nouveau.",
		mtu_err									:"Une clé vide n'est pas permis. Veuillez entrer un chiffre entier à nouveau.",
		mtu_pppoe_null							:"Une clé vide n'est pas permis. Veuillez entrer un chiffre entier à nouveau.",
		pppoe_text_err							:"Une clé vide et les caractères illégaux comme \\\'“”‘’ sont interdits. ",
		mtu_ival								:"La Taille MTU doit être entre 576 et [1] octets. Veuillez réessayer.",
		ip_addr_null							:"L'Adresse IP ne peut pas être vide ou 0.0.0.0. Veuillez entrer à nouveau.",
		ip_addr_ival							:"Adresse IP non valide avec des caractères illégaux. Veuillez entrer un autre.",
		ip_addr_err								:"Adresse IP non valide. Veuillez entrer un autre.",
		mask_addr_err							:"Le Masque de sous-réseau n'est pas valide. Veuillez entrer un autre.",
		mac_addr_err							:"L'adresse MAC n'est pas valide. Veuillez entrer un autre.",
		gw_err									:"La Passerelle par défaut doit être sur le même segment de réseau que l’adresse IP WAN. Veuillez entrer à nouveau.",
		gw_errs									:"Passerelle par défaut non valide. Veuillez entrer un autre.",
		port_null								:"Veuillez entrer l’adresse du port.",
		port_err								:"Le port doit être entre 1 et 65535.",
		int_number_err							:"Numéro non valide. Veuillez entrer un autre.",
		string_null								:"Une clé vide\n et les caractères illégaux comme sont interdits.",
		string_err								:'Aucun caractère spécial \'"\\  ou espace n\'est permis.',
		string_null_err							:'Aucun caractère spécial \'"\\  n\'est permis.',
		route_ip_err							:"L'adresse IP et le Masque de sous-réseau ne figurent pas dans le même sous-réseau. Veuillez entrer un autre.",
		auto_disconnect_time_err				:"La Durée d'attente max. doit être réglée entre 1 et 30 minutes.",
		dhcp_reserve_err						:"L’adresse IP doit être incluse dans la plage d'adresse DHCP. Veuillez entrer un autre.",
		dhcp_reserve_lan_ip						:"L’adresse IP doit être différent de l'adresse IP LAN du routeur. Veuillez entrer un autre. ",
		wireless_key_length						:"La longueur du Mot de passe/Clé doit être :[1].",
		wireless_key_hex_err					:"Le mot de passe doit être des caractères hexadécimaux.",
		qos_max_up_err							:"La Bande passante de chargement limitée ne peut pas être moins que la Bande passante de chargement garantie. Veuillez entrer à nouveau.",
		qos_max_down_err						:"La Bande passante de téléchargement limitée ne peut pas être moins que la Bande passante de téléchargement garantie. Veuillez entrer à nouveau.",
		qos_bandwidth_err						:"La Bande passante doit être entre 0 et 12799. Veuillez entrer à nouveau.",
		az09_string_err							:"Veuillez entrer des caractères :a-z,A-Z,0-9.",
		string_url_err							:"Veuillez entrer des caractères :a-z,A-Z,0-9,-.",
		string_hex_err							:"Veuillez entrer des caractères :a-f,A-F,0-9.",
//    	wireless_key_length_info				:"(Veuillez entrer [1] caractères (sauf les caractères spéciaux 【\'\"\\】))",
	  	wireless_key_length_info1				:"(Veuillez entrer [1] caractères hexadécimaux (a-f,A-F,0-9))",
	 	Src_password_err						:"Le mot de passe n'est pas correct. Veuillez entrer à nouveau.",
	  	save_only_need_reboot					:"Le réglage a été changé et les modifications prendront effet après le redémarrage. Il est recommandé de finir les autres réglages en premier puis de redémarrer le routeur à l'étape finale.",
		pin_number_err							:"Veuillez entrer 8 chiffres pour le code PIN.",
		item_exist								:"Un élément avec le même réglage existe déjà. Veuillez entrer un autre.",
		"rule_err"								:"Aucun caractère illegal ou espace.",
		"domain_err"							:"Format du Nom de domaine non valide. Veuillez entrer un autre.",
		"dns_null_err"							:"Adresse du serveur DNS non valide. Veuillez régler au moins un Serveur DNS.",
		"segment_err"							:"L’Adresse IP doit être différent de l'Adresse réseau. Veuillez entrer un autre.",
		"Bcast_err"								:"L’Adresse IP doit être différent de l'Adresse de diffusion. Veuillez entrer un autre.",
		"segment_len_err"						:"L'Adresse IP n'est pas sur le segment de réseau actuel. Veuillez entrer un autre.",
		"reserver_err"							:"L’adresse IP à réserver n'est pas dans la plage d'adresse DHCP. Veuillez entrer un autre.",
		"pass_err"								:"Le mot de passe doit être une combinaison de a-z, A-Z, 0-9, ou des caractères spéciaux. Veuillez réessayer.",
		"year_err"								:"Format de l'année incorrect. Veuillez entrer un autre (2008~2035).",
		"mon_err"								:"Format du mois incorrect. Veuillez entrer un autre (1~12).",
		"day31_err"								:"Format du jour incorrect. Veuillez entrer un autre (1~31).",
		"day30_err"								:"Format du jour incorrect. Veuillez entrer un autre (1~30).",
		"day29_err"								:"Format du jour incorrect. Veuillez entrer un autre (1~29).",
		"day28_err"								:"Format du jour incorrect. Veuillez entrer un autre (1~28).",
		"hour_err"								:"Format de l'heure incorrect. Veuillez entrer un autre (0~23).",
		"min_sec_err"							:"Format des minutes ou des secondes incorrect. Veuillez entrer un autre (0~59).",
		"page_err"								:"Format de page incorrect. Veuillez entrer un autre (1~100).",

		"DDNS_ERR_CLOSE"						:"Fermé.",
		"DDNS_ERR_CONNECTING"					:"Connexion...",
		"DDNS_ERR_INUPT"						:"Veuillez entrer le nom d’utilisateur et le mot de passe.",
		"DDNS_ERR_GET_NO_IP"					:"Échec d'obtention de l'adresse du serveur.",
		"DDNS_ERR_SYSTEM"						:"Ressources du système limitées.",
		"DDNS_ERR_USER"							:"Nom d'utilisateur ou mot de passe incorrect.",
		"DDNS_ERR_OK"							:"Mise à jour réussie !",
		"DDNS_ERR_SERVER"						:"Erreur de serveur DDNS.",
		"ST"									:"Service Standard,  ",
		"PR"									:"Service Professionnel,",

		"del_tip"								:"Souhaitez-vous vraiment tout supprimer ?",
		"del_one_tip"							:"Souhaitez-vous vraiment supprimer l'élément sélectionnée ?",
		"disconnect_tip"						:"Voulez-vous vraiment déconnecter le réseau ?",
		"connect_tip"							:"Voulez-vous vraiment connecter le réseau ?",
		"default_tip"							:"Voulez-vous vraiment réinitialiser les valeurs d'usine ?",
		"reboot_tip"							:"Voulez-vous vraiment redémarrer le routeur ?",
		"reboot_web_tip"						:"Le routeur redémarrera lorsque vous changez le port. Voulez-vous continuer ?",
		"backup_tip"							:"Voulez-vous vraiment restaurer les réglages ?",
		"del_reserve_err"						:"Échec d'annulation de la règle de réservation d'adresse.",
		"ip_occupy_err"							:"Adresse IP existant déjà. Veuillez entrer un autre.",
		"mac_occupy_err"						:"Adresse MAC existant déjà. Veuillez entrer un autre.",
		"port_occupy_err"						:"Port existant déjà. Veuillez entrer un autre.",
		"port_len_err"							:"La plage des numéros de port doit être la même. Par ex. plage de port externe, 1-4; Plage de port interne, 6-9.",
		"update_err"							:"Aucun fichier de mise à jour sélectionné.",
		"update_faild"							:"Échec de mise à jour du firmware.",
		"backup_err"							:"Aucun fichier de sauvegarde sélectionné.",
		"backup_faild"							:"Échec de sauvegarde.",
		"ip_len_err"							:"L'Adresse IP n'est pas dans la plage. Veuillez entrer un autre.",
		"add_item_err"							:"Un élément avec le même réglage existe déjà.",
		"_default"								:"Sortie non valide."
	},
	"status":{
		"txt"									:"Statut",
		"status":{
			"txt"								:"Info d'interface",
			
			"status_l2tp_panel"					:"L2TP",
			"l2tp_ip_label"						:"Adresse IP",
			"l2tp_mask_label"					:"Masque de sous-réseau",
			"l2tp_gw_label"						:"Passerelle par défaut",
			"status_pptp_panel"					:"PPTP",
			"pptp_ip_label"						:"Adresse IP",
			"pptp_mask_label"					:"Masque de sous-réseau",
			"pptp_gw_label"						:"Passerelle par défaut",
			"second_ip_label"					:"Adresse IP secondaire",
			"second_mask_label"					:"Masque de sous-réseau secondaire",
			
			"status_wan_panel"					:"WAN",
			"conntype_label"					:"Type de connexion",
			"mac_addr_label"					:"Adresse MAC",
			"ip_label"							:"Adresse IP",
			"mask_label"						:"Masque de sous-réseau",
			"gw_label"							:"Passerelle par défaut",
			"dns_a_label"						:"DNS primaire",
			"dns_b_label"						:"DNS secondaire",
			"con_time_label"					:"Heure de liaison",
			"connected_label"					:"Statut de liaison",
			"status_lan_panel"					:"LAN",
			"lan_mac_label"						:"Adresse MAC",
			"lan_ip_label"						:"Adresse IP",
			"lan_mask_label"					:"Masque de sous-réseau",
			"dhcp_enable_label"					:"Serveur DHCP",
			"status_wireless_panel"				:"Sans fil",
			"wl_enable_label"					:"Statut sans fil",
			"ssid_label"						:"SSID",
			"net_mode_label"					:"Mode Radio",
			"sec_mode_label"					:"Type d'authentification",
			"channel_label"						:"Canal",
			"wl_mac_label"						:"Adresse MAC",
			"wps_enable_label"					:"Statut WPS"
		}
	},
	"network":{
		"txt"									:"Réseau",
		"wan":{
			"txt"								:"WAN",
			"mode_panel"						:"Type WAN",
			"access_mode_label"					:"Type WAN",
			"wire_r"							:"Accès câblé",
			"wireless_r"						:"Accès sans fil",

			"wireless_config_panel"				:"Réglages WISP",
			"repeater_ssid_label"				:"SSID",
			"channel_label"						:"Canal",
			"channel_options"					:"['Auto','Canal 1 ','Canal 2 ','Canal 3 ','Canal 4 ','Canal 5 ','Canal 6 ','Canal 7 ','Canal 8 ','Canal 9 ','Canal 10','Canal 11']",
			"rp_sec_mode_label"					:"Type d'authentification",
			"rp_sec_mode_options"				:"['Aucune','WEP','WPA-PSK','WPA2-PSK']",

			"wep_panel"							:"WEP",
			"rp_key_size_label"					:"Longueur de la clé",
			"rp_key_type_label"					:"Type de cryptage",
			"rp_key_mode_wep_label"				:"Mode Clé",
			"rp_key_mode_wpa_label"				:"Mode Clé",
			"rp_key_wep_label"					:"Mot de passe",
			"rp_key_wpa_label"					:"Mot de passe",
			"64_r"								:"64bits",
			"128_r"								:"128bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",

			"wan_set_panel"						:"Réglages WAN",
			"conntype_label"					:"Type de connexion WAN",
			"conntype_options"					:"['DHCP(Câble Modem)','IP statique','PPPoE','Russia PPPoE','Unifi PPPoE','Maxis PPPoE','PPTP/Russia PPTP','L2TP/Russia L2TP']",
			"conntype_after"					:"LAN 1 seulement pour IPTV",

			"pppoe_username_label"				:"Nom d'utilisateur",
			"pppoe_pwd_label"					:"Mot de passe",
			"l2tp_username_label"				:"Nom d'utilisateur",
			"l2tp_pwd_label"					:"Mot de passe",
			"l2tp_server_label"					:"IP/Nom du serveur",
			"l2tp_type_label"					:"Type de connexion",
			"l2tp_ip_label"						:"Adresse IP",
			"l2tp_mask_label"					:"Masque de sous-réseau",
			"l2tp_gw_label"						:"Passerelle par défaut",

			"pptp_username_label"				:"Nom d'utilisateur",
			"pptp_pwd_label"					:"Mot de passe",
			"pptp_server_label"					:"IP/Nom du serveur",
			"pptp_type_label"					:"Type de connexion",
			"pptp_ip_label"						:"Adresse IP",
			"pptp_mask_label"					:"Masque de sous-réseau",
			"pptp_gw_label"						:"Passerelle par défaut",

			"pppoe_service_name_label"			:"Nom du serveur",
			"pppoe_service_name_after"			:"(Optionnel)",
			"pppoe_ac_name_label"				:"Nom PPPoE AC",
			"pppoe_ac_name_after"				:"(Optionnel)",
			"pppoe_mtu_label"					:"Taille MTU",
			"pppoe_mtu_after"					:"(Le réglage par défaut est 1480, ne le changez pas sauf si nécessaire.)",
			"dns_a_label"						:"DNS primaire",
			"dns_a_after"						:"(Optionnel)",	
			"dns_b_label"						:"DNS secondaire",
			"dns_b_after"						:"(Optionnel)",
			"auto_r"							:"Connecter automatiquement",
			"time_r"							:"Connecter sur demande,      Temps d'attente max # minutes(0 indique actif tout le temps.)",
			"hand_r"							:"Connecter manuellement",
			"dhcp_mtu_label"					:"Taille MTU",
			"dhcp_mtu_after"					:"(Le réglage par défaut est 1500, ne le changez pas sauf si nécessaire.)",
			"wan_ip_label"						:"Adresse IP WAN",
			"wan_mask_label"					:"Masque de sous-réseau",
			"wan_gw_label"						:"Passerelle par défaut",
			"mac_addr_label"					:"Adresse MAC",
			"static_mtu_label"					:"Taille MTU",
			"static_mtu_after"					:"(Le réglage par défaut est 1500, ne le changez pas sauf si nécessaire.)",
			"l2tp_mtu_label"					:"Taille MTU",
			"l2tp_mtu_after"					:"(Le réglage par défaut est 1460, ne le changez pas sauf si nécessaire.)",
			"pptp_mtu_label"					:"Taille MTU",
			"pptp_mtu_after"					:"(Le réglage par défaut est 1420, ne le changez pas sauf si nécessaire.)",

			"second_in_panel"					:"Connexion secondaire",
			"second_in_type_label"				:"Type de connexion",
			"dy_r"								:"Dynamique",
			"st_r"								:"Statique",

			"ap_get_thead"						:'["ID","Nom du réseau","BSSID","Canal(Bande radio)","Mode radio","Type d\'authentification","Puissance du signal","Connecter"]'
		},
		"lan":{
			"txt"								:"LAN",
			"lan_set_panel"						:"LAN",
			"lan_ip_label"						:"Adresse IP",
			"lan_mask_label"					:"Masque de sous-réseau",
			"servie_panel"						:"Serveur DHCP",
			"dhcp_enable_label"					:"Statut DHCP",
			"dhcp_start_ip_label"				:"Adresse IP de début",
			"dhcp_end_ip_label"					:"Adresse IP de fin",

			"dhcp_list_panel"					:"Liste Client DHCP",
			"dhcp_client_list_thead"			:'["ID","Adresse IP","Adresse MAC","Nom d\'hôte","Réservé","Statut","Opération"]',
			"load_panel"						:"Redémarrer le routeur"
		},
		"iptv":{
			"txt"								:"IPTV",
			"iptv_set_panel"					:"Mode IPTV",
			"iptv_mode_label"					:"Mode IPTV",
			"iptv_mode_options"					:"['Automatique','Bridge','VLAN 802.1Q Tag']",
			"iptv_port_label"					:"Port IPTV",
			"iptv_port_options"					:"['LAN1','LAN1 & LAN2']",
			"vlan_set_panel"					:"Paramétrages VLAN",
			"vlan_tag_enable_label"				:"VLAN Tag pour Internet",
			"vlan_id_inter_label"				:"ID VLAN - Internet",
			"vlan_pri_inter_label"				:"Priorité VLAN",
			"vlan_pri_inter_options"			:"[0,1,2,3,4,5,6,7]",
			
			"vlan_id_iptv_label"				:"ID VLAN - IPTV",
			"vlan_pri_iptv_label"				:"Priorité VLAN",
			"vlan_pri_iptv_options"				:"[0,1,2,3,4,5,6,7]",

			"mvlan_id_iptv_label"				:"ID VLAN Multiple - IPTV",
			"mvlan_pri_iptv_label"				:"Priorité VLAN",
			"mvlan_pri_iptv_options"			:"[0,1,2,3,4,5,6,7]",

			"vlan_id_phone_label"				:"ID VLAN - Téléphone IP",
			"vlan_pri_phone_label"				:"Priorité VLAN",
			"vlan_pri_phone_options"			:"[0,1,2,3,4,5,6,7]",

			"port_set_panel"					:"Paramétrages du Port",
			"iptv_lan1_mode_label"				:"Mode Port LAN1",
			"iptv_lan1_mode_options"			:"['Internet','IPTV','Téléphone IP']",
			"iptv_lan2_mode_label"				:"Mode Port LAN2",
			"iptv_lan2_mode_options"			:"['Internet','IPTV','Téléphone IP']",
			"iptv_lan3_mode_label"				:"Mode Port LAN3",
			"iptv_lan3_mode_options"			:"['Internet','IPTV','Téléphone IP']",
			"iptv_lan4_mode_label"				:"Mode Port LAN4",
			"iptv_lan4_mode_options"			:"['Internet','IPTV','Téléphone IP']"
		},
		"address_reservation":{
			"txt"								:"Réservation d'adresse",
			"reservation_panel"					:"Réservation d'adresse",
			"reserve_des_label"					:"Description",
			"reserve_ip_label"					:"Adresse IP",
			"reserve_mac_label"					:"Adresse MAC",

			"reservation_list_panel"			:"Liste de Réservation d'adresse",
			"reservation_list_thead"			:"['ID','Description','Adresse IP','Adresse MAC','Modifier']"
		},
		"opmode":{
			"txt"                               :"Mode",
			"opmode_panel"                      :"Mode de Fonctionnement",
			"access_mode_label"                 :"Mode",
			"router_r"                          :"Routeur",
			"bridge_r"                          :"Bridge"
		}
	},
	"wireless":{
		"txt"									:"Sans fil",
		"base":{
			"txt"								:"Réglages sans fil",
			"base_panel"						:"Réglages sans fil",	
			"wl_enable_label"					:"Statut sans fil",
			"ssid_label"						:"SSID",
			"wl_stand_label"					:"Bande radio",
			"wl_stand_options"					:"['802.11b','802.11g','802.11n','802.11b+g','802.11g+n','802.11b+g+n']",
			"net_mode_label"					:"Mode Radio",
			"net_mode_options"					:'["Point d\'accès","Répéteur","AP+WDS","WDS","Client"]',
		//	"wl_config_label"					:"Configuration",
			"cl_config_label"					:"Configuration",
			"rp_config_label"					:"Configuration",
			"auto_r"							:"Automatique",
			"hand_r"							:"Manuel",
			"repeater_ssid_label"				:"Nom PA distant",
			"repeater_mac_label"				:"Adresse MAC PA distant",
			"wl_mac_label"						:"Adresse MAC",
			"ssid_broad_label"					:"Diffusion SSID",
			"channel_width_label"				:"Largeur du canal",
			"20_r"								:"20MHz",
			"40_r"								:"40MHz",
			"channel_bind_label"				:"Contrôle de bande latéral",
			"down_r"							:"Plus bas",
			"up_r"								:"Plus haut",
		//"repeater_ssid_label"				:"Répéteur SSID",
			"region_label"						:"Région",
			"region_options"					:"['US','EU','MKK','IC']",
			"channel_label"						:"Canal",
			"channel_options"					:"['Auto','Canal 1 ','Canal 2 ','Canal 3 ','Canal 4 ','Canal 5 ','Canal 6 ','Canal 7 ','Canal 8 ','Canal 9 ','Canal 10','Canal 11']",

			"ap_security_panel"					:"Réglages de sécurité PA",
			"tips_info"							:"Pour une sécurité optimale avec votre réseau sans fil, nous vous recommandons de régler WPA2-PSK comme Type d'authentification et AES ou TKIP & AES comme Type de cryptage.",
			"sec_mode_label"					:"Type d'authentification",
			"sec_mode_options"					:"['Aucune','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Lorsque WPS est activé, il n'est pas recommandé de régler WEP comme Type d'authentification.",
			"key_size_label"					:"Longueur de la clé",
			"key_type_label"					:"Type de cryptage",
			"key_mode_wep_label"				:"Mode Clé",
			"key_mode_wpa_label"				:"Mode Clé",
			"key_wep_label"						:"Mot de passe",
			"key_wpa_label"						:"Mot de passe",
			"key_time_label"					:"Renouvellement de clé",

			"wds_security_panel"				:"Réglages de sécurité WDS",
			"wds_sec_mode_label"				:"Type d'authentification",
			"wds_sec_mode_options"				:"['Aucune','WEP 64bits','WEP 128bits','WPA (TKIP)','WPA2 (AES)']",
			"wds_key_mode_wep_label"			:"Mode Clé",
			"wds_key_mode_wpa_label"			:"Mode Clé",
			"wds_key_wep_label"					:"Mot de passe",				
			"wds_key_wpa_label"					:"Mot de passe",				

			"client_security_panel"				:"Réglages de sécurité du client",
			"cl_sec_mode_label"					:"Type d'authentification",
			"cl_sec_mode_options"				:"['Aucune','WEP','WPA-PSK','WPA2-PSK']",
			"cl_key_size_label"					:"Longueur de la clé",
			"cl_key_type_label"					:"Type de cryptage",
			"cl_key_mode_wep_label"				:"Mode Clé",
			"cl_key_mode_wpa_label"				:"Mode Clé",
			"cl_key_wep_label"					:"Mot de passe",
			"cl_key_wpa_label"					:"Mot de passe",
			"cl_key_auto_label"					:"Mot de passe",
			"cl_key_time_label"					:"Renouvellement de clé",

			"repeater_security_panel"			:"Réglages de sécurité du répéteur",
			"rp_sec_mode_label"					:"Type d'authentification",
			"rp_sec_mode_options"				:"['Aucune','WEP','WPA-PSK','WPA2-PSK']",
			"rp_key_size_label"					:"Longueur de la clé",
			"rp_key_type_label"					:"Type de cryptage",
			"rp_key_mode_wep_label"				:"Mode Clé",
			"rp_key_mode_wpa_label"				:"Mode Clé",
			"rp_key_wep_label"					:"Mot de passe",
			"rp_key_wpa_label"					:"Mot de passe",
			"rp_key_auto_label"					:"Mot de passe",
			"rp_key_time_label"					:"Renouvellement de clé",

			"64_r"								:"64bits",
			"128_r"								:"128bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_get_thead"						:'["ID","Nom du réseau","BSSID","Canal(Bande radio)","Mode radio","Type d\'authentification","Puissance du signal","Connecter"]'
		},
		"wl_mac_filter":{
			"txt"								:"Filtrage MAC",
			"filter_set_panel"					:"Filtrage MAC sans fil",
			"wl_mac_filter_enable_label"		:"Statut",
			"wl_mac_filter_rule_label"			:"Règle de filtrage",
			"deny_r"							:"Refuser l'accès des appareils listés au réseau, les autres sont permis",
			"allow_r"							:"Permettre les appareils listés d'accéder au réseau, les autres sont interdits",
			"contr_des_panel"					:"Gestion de Liste de filtrage MAC sans fil",
			"mac_des_label"						:"Description",
			"macaddr_label"						:"Adresse MAC",
			"mac_tab_panel"						:"Liste de filtrage MAC sans fil",
			"wl_mac_filter_list_thead"			:"['ID','Description','Adresse MAC','Modifier']"
		},
		"wds":{
			"txt"								:"Réglages WDS",
			"wds_set_panel"						:"Réglages WDS",
			"wds_name_label"					:"WDS SSID",
			"wds_mac_label"						:"Adresse MAC WDS",
			"wds_tab_panel"						:"Liste Client WDS",
			"wl_wds_list_thead"					:"['ID','WDS SSID','Adresse MAC WDS','Modifier']",
			"ap_get_thead"						:'["ID","Nom du réseau","BSSID","Canal(Bande radio)","Mode radio","Type d\'authentification","Puissance du signal","Connecter"]'
		},
		"advance":{
			"txt"								:"Avancés sans fil",
			"advance_set_panel"					:"Réglages avancés sans fil",
			"wlan_partition_label"				:"Isolation PA",
			"iapp_label"						:"Roaming sans fil",
			"shortGi_label"						:"GI court",
			"protection_label"					:"Protection",
			"out_power_label"					:"Puissance de transmission",
			"a_r"								:"100%",
			"b_r"								:"70%",
			"c_r"								:"50%",
			"d_r"								:"35%",
			"e_r"								:"15%",
			"wmm_label"							:"WMM"
		},
		"multiple_ssid":{
			"txt"								:"SSID multiple",
			"ap1_multiple_status_panel"  		:"SSID multiple",
			"multiple_status_label"    			:"Statut",
			"multiple_sele_label"      			:"Sélect. AP",//OK
			"multiple_sele_options"    			:"['AP1','AP2','AP3']",
			"para_set_panel"					:"Réglages SSID multiples",
			"ap1_wl_enable_label"				:"Statut",
			"ap1_wl_mac_label"					:"Adresse MAC",
			"ap1_ssid_label"					:"SSID",
			"ap1_ssid_broad_label"				:"Diffusion SSID",
			"ap1_sec_contr_label"				:"Contrôle d'accès",
			"ap1_sec_contr_options"				:"['LAN+WAN','WAN']",
			"ap1_encryption_label"				:"Type de cryptage",
			"ap1_encryption_options"			:"['None','TKIP','AES']",
			"ap1_password_label"				:"Mot de passe",

			"safe_set_panel"					:"Réglages de sécurité SSID multiples",
			"ap1_sec_mode_label"				:"Type d'authentification",
			"ap1_sec_mode_options"				:"['Aucune','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"Lorsque WPS est activé, il n\'est pas recommandé de régler WEP comme Type d'authentification.",
			"ap1_key_size_label"				:"Longueur de la clé",
			"ap1_key_type_label"				:"Longueur de la clé",
			"ap1_key_mode_wep_label"			:"Mode Clé",
			"ap1_key_mode_wpa_label"			:"Mode Clé",
			"ap1_key_wep_label"					:"Mot de passe",
			"ap1_key_wpa_label"					:"Mot de passe",
			"ap1_key_time_label"				:"Renouvellement de clé",
			"64_r"								:"64bits",
			"128_r"								:"128bits",
			"hex_r"								:"HEX",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_link_tab_panel"					:"Liste SSID multiples",
			"wl_link_ap1_list_thead"			:"['ID','SSID','Adresse MAC','Diffusion SSID','Contrôle d\\'accès','Type d\\'authentification','Modifier']"
		},
		"wps":{
			"txt"								:"Réglages WPS",
			"wps_security_panel"				:"Réglages WPS",
			"wps_enable_label"					:"Statut WPS",
			"wps_pin_label"						:"Code PIN",
			"hand_add_label"					:"Ajouter un nouvel appareil",

			"hand_add_p_panel"					:"Ajouter un nouvel appareil",
			"hand_r"							:"Entrez le PIN du nouvel appareil: ",
			"press_r"							:"Appuyez sur le bouton du nouvel appareil dans deux minutes"
		},
		"list":{
			"txt"								:"Liste Client sans fil",
			"list_panel"						:"Liste Client sans fil",
			"wl_link_ap0_list_thead"			:'["ID","SSID","Nom d\'hôte","Adresse MAC","Paquets envoyés","Paquets reçus"]'
		}
	},
	"management":{
		"txt"									:" Contrôle d'accès",
	    "attack_defense":{
			"txt"								:"Sécurité avancée",
			"attack_defense_panel"				:"Sécurité avancée",
			"ping_wan_label"					:"Ignorer paquets PING du port WAN",
			"ping_lan_label"					:"Ignorer passerelle PING",
			"port_packet_label"				    :"Ignorer paquets de scan de port",
			"icmp_flood_label"				    :"Prévention d'attaque du type ICMP",
			"icmp_flood_after"					:"Limite de paquets (5-3000)",
			"tcp_flood_label"				    :"Prévention d'attaque du type TCP-SYN",
			"tcp_flood_after"					:"Limite de paquets (5-3000)",
			"udp_flood_label"				    :"Prévention d'attaque du type UDP",
			"udp_flood_after"					:"Limite de paquets (5-3000)",
			"virus_filter_label"		        :"Filtrage de virus",
			"arp_attack_label"				    :"Prévention d'attaque du type ARP",
			"attack_log_tab_panel"              :"Journal d'attaque du type ARP",
			"attack_log_list_thead"             :"['ID','Temps','Journal-Contenu']"
		},
		"ip_filter":{
			"txt"								:"Filtrage d'IP",
			"ip_filter_panel"					:"Filtrage d'IP",
			"ip_filter_enable_label"			:"Statut",
			"ip_filter_rule_label"				:"Règle de filtrage",
			"deny_r"							:"Refuser l'accès réseau aux appareils (adresse IP) non listés ci-dessous.",
			"permit_r"							:"Permettre l'accès réseau aux appareils (adresse IP) non listés ci-dessous.",
			"ip_filter_list_panel"				:"Réglages Règle de filtrage d'IP",
			"ip_describe_label"					:"Description",
			"ip_status_label"					:"Statut",
			"ip_status_options"					:"['Activer','Désactiver']",
			"ip_rule_label"						:"Règle",
			"ip_rule_options"					:"['Permettre','Refuser']",
			"ip_src_sele_label"					:"Hôte de source",
			"ip_src_sele_options"      			:'["Tous les hôtes","Hôtes spécifiques","Sous-réseau d\'hôte","Segment d\'hôte"]',
			"ip_src_ip_label"                 	:"Adresse IP",
			"ip_src_mask_label"            		:"Masque de sous-réseau",
			"ip_src_start_label"				:"Adresse IP de début",
			"ip_src_end_label"					:"Adresse IP de fin",
			"ip_des_sele_label"                 :"Adresse d'hôte",
			"ip_des_sele_options"               :'["Tous les hôtes","Hôtes spécifiques","Sous-réseau d\'hôte","Segment d\'hôte"]',
			"ip_des_ip_label"                   :"Adresse IP",
			"ip_des_mask_label"                 :"Masque de sous-réseau",
			"ip_des_start_label"				:"Adresse IP de début",
			"ip_des_end_label"               	:"Adresse IP de fin",
			"ip_proto_label"					:"Protocole",
			"ip_port_label"						:"Port",
			"ip_proto_options"					:"['TOUS','TCP','UDP','ICMP']",
			"ip_day_label"						:"Jour",
			"ip_day_btn"						:"TOUS",
			"ip_time_label"						:"Heure",
			"ip_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"ip_filter_tab_panel"				:"Liste de filtrage d'IP",
			"ip_filter_list_thead"				:"['ID','Description','Règle','IP de source','IP de destination','Protocole','Port','Jour','Heure','Modifier']"
		},
		"mac_filter":{
			"txt"								:"Filtrage MAC",
			"mac_filter_panel"					:"Filtrage d'adresse MAC",
			"mac_filter_enable_label"			:"Statut",
			"mac_filter_rule_label"				:"Règle de filtrage",
			"deny_r"							:"Refuser l'accès réseau aux appareils (adresse MAC) non listés ci-dessous.",
			"permit_r"							:"Permettre l'accès réseau aux appareils (adresse MAC) non listés ci-dessous.",
			"mac_filter_list_panel"				:"Réglages Règle de filtrage MAC",
			"mac_describe_label"				:"Description",
			"mac_status_label"					:"Statut",
			"mac_status_options"				:"['Activer','Désactiver']",
			"mac_rule_label"					:"Règle",
			"mac_rule_options"					:"['Permettre','Refuser']",
			"mac_filter_label"					:"Adresse MAC source",
			"mac_day_label"						:"Jour",
			"mac_time_label"					:"Heure",
			"mac_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"mac_filter_tab_panel"				:"Liste de filtrage MAC",
			"mac_filter_list_thead"				:"['ID','Description','Règle','Adresse MAC','Jour','Heure','Modifier']"
		},
		"dns_filter":{
			"txt"								:"Filtrage de domaine",
			"domain_filter_panel"				:"Filtrage de domaine",
			"dns_filter_enable_label"			:"Statut",
			"dns_filter_rule_label"				:"Règle de filtrage",
			"deny_r"							:"Refuser l'accès avec clés DNS non listées ci-dessous.",	
			"permit_r"							:"Permettre l'accès avec clés DNS non listées ci-dessous.",
			"domain_filter_list_panel"			:"Réglages Règle de filtrage de domaine",
			"dns_des_label"						:"Description",
			"dns_status_label"					:"Statut",
			"dns_status_options"				:"['Activer','Désactiver']",
			"dns_rule_label"					:"Règle",
			"dns_rule_options"					:"['Permettre','Refuser']",
			"dns_key_label"						:"Clés DNS",
			"dns_day_label"						:"Jour",
			"dns_time_label"					:"Heure",
			"dns_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"domain_filter_tab_panel"			:"Liste de filtrage de domaine",
			"dns_filter_list_thead"				:"['ID','Description','Règle','Clés DNS','Jour','Heure','Modifier']"		
		}
	},
	"qos":{
		"txt"									:"Contrôle de la passante", 
		"qos":{
			"config_panel"						:"Configuration du contrôle de la passante",
			"qos_enable_label"					:"Statut",
			"qos_rule_label"					:"Règle",
			"qos_rule_label_a"					:"Passante uplink",  
			"qos_rule_label_b"					:"Passante downlink",
			"qos_rule_label_c"					:"(Ko/s) (0 indique aucune limite.)",  
			"qos_rule_label_d"					:"(Ko/s) (0 indique aucune limite.)",

			"qos_set_panel"						:"Réglage de la règle du Contrôle de la bande passante",
			"qos_des_label"						:"Description",
			"qos_status_label"					:"Statut",
			"qos_status_options"				:"['Activer','Désactiver']",
			"qos_sele_label"					:"Hôte",
			"qos_sele_options"					:'["Tous les hôtes","Hôtes spécifiques","Sous-réseau d\'hôte","Segment d\'hôte"]',
			"qos_ip_label"						:"Adresse IP",
			"qos_mask_label"					:"Masque de sous-réseau",
			"qos_ip_start_label"				:"Adresse IP de début",
			"qos_ip_end_label"					:"Adresse IP de fin",
			"qos_min_label"						:"Passante garantie",
			"qos_min_label_a"					:"Passante uplink",
			"qos_min_label_b"					:"Passante downlink",
			"qos_min_label_c"					:"(Ko/s) (0 indique aucune limite.)",
			"qos_min_label_d"					:"(Ko/s) (0 indique aucune limite.)",
			"qos_max_label"						:"Passante limitée",
			"qos_max_label_a"					:"Passante uplink",
			"qos_max_label_b"					:"Passante downlink",
			"qos_max_label_c"					:"(Ko/s) (0 indique aucune limite.)",
			"qos_max_label_d"					:"(Ko/s) (0 indique aucune limite.)",

			"qos_list_panel"					:"Liste de contrôle de la bande passante",
			"qos_rule_list_thead"				:'["ID","Description","Statut","Plage d\'adresse IP",{head:"Passante garantie",con:["Passante uplink","Passante downlink"]},{head:"Passante limitée",con:["Passante uplink","Passante downlink"]},"Modifier"]'
		}
	},
	"ddns":{
		"txt"									:"DNS dynamique",
		"ddns":{
			"txt"								:"DNS dynamique",
			"ddns_panel"						:"DNS dynamique",
			"ddns_enable_label"					:"Statut DDNS",
			"ddns_sp_label"						:"Fournisseur de service",
			"ddns_sp_options"					:"['No-IP','Dyndns']",
			"ddns_sp_after"						:"<a href='http://www.meibu.com/reg.asp'>www.noip.com</a>",
			"ddns_username_label"				:"Nom d'utilisateur",
			"ddns_password_label"				:"Mot de passe",
			"ddns_domain_label"					:"Nom de domaine",
			"ddns_port_label"					:"Port",
			"ddns_info_label"					:"Statut de connexion",
			"ddns_tips_info"					:"Astuce : Lorsque vous vous connectez DDNS avec succès, vous devriez vous déconnecter avant de changer à un autre compte."
		}
	},
	"forward":{
		"txt"									:"Renvoi",
		"virtual":{
			"txt"								:"Serveurs virtuels",
			"vir_server_panel"					:"Réglages de règle de Serveurs virtuels",
			"vir_name_label"					:"Description",
			"vir_ip_label"						:"Adresse IP",
			"vir_proto_label"					:"Protocole",
			"vir_proto_options"					:"['TOUS','TCP','UDP','HTTP','HTTPS','FTP','POP3','SMTP','DNS','TELENT','IPSEC','PPTP','Windows Terminal Client','GuruGuru','H323 VoIP Phone','Soribada']",
			"vir_outport_label"					:"Port externe",
			"vir_inport_label"					:"Port interne",
			"vir_tab_panel"						:"Liste de Serveurs virtuels",
			"virtual_server_list_thead"			:"['ID','Description','Adresse IP','Protocole','Port externe','Port interne','Modifier']"
		}
	},
	"advanced":{
		"txt"									:"Avancé",
		"vpn":{
			"txt"								:"VPN",
			"vpn_panel"							:"Réglages VPN Pass-through",
			"pptp_enable_label"					:"PPTP Pass-through",
			"l2tp_enable_label"					:"L2TP Pass-through",
			"ipsec_enable_label"				:"IPSEC Pass-through"
		},
		"igmp":{
			"txt"								:"IGMP",
			"igmp_panel"						:"IGMP",
			"igmp_enable_label"					:"Statut"
		},
		"dmz":{
			"txt"								:"DMZ",
			"dmz_panel"							:"DMZ",
			"dmz_enable_label"					:"Statut",
			"dmz_ip_label"						:"Adresse IP",

			"super_dmz_panel"					:"Super DMZ",
			"super_dmz_enable_label"			:"Statut",
			"super_dmz_addr_label"				:"Adresse MAC"		
		},
		"portTrigger":{
			"txt"								:"Décl. de port",  //OK
			"port_trigger_panel"				:"Réglages Règle Déclenchement de port",//OK
			"port_select_label"					:"Règle prédéfinie",
			"port_select_options"				:"['--Sélectionner One--','GuruGuru','BuddyBuddy','Enppy','Pruna TCP','Pruna UDP']",
			"app_name_label"					:"Description",
			"trigger_proto_label"				:"Protocole de décl.",// 与770行相同，之前为标出
			"trigger_proto_options"				:"['TCP','UDP']",
			"app_port_label"					:"Port de déclenchement",//OK
			"forward_proto_label"				:"Protocole de renvoi",
			"forward_proto_options"				:"['TCP','UDP']",
			"forward_port_label"				:"Port de renvoi",
		
			"trigger_tab_panel"					:"Liste de déclenchement de port",//OK
			"app_port_list_thead"				:"['ID','Description','Protocole de déclenchement','Port de déclenchement','Protocole de renvoi','Port de renvoi','Modifier']"//OK
		},
		"ftp":{
			"txt"								:"Port privé FTP",
			"ftp_port_panel"					:"Port privé FTP",
			"ftp_enable_label"					:"Statut",
			"ftp_port_label"					:"Port"
		},
		"upnp":{
			"txt"								:"UPnP",
			"upnp_panel"						:"Réglage UPnP",
			"upnp_enable_label"					:"Statut"
		},
		"binds":{
			"txt"								:"Liaison IP & MAC",
			"binds_set_panel"					:"Liaison IP & MAC",
			"binds_rule_label"					:"Règle de filtrage",
			"deny_r"							:"Permettre l'accès internet aux appareils qui ne sont pas listés.",
			"allow_r"							:"Refuser l'accès internet aux appareils qui ne sont pas listés.",

			"contr_binds_panel"					:"Réglages Règle de liaison IP & MAC",
			"binds_des_label"					:"Description",
			"binds_ip_label"					:"Adresse IP",
			"binds_mac_label"					:"Adresse MAC",
			"binds_port_label"					:"Interface",
			"binds_port_options"				:"['LAN','WAN']",
			"binds_tab_panel"					:"Liste de liaison IP & MAC",
			"binds_list_thead"					:"['ID','Description','Adresse IP','Adresse MAC','Interface','Modifier']"
		},
		"arp_list":{
			"txt"								:"Liste ARP",
			"arp_list_panel"					:"Liste ARP",
			"arp_list_thead"					:"['ID','Adresse IP','Adresse MAC']"
		},
		"routing":{
			"txt"								:"Routage statique",
			"routing_panel"						:"Réglage de règle de Routage statique",
			"route_des_label"					:"Description",
			"route_type_label"					:"Type",
			"route_type_options"				:"['NET','HOTE']",
			"ip_value_label"					:"IP de la destination",
			"mask_value_label"					:"Masque de sous-réseau",
			"gateway_value_label"				:"Passerelle par défaut",
			"route_tab_panel"					:"Liste de route statique",
			"static_routing_list_thead"			:"['ID','Description','Type','IP de la destination','Masque de sous-réseau','Passerelle par défaut','Modifier']"
		},
		"interface_mode":{
			"txt"								:"Réglage de port",
			"mode_panel"						:"Réglage de port WAN",
			"wan_label"							:"Port WAN",
			"wan_options"						:"['Auto','10M Duplex','10M Half-Duplex','100M Duplex','100M Half-Duplex']"
		},
		"wakeup":{
			"txt"								:"WOL",
			"wakeup_panel"						:"WOL",
			"wakeup_mac_label"					:"Adresse MAC"
		}
	},
	"misc":{
		"txt"									:"Outils du système",
		"update":{
			"txt"								:"Firmware", 
			"update_panel"						:"Mise à jour du firmware",
			"version_label"						:"Version actuelle",
			"file_label"						:"Fichier de mise à jour",
			"updata_file_label"                 :"Fichier de mise à jour",
			"load_panel"						:"Mise à jour du firmware",
			"tip_update_info"					:"Astuce : N'éteignez pas le routeur pendant l'opération de mise à jour du firmware."
		},
		"sys_time":{
			"txt"								:"Réglages de l’heure",
			"time_set_panel"					:"Réglages de l’heure",
			"time_now_label"					:"Heure actuelle",
			"time_type_label"					:"Type",
			"ntp_r"								:"NTP",
			"hand_r"							:"Manuel",
			"time_date_label"					:"Date",
			"time_date_after"					:"Année",
			"time_date_after2"					:"Mois",
			"time_date_after3"					:"Jour",
			"time_time_label"					:"Heure",
			"time_time_after"					:"Heure",
			"time_time_after2"					:"Minute",
			"time_time_after3"					:"Seconde",
			"timezone_label"					:"GMT",
			"timezone_options"					:"['(GMT-12:00) Eniwetok, Kwajalein','(GMT-11:00) Midway Is., Samoa','(GMT-10:00) Hawaii','(GMT-09:00) Alaska','(GMT-08:00) Heure pacifique (US Canada); Los Angeles','(GMT-07:00) Mountain Time (US Canada); Arizona','(GMT-06:00) Heure centrale (US Canada); Mexico City','(GMT-05:00) Heure de l\\'Est (US Canada); Bogota, New York, Lima','(GMT-04:00) Heure atlantiqueTime(Canada); Caracas, La Pax','(GMT-03:00) Brasilia, Buenos Aires, Georgetown, Greenland','(GMT-02:00) Mid-Atlantic','(GMT-01:00) Cape Verde Is., Azores','(GMT) Heure Greenwich; Dublin, Edinbourg, Londre, Lisbone','(GMT+1:00) Amsterdam, Berlin, Rome, Stockholm, Paris','(GMT+2:00) Cairo, Athène, Istanboul, Minsk, Jérusalem','(GMT+3:00) Bagdad, Koweit, Riyadh, Moscou, St.Petersburg','(GMT+4:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan','(GMT+5:00) Ekaterinburg, Islamabad, Karachi, Tashkent','(GMT+6:00) Almaty, Novosibirsk, Astana, Dhaka','(GMT+7:00) Bangkok, Jakarta, Hanoi','(GMT+8:00) Beijing, Hong Kong, Taipei, Singapour','(GMT+9:00) Tokyo, Osaka, Sapporo, Séoul, Yakutsk','(GMT+10:00) Brisbane, Guam, Canberra, Melbourne, Sydney','(GMT+11:00) Magadan, Solomon Is., New Caledonia','(GMT+12:00) Fiji, Marshall Is., Auckland, Wellington','(GMT+13:00) Nukualofa']",
			"ntp_panel"							:"Serveur NTP",
			"time_server_label"					:"IP/Nom du Serveur NTP",
			"time_server_after"					:"(Optionnel)"
		},
		"diagnostic":{
			"txt"								:"Outils de diagnostic", 
			"diagnostic_panel"					:"Outils de diagnostic",
			"tools_type_label"						:"Outil de diagnostic",
			"ping_r"							:"Ping",
			"trac_r"							:"Tracert",
			"tools_ip_url_label"						:"IP/Nom de domaine",
			"result_head_info"					:"Résultat du diagnostique",
			"result_info"						:" "
		},
		"remote":{
			"txt"								:"Gestion à distance",
			"remote_panel"						:"Gestion à distance",	
			"remote_enable_label"				:"Statut",
			"remote_port_label"					:"Port"	
		},
		"passwd":{
			"txt"								:"Mot de passe",
			"change_pwd_panel"					:"Mot de passe",
			"old_user_label"					:"Nom d'utilisateur",
			"old_pwd_label"						:"Mot de passe actuel",
			"old_pwd_after"					    :"(Veuillez entrer des caractères: a-z,A-Z,0-9.)",
			"new_user_label"					:"Nouveau nom d'utilisateur",
			"new_user_after"					:"(Veuillez entrer des caractères: a-z,A-Z,0-9.)",
			"new_pwd_label"						:"Nouveau mot de passe",
			"new_pwd_after"						:"(Veuillez entrer des caractères: a-z,A-Z,0-9.)",
			"new_pwd_confirm_label"				:"Confirmer mot de passe",
			"new_pwd_confirm_after"				:"(Veuillez entrer des caractères: a-z,A-Z,0-9.)"
		},
		"backup":{
			"txt"								:"Sauv. & Rest.", //OK
			"backup_panel"						:"Sauvegarder",//OK
			
			"restore_panel"						:"Restaurer",//OK
			"tip_restore_info"					:"Astuce : L'opération de restauration prendra au moins 1 minutes. Pendant l'opération, n'éteignez pas l'alimentation et n'appuyez pas sur le bouton Défaut du routeur, pour éviter les dommages.",
			"file_label"						:"Sauvegarder fichier",//OK
			"file_up_label"						:"Sauvegarder fichier",//OK
			"load_panel"						:"Restaurer"//OK		
		},
		"sys_log":{
			"txt"								:"Journal du système",
			"sys_log_panel"						:"Journal du système",
			"sys_log_thead"						:"['ID','Temps','Journal-Contenu']"
		},
		"statistics":{
			"txt"								:"Statistiques",
			"status_sys_panel"					:"Statut du routeur",
			"run_time_label"					:"Disponibilité du système",
			"cpu_label"							:"Utilisation CPU",
			"mem_label"							:"Utilisation mémoire",

			"statistics_panel"					:"Statistiques de trafic",
			"statistics_list_thead"				:"['Type','Paquets envoyés','Paquets reçus','Données envoyées (Koctets)','Données reçues (Koctets)']"
		},
		"default":{
			"txt"								:"Défauts d'usine",
			"tip_default_info"					:"Astuce : Tous les réglages de configuration seront restaurés aux valeurs par défaut.",
			"default_panel"						:"Défauts d'usine",
			"load_panel"						:"Défauts d'usine"
		},
		"reboot":{
			"txt"								:"Redémarrage",
			"tip_reboot_info"					:"Astuce : Le réseau sera déconnecté pendant quelques instant pendant le redémarrage.",
			"reboot_panel"						:"Redémarrage du système"
		}
	}
};



//Extra part（to be translated）           ：“Bienvenue au Routeur sans fil N-netis”
//Extra part（to be translated）           ："Sélectionner la langue"
//Extra part（to be translated）           ："Configuration rapide"
//Extra part（to be translated）           ："Type de connexion Internet"
//Extra part（to be translated）           ："Configuration sans fil"
//Extra part（to be translated）           ："Aller à Enregistrer..."
//Extra part（to be translated）           ："Nom d'utilisateur ou mot de passe incorrect"
//Extra part（to be translated）           ："Conflit d'adresse IP avec WAN! "Veuillez changer l'adresse IP LAN du routeur."
