//Language = {};
Language.TC = {
	"common":{
		"all"									:"全部",
		"wan_lan_err"							:"IP 位址與 WAN 位址發生衝突！ 請變更路由器的 LAN IP 位址。",
		"channel"                 				:"頻道",
    	"after_map_a"             				:"(請輸入 10 個十六進位字元 (a-f、A-F、0-9 的任何組合。))",
    	"after_map_b"             				:'(請輸入 5 個 ASCII 字元 (a-z、A-Z、0-9 的任何組合。))',
    	"after_map_c"             				:"(請輸入 26 個十六進位字元 (a-f、A-F、0-9 的任何組合。))",
    	"after_map_d"             				:'(請輸入 13 個 ASCII 字元 (a-z、A-Z、0-9 的任何組合。))',
    	"after_map_e"             				:"(請輸入 64 個十六進位字元 (a-f、A-F、0-9 的任何組合。))",
    	"after_map_f"             				:'(請輸入 8 至 63 個 ASCII 字元 (a-z、A-Z、0-9 的任何組合。))',
    	"after_map_g"             				:'秒(60-86400)',
		"auto_type"               				:"自動",
		"welcome_title"           				:"歡迎使用 netis 無線寬頻分享器",
		"advanced_title"          				:"netis 無線寬頻分享器",  
		"DDNS_ERR_FAILED"         				:"失敗",
		"bound"                   				:"已綁定",
		"unbound"                 				:"未綁定",
		"bind"                    				:"綁定",
		"timeout_err"							:"操作失敗，請重新嘗試。",
		"use_tip"								:"時間",
		"restoring"								:"正在還原系統設定...",
		"defaulting"							:"正在恢復原廠預設值...",
		"rebooting"								:"正在重新開機...",
		"days"									:"天",
		"hours"									:"時",
		"minutes"								:"分",
		"seconds"								:"秒",
		"search"								:"正在掃描...",
		"wel_key_err"							:"請輸入 8 至 63 個字元 (特殊字元【\'\"\\】除外)).",
		"wel_sele_lan"							:"選擇語言",
		"wel_tips"								:"快速設定",
		"wel_inter_tip"							:"連線方式",
		"wel_wirel_tip"							:"無線網路設定",
		"wel_pwd_tip"							:"(請輸入8至63個英數字。) ",
		"wel_status_label"						:"加密 :",

		"wel_static_tip"						:"如果您的 ISP 提供固定 IP 位址資訊，請選擇固定 IP 選項。",
		"wel_dhcp_tip"							:"如果您的 ISP 釋出使用 DHCP 伺服器的自動 IP 位址，請選擇 DHCP 選項。",
		"wel_pppoe_tip"							:"如果您的 ISP 提供 PPPoE(ADSL) 連線，請選擇 PPPoE 選項。",
		"bind_all"								:"全部繫結",
		"advance"								:"進階",
		"text_after"							:"封包/秒",
		"wps_off"								:"停用 WPS",
		"wps_on"								:"啟用 WPS",
		"def_pin"								:"恢復PIN碼",
		"new_pin"								:"更新PIN碼",
		"info"									:"資訊",
		"connect"								:"進行連線",
		"disconnect"          					:"中斷連線",
		"connected"                             :"連線成功",
        "disconnected"                          :"連線中斷",
		"refresh"                     			:"重新整理",
		"open"									:"PBC設定",	
		"link"									:"進行連線",
		"save_reboot"							:"儲存並重新開機",	
		"add"									:"新增",
		"del"									:"刪除",
		"del_all"								:"全部刪除",
		"delAll"								:"全部刪除",
		"mod"									:"修改",
		"reboot"								:"重新開機",
		"back"									:"返回",
		"save"									:"儲存",
		"keep_all"								:"全部保留",
		"wakeup"								:"喚醒",
		"upgrade"								:"升級",
		"backup"								:"備份",
		"recover"                               :"還原",
		"restore"								:"恢復原廠預設值",
		"help_more_btn"							:"更多...",
		"ap_get"								:"掃描AP",
		"auto_check"							:"自動偵測",
		"help_more_null"						:"",
		"on"									:"啟用",
		"off"									:"停用",
		"forbid_s"                              :"拒絕",
		"allow_s"                               :"允許",
		"df_mac"								:"預設 MAC",
		"clone_mac"								:"MAC 複製",
        "start"                                 :"開始",
        "end"								    :"結束",
        "browse"                                :"瀏覽",
        "current"                               :"MAC 位址複製",
        "device"                                :"還原預設 MAC",
        "set_reserve"                           :"保留",
        "cancel_reserve"                        :"取消",
        "reserved"                              :"已保留",
        "static"                                :"固定IP",
        "dynamic"                               :"DHCP",
		"yes"									:"是",
		"no"									:"否",
        "other"                                 :"其他",
		"total"									:"總計",
        "online"                                :"線上",
        "offline"                               :"離線",
		"week_0"								:"星期日",
		"week_1"								:"星期一", 
		"week_2"								:"星期二",
		"week_3"								:"星期三",
		"week_4"								:"星期四",
		"week_5"								:"星期五",
		"week_6"								:"星期六",
		"everday"								:"每天",
		"all_day"								:"整日",
//		"Sun"								    :"星期日",
//		"Mon"								    :"星期一", 
//		"Tue"								    :"星期二",
//		"Wed"								    :"星期三",
//		"Thu"								    :"星期四",
//		"Fri"								    :"星期五",
//		"Sat"								    :"星期六",
//		"week"									:"星期",
		"check_all_label"						:"全部選擇",
		"max_size_label_a"						:" 目前第 ",
		"max_size_label_b"						:"&nbsp;頁 ",
		"size_label"							:"每頁顯示規則數",
		"size_set_btn"							:"確定",
		"load_tip"								:"正在升級中...",
		"lock_save"								:"儲存中...",
		"lock_delete"							:"刪除中...",
		"lock_add"								:"新增中...",
		"unlock_save"							:"成功儲存！",
		"unlock_delete"							:"成功刪除！",
		"unlock_add"							:"成功新增！",
		"unlock_err"							:"無法識別的傳回值！ 請重新嘗試。",
		"unlock_error"							:"操作失敗！",
		"time_err"								:"最大閒置時間應設為 1 至 30 分鐘。",
		"dhcp_mtu_err"							:"MTU 大小應該介於 576 至 1500 位元組。 請重新嘗試。",
		"pppoe_mtu_err"							:"MTU 大小應該介於 576 至 1492 位元組。 請重新嘗試。",
		"static_mtu_err"						:"MTU 大小應該介於 576 至 1500 位元組。 請重新嘗試。",
		"l2tp_mtu_err"             				:"MTU 大小應該介於 576 至 1460 位元組。 請重新嘗試。",
		"pptp_mtu_err"             				:"MTU 大小應該介於 576 至 1420 位元組。 請重新嘗試。",
		"beacon_err"							:"Becon間隔值應該介於 20 至 1000。",
		"rts_err"								:"RTS 閾值應該介於 256 至 2347。",
		"frag_err"								:"分片閥值應該介於 256 至 2346。",
		"cmp_port_err"							:"結束通訊埠不可小於起始通訊埠。 請重新輸入。",
		"cmp_ip_err"							:"結束IP位址不可小於起始IP位址。 請重新輸入。",
		"mask_err"								:"子網路遮罩無效。 請輸入其他設定值。",
		"ip_err"								:"IP 位址無效。 請輸入其他設定值。",
		"key_time_err"							:"金鑰更新間隔介於 60 至 86400 秒。 請重新輸入。",
		"addr_err"								:"DHCP 位址範圍不應超過最大限制。 請重新輸入。",
		"lan_ip_err"							:"DHCP 位址範圍應設為與 LAN IP 位址相同的網路區段。 請重新輸入。",
		"lan_addr_err"							:"DHCP 位址範圍不可包含LAN IP 位址。 請重新輸入。",
		"item_err"								:"無法新增更多項目。",
		"ip_used_err"							:"IP 位址已用於其他項目。 請嘗試其他位址。",
		"qos_band_err"							:"頻寬應設為介於 0 至 12799。請重新輸入。",
		"qos_up_err"							:"受限制上行頻寬不可小於保證上行頻寬。 請重新輸入。",
		"qos_down_err"							:"受限制下行頻寬不可小於保證下行頻寬。 請重新輸入。",	
		"key_len_err"							:"密碼/金鑰長度應該為：",
		"ddns_start"							:"連線中...",
		"ddns_failed"							:"驗證失敗。 請檢查帳戶資訊並重新嘗試。",
		"ddns_ok"								:"您已經成功連線！ 網域名稱為:",
		"oray_user_err"							:"請輸入 5 至 16 個字元，可以使用 a-z、A-Z、0-9、-(連字號) 的任何組合。 不允許只輸入數字或 -(連字號)。",
		"oray_pass_err"							:"請輸入 6 至 16 個字元，可以使用 a-z、A-Z、0-9、特殊字元的任何組合.",
		"meibu_user_err"						:"請輸入 1 至 26 個字元，可以使用 a-z、A-Z、0-9 的任何組合。不允許輸入中文字或無效字元。",
		"meibu_pass_err"						:"請輸入至少 4 個字元，可以使用 a-z、A-Z、0-9 的任何組合。",
		"end_time_err"                          :"錯誤的時間格式。 請重新嘗試。",
		"reserved_keep"                         :"無效的操作！ 此位址已經保留。",
		"reserved_cancel"                       :"無效的操作！ 此位址尚未保留。",
		password_null							:"密碼不能是空值。 請重新輸入。",
		password_ival							:"僅限使用英文字母或數字作為密碼。 請重新輸入！",
		password_length_err						:"密碼不可少於 32 個字元。 請重新輸入。",
		password_err							:"您輸入的新密碼不相符。 請重新輸入。",
		mtu_err									:"不允許使用空值金鑰。 請重新輸入完整數字。",
		mtu_pppoe_null							:"不允許使用空值金鑰。 請重新輸入完整數字。",
		pppoe_text_err							: '不允許使用空值金鑰及 \\\'“”‘’等無效字元。 ',
		mtu_ival								:"MTU 大小應該介於 576 至 [1] 位元組。 請重新嘗試。",
		ip_addr_null							:"IP 位址不可設為空白或 0.0.0.0。 請重新輸入。",
		ip_addr_ival							:"使用無效字元的無效 IP 位址。 請輸入其他設定值。",
		ip_addr_err								:"無效的 IP 位址。 請輸入其他設定值。",
		mask_addr_err							:"子網路遮罩無效。 請輸入其他設定值。",
		mac_addr_err							:"MAC 位址無效。 請輸入其他設定值。",
		gw_err									:"預設閘道應設為與 WAN IP 位址相同的網路區段。 請重新輸入。",
		gw_errs									:"無效的預設閘道。 請輸入其他設定值。",
		port_null								:"請輸入通訊埠。",
		port_err								:"通訊埠應設為 1 至 65535。請重新輸入。 ",
		int_number_err							:"無效的數字！ 請輸入其他設定值。",
		string_null								:" 不允許使用空值金鑰 \n 及無法識別的特殊字元。",
		string_err								:'不允許使用特殊字元 \'"\\ 或空格。',
		string_null_err							:'不允許使用特殊字元 \'"\\。',
		route_ip_err							:"IP 位址及子網路遮罩不在相同網路上。 請輸入其他設定值。",
		auto_disconnect_time_err				:"最大閒置時間應設為 1 至 30 分鐘。",
		dhcp_reserve_err						:"IP 位址須在DHCP 位址範圍。 請輸入其他設定值。",
		dhcp_reserve_lan_ip						:"IP 位址不可與LAN IP 位址相同。 請輸入其他設定值。 ",
		wireless_key_length						:"密碼/金鑰長度應該為 :[1]。",
		wireless_key_hex_err					:"密碼應該全部使用十六進位字元。",
		qos_max_up_err							:"受限制上行頻寬不可小於保證上行頻寬。 請重新輸入。",
		qos_max_down_err						:"受限制下行頻寬不可小於保證下行頻寬。 請重新輸入。",
		qos_bandwidth_err						:"頻寬應設為介於 0 至 12799。請重新輸入。",
		az09_string_err							:"請輸入字元：a-z、A-Z、0-9。",
		string_url_err							:"請輸入字元：a-z、A-Z、0-9、-。",
		string_hex_err							:"請輸入字元：a-f、A-F、0-9。",
//		wireless_key_length_info				:'(請輸入 [1] 個字元 (特殊字元【\'\"\\】除外))',
	  	wireless_key_length_info1				:"(請輸入 [1] 個十六進位字元 (a-f、A-F、0-9))",
	 	Src_password_err						:"目前密碼不正確。 請重新輸入。",
	  	save_only_need_reboot					:"現在設定已經變更，不過只有在重新開機後才會生效。 建議您先完成其他設定，最後再重新啟動無線寬頻分享器。",
		pin_number_err							:"請輸入 8 個數字的 PIN 碼。",
		item_exist								:"使用相同設定的項目已存在。 請嘗試其他設定值。",
		"rule_err"								:"不允許無效的字元及空格。",
		"domain_err"							:"無效的網域名稱格式。 請嘗試其他設定值。",
		"dns_null_err"							:"無效的 DNS 伺服器位址。 請設定至少一個 DNS 伺服器。",
		"segment_err"							:"IP 位址不可以是網路IP 位址。 請嘗試其他設定值。",
		"Bcast_err"								:"IP 位址不可以是廣播位址。 請嘗試其他設定值。",
		"segment_len_err"						:"IP 位址不在目前網路區段上。 請嘗試其他設定值。",
		"reserver_err"							:"欲保留的 IP 位址不在 DHCP 位址範圍內。 請嘗試其他設定值。",
		"pass_err"								:"密碼可以使用 a-z、A-Z、0-9 或特殊字元的任何組合。 請重新嘗試。",
		"year_err"								:"錯誤的年份格式。 請輸入其他設定值 (2008~2035)。",
		"mon_err"								:"錯誤的月份格式。 請輸入其他設定值 (1~12)。",
		"day31_err"								:"錯誤的日期格式。 請輸入其他設定值 (1~31)。",
		"day30_err"								:"錯誤的日期格式。 請輸入其他設定值 (1~30)。",
		"day29_err"								:"錯誤的日期格式。 請輸入其他設定值 (1~29)。",
		"day28_err"								:"錯誤的日期格式。 請輸入其他設定值 (1~28)。",
		"hour_err"								:"錯誤的小時格式。 請輸入其他設定值 (0~23)。",
		"min_sec_err"							:"錯誤的分鐘或秒鐘格式。 請輸入其他設定值 (0~59)。",
		"page_err"								:"錯誤的頁面格式。 請輸入其他設定值 (1~100)。",

		"DDNS_ERR_CLOSE"						:"已關閉。",
		"DDNS_ERR_CONNECTING"					:"連線中...",
		"DDNS_ERR_INUPT"						:"請同時輸入使用者名稱及密碼。",
		"DDNS_ERR_GET_NO_IP"					:"無法取得伺服器位址。",
		"DDNS_ERR_SYSTEM"						:"系統資源受限制。",
		"DDNS_ERR_USER"							:"使用者名稱或密碼無效。",
		"DDNS_ERR_OK"							:"成功更新！",
		"DDNS_ERR_SERVER"						:"DDNS 伺服器錯誤。",
		"ST"									:"標準服務,  ",
		"PR"									:"專業服務,",

		"del_tip"								:"您是否要刪除全部？",
		"del_one_tip"							:"您是否要刪除選取項目？",
		"disconnect_tip"						:"您是否要中斷網路？",
		"connect_tip"							:"您是否要連接網路？",
		"default_tip"							:"您是否要重設為出廠預設值？",
		"reboot_tip"							:"您是否要重新啟動無線寬頻分享器？",
		"reboot_web_tip"						:"無線寬頻分享器將會在您變更連接埠後重新啟動。 您是否要繼續？",
		"backup_tip"							:"您是否要還原設定？",
		"del_reserve_err"						:"無法取消位址保留規則。",
		"ip_occupy_err"							:"IP 位址已存在。 請嘗試其他設定值。",
		"mac_occupy_err"						:"MAC 位址已存在。 請嘗試其他設定值。",
		"port_occupy_err"						:"通訊埠已存在。 請嘗試其他設定值。",
		"port_len_err"							:"通訊埠的數值範圍應該相同，例如：外部通訊埠範圍 1-4，內部通訊埠範圍 6-9。",
		"update_err"							:"未選取升級檔案。",
		"update_faild"							:"韌體升級失敗。",
		"backup_err"							:"未選取備份檔案。",
		"backup_faild"							:"備份失敗。",
		"ip_len_err"							:"IP 位址不在範圍內。 請嘗試其他設定值。",
		"add_item_err"							:"使用相同設定的項目已存在。",
		"_default"								:"無效的輸入。"
	},
	"status":{
		"txt"									:"系統狀態",
		"status":{
			"txt"								:"統計資訊",
			
			"status_l2tp_panel"					:"L2TP",
			"l2tp_ip_label"						:"IP 位址",
			"l2tp_mask_label"					:"子網路遮罩",
			"l2tp_gw_label"						:"預設閘道",
			"status_pptp_panel"					:"PPTP",
			"pptp_ip_label"						:"IP 位址",
			"pptp_mask_label"					:"子網路遮罩",
			"pptp_gw_label"						:"預設閘道",
			"second_ip_label"					:"次要IP 位址",
			"second_mask_label"					:"次要子網路遮罩",
			
			"status_wan_panel"					:"網際網路(WAN)",
			"conntype_label"					:"連線類型",
			"mac_addr_label"					:"MAC 位址",
			"ip_label"							:"IP 位址",
			"mask_label"						:"子網路遮罩",
			"gw_label"							:"預設閘道",
			"dns_a_label"						:"主要 DNS伺服器",
			"dns_b_label"						:"次要 DNS伺服器",
			"con_time_label"					:"連線時間",
			"connected_label"					:"連線狀態",
			"status_lan_panel"					:"區域網路(LAN)",
			"lan_mac_label"						:"MAC 位址",
			"lan_ip_label"						:"IP 位址",
			"lan_mask_label"					:"子網路遮罩",
			"dhcp_enable_label"					:"DHCP 伺服器",
			"status_wireless_panel"				:"無線網路",
			"wl_enable_label"					:"無線網路狀態",
			"ssid_label"						:"無線網路名稱(SSID)",
			"net_mode_label"					:"無線網路電波模式",
			"sec_mode_label"					:"驗證類型",
			"channel_label"						:"頻道",
			"wl_mac_label"						:"MAC 位址",
			"wps_enable_label"					:"WPS 狀態"
		}
	},
	"network":{
		"txt"									:"網路設定",
		"wan":{
			"txt"								:"網際網路(WAN)",
			"mode_panel"						:"WAN 連線方式",
			"access_mode_label"					:"WAN 連線類型",
			"wire_r"							:"有線網路",
			"wireless_r"						:"無線網路",

			"wireless_config_panel"				:"無線網路設定",
			"repeater_ssid_label"				:"無線網路名稱(SSID)",
			"channel_label"						:"頻道",
			"channel_options"					:"['自動','頻道 1 ','頻道 2 ','頻道 3 ','頻道 4 ','頻道 5 ','頻道 6 ','頻道 7 ','頻道 8 ','頻道 9 ','頻道 10','頻道 11']",
			"rp_sec_mode_label"					:"加密類型",
			"rp_sec_mode_options"				:"['不加密','WEP','WPA-PSK','WPA2-PSK']",

			"wep_panel"							:"WEP",
			"rp_key_size_label"					:"金鑰長度",
			"rp_key_type_label"					:"加密模式",
			"rp_key_mode_wep_label"				:"金鑰格式",
			"rp_key_mode_wpa_label"				:"金鑰格式",
			"rp_key_wep_label"					:"無線金鑰(密碼)",
			"rp_key_wpa_label"					:"無線金鑰(密碼)",
			"64_r"								:"64 位元",
			"128_r"								:"128 位元",
			"hex_r"								:"十六進位",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",

			"wan_set_panel"						:"網路連線設定",
			"conntype_label"					:"WAN 連線類型",
			"conntype_options"					:"['DHCP(Cable)','固定 IP','PPPoE','Russia PPPoE','Unifi PPPoE','Maxis PPPoE','PPTP/Russia PPTP','L2TP/Russia L2TP']",
			"conntype_after"					:"LAN 1 僅適用於 IPTV",

			"pppoe_username_label"				:"使用者名稱",
			"pppoe_pwd_label"					:"密碼",
			"l2tp_username_label"				:"使用者名稱",
			"l2tp_pwd_label"					:"密碼",
			"l2tp_server_label"					:"伺服器 IP 位址/名稱",
			"l2tp_type_label"					:"連線類型",
			"l2tp_ip_label"						:"IP 位址",
			"l2tp_mask_label"					:"子網路遮罩",
			"l2tp_gw_label"						:"預設閘道",

			"pptp_username_label"				:"使用者名稱",
			"pptp_pwd_label"					:"密碼",
			"pptp_server_label"					:"伺服器 IP 位址/名稱",
			"pptp_type_label"					:"連線類型",
			"pptp_ip_label"						:"IP 位址",
			"pptp_mask_label"					:"子網路遮罩",
			"pptp_gw_label"						:"預設閘道",

			"pppoe_service_name_label"			:"伺服器名稱",
			"pppoe_service_name_after"			:"(選填)",
			"pppoe_ac_name_label"				:"PPPoE AC 名稱",
			"pppoe_ac_name_after"				:"(選填)",
			"pppoe_mtu_label"					:"MTU 大小",
			"pppoe_mtu_after"					:"(預設為 1480，如無特殊需求請勿變更。)",
			"dns_a_label"						:"主要 DNS伺服器",
			"dns_a_after"						:"(選填)",	
			"dns_b_label"						:"次要 DNS伺服器",
			"dns_b_after"						:"(選填)",
			"auto_r"							:"自動連線",
			"time_r"							:"隨需連線、當網路閒置 # 分鐘後自動斷線 (0表示不限制)",
			"hand_r"							:"手動連線",
			"dhcp_mtu_label"					:"MTU 大小",
			"dhcp_mtu_after"					:"(預設為 1500，如無特殊需求請勿變更。)",
			"wan_ip_label"						:"WAN IP 位址",
			"wan_mask_label"					:"子網路遮罩",
			"wan_gw_label"						:"預設閘道",
			"mac_addr_label"					:"MAC 位址",
			"static_mtu_label"					:"MTU 大小",
			"static_mtu_after"					:"(預設為 1500，如無特殊需求請勿變更。)",
			"l2tp_mtu_label"					:"MTU 大小",
			"l2tp_mtu_after"					:"(預設為 1460，如無特殊需求請勿變更。)",
			"pptp_mtu_label"					:"MTU 大小",
			"pptp_mtu_after"					:"(預設為 1420，如無特殊需求請勿變更。)",

			"second_in_panel"					:"次要連接",
			"second_in_type_label"				:"連線類型",
			"dy_r"								:"DHCP",
			"st_r"								:"固定 IP",

			"ap_get_thead"						:"['ID','網路名稱','MAC 位址','頻道 (無線模式)','無線類型','加密類型','訊號強度','連線']"
		},
		"lan":{
			"txt"								:"區域網路(LAN)",
			"lan_set_panel"						:"區域網路(LAN)",
			"lan_ip_label"						:"IP 位址",
			"lan_mask_label"					:"子網路遮罩",
			"servie_panel"						:"DHCP 伺服器",
			"dhcp_enable_label"					:"DHCP 運作狀態",
			"dhcp_start_ip_label"				:"起始 IP 位址",
			"dhcp_end_ip_label"					:"結束 IP 位址",

			"dhcp_list_panel"					:"DHCP 使用者列表",
			"dhcp_client_list_thead"			:"['ID','IP 位址','MAC 位址','主機名稱','已保留','狀態','操作']",
			"load_panel"						:"重新開機無線寬頻分享器"
		},
		"iptv":{
			"txt"								:"IPTV",
			"iptv_set_panel"					:"IPTV模式",
			"iptv_mode_label"					:"IPTV模式",
			"iptv_mode_options"					:"['自動','橋接','802.1Q 標籤 VLAN']",
			"iptv_port_label"					:"IPTV 連接埠",
			"iptv_port_options"					:"['LAN1','LAN1 & LAN2']",
			"vlan_set_panel"					:"VLAN設定",
			"vlan_tag_enable_label"				:"網際網路802.1Q 標籤",
			"vlan_id_inter_label"				:"網際網路VLAN ID",
			"vlan_pri_inter_label"				:"VLAN優先順序",
			"vlan_pri_inter_options"			:"[0,1,2,3,4,5,6,7]",
			
			"vlan_id_iptv_label"				:"IPTV VLAN ID",
			"vlan_pri_iptv_label"				:"VLAN優先順序",
			"vlan_pri_iptv_options"				:"[0,1,2,3,4,5,6,7]",

			"mvlan_id_iptv_label"				:"IPTV多重VLAN ID",
			"mvlan_pri_iptv_label"				:"VLAN優先順序",
			"mvlan_pri_iptv_options"			:"[0,1,2,3,4,5,6,7]",

			"vlan_id_phone_label"				:"網路電話VLAN ID",
			"vlan_pri_phone_label"				:"VLAN優先順序",
			"vlan_pri_phone_options"			:"[0,1,2,3,4,5,6,7]",

			"port_set_panel"					:"連接埠設定",
			"iptv_lan1_mode_label"				:"LAN1 連接埠模式",
			"iptv_lan1_mode_options"			:"['網際網路','IPTV','網路電話']",
			"iptv_lan2_mode_label"				:"LAN2 連接埠模式",
			"iptv_lan2_mode_options"			:"['網際網路','IPTV','網路電話']",
			"iptv_lan3_mode_label"				:"LAN3 連接埠模式",
			"iptv_lan3_mode_options"			:"['網際網路','IPTV','網路電話']",
			"iptv_lan4_mode_label"				:"LAN4 連接埠模式",
			"iptv_lan4_mode_options"			:"['網際網路','IPTV','網路電話']"
		},
		"address_reservation":{
			"txt"								:"IP 位址保留",
			"reservation_panel"					:"IP 位址保留",
			"reserve_des_label"					:"規則名稱",
			"reserve_ip_label"					:"IP 位址",
			"reserve_mac_label"					:"MAC 位址",

			"reservation_list_panel"			:"IP 位址保留列表",
			"reservation_list_thead"			:"['ID','規則名稱','IP 位址','MAC 位址','修改']"
		},
		"opmode":{
			"txt"                               :"工作模式",
			"opmode_panel"                      :"工作模式",
			"access_mode_label"                 :"模式",
			"router_r"                          :"路由",
			"bridge_r"                          :"橋接"
		}
	},
	"wireless":{
		"txt"									:"無線網路",
		"base":{
			"txt"								:"無線網路設定",
			"base_panel"						:"無線網路設定",	
			"wl_enable_label"					:"無線運作狀態",
			"ssid_label"						:"無線網路名稱(SSID)",
			"wl_stand_label"					:"無線模式",
			"wl_stand_options"					:"['802.11b','802.11g','802.11n','802.11b+g','802.11g+n','802.11b+g+n']",
			"net_mode_label"					:"無線類型",
			"net_mode_options"					:"['AP','Repeater','AP+WDS','WDS','Client']",
		//	"wl_config_label"					:"組態",
			"cl_config_label"					:"組態",
			"rp_config_label"					:"組態",
			"auto_r"							:"自動",
			"hand_r"							:"手動",
			"repeater_ssid_label"				:"遠端 AP 名稱",
			"repeater_mac_label"				:"遠端 AP MAC 位址",
			"wl_mac_label"						:"MAC 位址",
			"ssid_broad_label"					:"SSID 廣播",
			"channel_width_label"				:"頻道寬度",
			"20_r"								:"20MHz",
			"40_r"								:"40MHz",
			"channel_bind_label"				:"頻道綁定",
			"down_r"							:"下層",
			"up_r"								:"上層",
		//"repeater_ssid_label"				:"目標網路名稱",
			"region_label"						:"地區",
			"region_options"					:"['US','EU','MKK','IC']",
			"channel_label"						:"頻道",
			"channel_options"					:"['自動','頻道 1 ','頻道 2 ','頻道 3 ','頻道 4 ','頻道 5 ','頻道 6 ','頻道 7 ','頻道 8 ','頻道 9 ','頻道 10','頻道 11']",

			"ap_security_panel"					:"AP 加密設定",
			"tips_info"							:"為了提供最佳的無線網路安全性，強烈建議您將 WPA2-PSK 設為加密類型，以及將 AES 或 TKIP & AES 設為加密模式。",
			"sec_mode_label"					:"加密類型",
			"sec_mode_options"					:"['不加密','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"啟用 WPS 時，不建議將 WEP 設為加密類型。",
			"key_size_label"					:"金鑰長度",
			"key_type_label"					:"加密模式",
			"key_mode_wep_label"				:"金鑰格式",
			"key_mode_wpa_label"				:"金鑰格式",
			"key_wep_label"						:"無線金鑰(密碼)",
			"key_wpa_label"						:"無線金鑰(密碼)",
			"key_time_label"					:"組金鑰更新週期",

			"wds_security_panel"				:"WDS 加密設定",
			"wds_sec_mode_label"				:"加密類型",
			"wds_sec_mode_options"				:"['不加密','WEP 64 位元','WEP 128 位元','WPA (TKIP)','WPA2 (AES)']",
			"wds_key_mode_wep_label"			:"金鑰格式",
			"wds_key_mode_wpa_label"			:"金鑰格式",
			"wds_key_wep_label"					:"無線金鑰(密碼)",				
			"wds_key_wpa_label"					:"無線金鑰(密碼)",				

			"client_security_panel"				:"Client 加密設定",
			"cl_sec_mode_label"					:"加密類型",
			"cl_sec_mode_options"				:"['不加密','WEP','WPA-PSK','WPA2-PSK']",
			"cl_key_size_label"					:"金鑰長度",
			"cl_key_type_label"					:"加密模式",
			"cl_key_mode_wep_label"				:"金鑰格式",
			"cl_key_mode_wpa_label"				:"金鑰格式",
			"cl_key_wep_label"					:"無線金鑰(密碼)",
			"cl_key_wpa_label"					:"無線金鑰(密碼)",
			"cl_key_auto_label"					:"無線金鑰(密碼)",
			"cl_key_time_label"					:"組金鑰更新週期",

			"repeater_security_panel"			:"Repeater 加密設定",
			"rp_sec_mode_label"					:"加密類型",
			"rp_sec_mode_options"				:"['不加密','WEP','WPA-PSK','WPA2-PSK']",
			"rp_key_size_label"					:"金鑰長度",
			"rp_key_type_label"					:"加密模式",
			"rp_key_mode_wep_label"				:"金鑰格式",
			"rp_key_mode_wpa_label"				:"金鑰格式",
			"rp_key_wep_label"					:"無線金鑰(密碼)",
			"rp_key_wpa_label"					:"無線金鑰(密碼)",
			"rp_key_auto_label"					:"無線金鑰(密碼)",
			"rp_key_time_label"					:"組金鑰更新週期",

			"64_r"								:"64 位元",
			"128_r"								:"128 位元",
			"hex_r"								:"十六進位",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_get_thead"						:"['ID','網路名稱','MAC 位址','頻道 (無線模式)','無線類型','加密類型','訊號強度','連線']"
		},
		"wl_mac_filter":{
			"txt"								:"無線 MAC 過濾",
			"filter_set_panel"					:"無線 MAC 過濾",
			"wl_mac_filter_enable_label"		:"運作狀態",
			"wl_mac_filter_rule_label"			:"過濾規則",
			"deny_r"							:"黑名單(位於列表上的MAC位址將無法連線至無線網路)",
			"allow_r"							:"白名單(位於列表上的MAC位址才可以連線至無線網路)",
			"contr_des_panel"					:"無線 MAC 過濾規則設定",
			"mac_des_label"						:"規則名稱",
			"macaddr_label"						:"MAC 位址",
			"mac_tab_panel"						:"無線 MAC 過濾規則列表",
			"wl_mac_filter_list_thead"			:"['ID','規則名稱','MAC 位址','修改']"
		},
		"wds":{
			"txt"								:"WDS 設定",
			"wds_set_panel"						:"WDS 設定",
			"wds_name_label"					:"目標無線名稱",
			"wds_mac_label"						:"目標 MAC 位址",
			"wds_tab_panel"						:"WDS 連線列表",
			"wl_wds_list_thead"					:"['ID','目標無線名稱','目標 MAC 位址','修改']",
			"ap_get_thead"						:"['ID','網路名稱','MAC 位址','頻道 (無線模式)','無線類型','加密類型','訊號強度','連線']"
		},
		"advance":{
			"txt"								:"無線網路進階設定",
			"advance_set_panel"					:"無線網路進階設定",
			"wlan_partition_label"				:"無線使用者隔離",
			"iapp_label"						:"無線漫遊",
			"shortGi_label"						:"Short GI",
			"protection_label"					:"保護",
			"out_power_label"					:"傳輸功率",
			"a_r"								:"100%",
			"b_r"								:"70%",
			"c_r"								:"50%",
			"d_r"								:"35%",
			"e_r"								:"15%",
			"wmm_label"							:"WMM"
		},
		"multiple_ssid":{
			"txt"								:"多重 SSID",
			"ap1_multiple_status_panel"  		:"多重 SSID",
			"multiple_status_label"    			:"狀態",
			"multiple_sele_label"      			:"選擇 AP",
			"multiple_sele_options"    			:"['AP1','AP2','AP3']",
			"para_set_panel"					:"多重 SSID 設定",
			"ap1_wl_enable_label"				:"運作狀態",
			"ap1_wl_mac_label"					:"MAC 位址",
			"ap1_ssid_label"					:"無線網路名稱(SSID)",
			"ap1_ssid_broad_label"				:"SSID 廣播",
			"ap1_sec_contr_label"				:"權限",
			"ap1_sec_contr_options"				:"['LAN+WAN','WAN']",
			"ap1_encryption_label"				:"加密模式",
			"ap1_encryption_options"			:"['不加密','TKIP','AES']",
			"ap1_password_label"				:"無線金鑰(密碼)",

			"safe_set_panel"					:"多重 SSID 加密設定",
			"ap1_sec_mode_label"				:"加密類型",
			"ap1_sec_mode_options"				:"['不加密','WEP','WPA-PSK','WPA2-PSK','WPA/WPA2-PSK']",
			"wep_tips_info"						:"啟用 WPS 時，不建議將 WEP 設為加密類型。",
			"ap1_key_size_label"				:"金鑰長度",
			"ap1_key_type_label"				:"加密模式",
			"ap1_key_mode_wep_label"			:"金鑰格式",
			"ap1_key_mode_wpa_label"			:"金鑰格式",
			"ap1_key_wep_label"					:"無線金鑰(密碼)",
			"ap1_key_wpa_label"					:"無線金鑰(密碼)",
			"ap1_key_time_label"				:"組金鑰更新週期",
			"64_r"								:"64 位元",
			"128_r"								:"128 位元",
			"hex_r"								:"十六進位",
			"asc_r"								:"ASCII",
			"t_r"								:"TKIP",
			"a_r"								:"AES",
			"ta_r"								:"TKIP & AES",
			"ap_link_tab_panel"					:"多重 SSID 清單",
			"wl_link_ap1_list_thead"			:"['ID','SSID','MAC 位址','SSID 廣播','權限','加密類型','修改']"
		},
		"wps":{
			"txt"								:"WPS 設定",
			"wps_security_panel"				:"WPS 設定",
			"wps_enable_label"					:"WPS 運作狀態",
			"wps_pin_label"						:"PIN 碼",
			"hand_add_label"					:"新增裝置",

			"hand_add_p_panel"					:"新增裝置",
			"hand_r"							:"請輸入無線設備 PIN 碼:",
			"press_r"							:"PBC(請在兩分鐘內按壓無線設備 WPS 按鈕)"
		},
		"list":{
			"txt"								:"連線列表",
			"list_panel"						:"連線列表",
			"wl_link_ap0_list_thead"			:"['ID','SSID','主機名稱','MAC 位址','已傳送封包','已接收封包']"
		}
	},
	"management":{
		"txt"									:" 存取控制",
	    "attack_defense":{
			"txt"								:"進階安全性",
			"attack_defense_panel"				:"進階安全性",
			"ping_wan_label"					:"忽略 WAN 連接埠的 PING 封包",
			"ping_lan_label"					:"忽略 PING 閘道",
			"port_packet_label"				    :"忽略通訊埠掃描封包",
			"icmp_flood_label"				    :"ICMP-Flood 攻擊防護",
			"icmp_flood_after"					:"封包閾值 (5-3000)",
			"tcp_flood_label"				    :"TCP-SYN-Flood 攻擊防護",
			"tcp_flood_after"					:"封包閾值 (5-3000)",
			"udp_flood_label"				    :"UDP-Flood 攻擊防護",
			"udp_flood_after"					:"封包閾值 (5-3000)",
			"virus_filter_label"		        :"病毒過濾",
			"arp_attack_label"				    :"ARP 攻擊防護",
			"attack_log_tab_panel"              :"ARP 攻擊記錄",
			"attack_log_list_thead"             :"['ID','時間','事件']"
		},
		"ip_filter":{
			"txt"								:"IP 位址過濾",
			"ip_filter_panel"					:"IP 位址過濾",
			"ip_filter_enable_label"			:"運作狀態",
			"ip_filter_rule_label"				:"過濾規則",
			"deny_r"							:"拒絕不在列表中的 IP 位址連線至網際網路。",
			"permit_r"							:"允許不在列表中的 IP 位址連線至網際網路。",
			"ip_filter_list_panel"				:"IP 位址過濾規則設定",
			"ip_describe_label"					:"規則名稱",
			"ip_status_label"					:"狀態",
			"ip_status_options"					:"['啟用','停用']",
			"ip_rule_label"						:"權限",
			"ip_rule_options"					:"['允許','拒絕']",
			"ip_src_sele_label"					:"來源主機",
			"ip_src_sele_options"      			:"['全部主機','單一主機','指定網段','IP範圍']",
			"ip_src_ip_label"                 	:"IP 位址",
			"ip_src_mask_label"            		:"子網路遮罩",
			"ip_src_start_label"				:"起始 IP 位址",
			"ip_src_end_label"					:"結束 IP 位址",
			"ip_des_sele_label"                 :"目的地主機",
			"ip_des_sele_options"               :"['全部主機','單一主機','指定網段','IP範圍']",
			"ip_des_ip_label"                   :"IP 位址",
			"ip_des_mask_label"                 :"子網路遮罩",
			"ip_des_start_label"				:"起始 IP 位址",
			"ip_des_end_label"               	:"結束 IP 位址",
			"ip_proto_label"					:"通訊協定",
			"ip_port_label"						:"通訊埠",
			"ip_proto_options"					:"['全部','TCP','UDP','ICMP']",
			"ip_day_label"						:"時間管理",
			"ip_day_btn"						:"全部",
			"ip_time_label"						:"指定時段",
			"ip_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"ip_filter_tab_panel"				:"IP 過濾規則列表",
			"ip_filter_list_thead"				:"['ID','規則名稱','權限','來源 IP','目的地 IP','通訊協定','通訊埠','週期','時間','修改']"
		},
		"mac_filter":{
			"txt"								:"MAC 位址過濾",
			"mac_filter_panel"					:"MAC 位址過濾",
			"mac_filter_enable_label"			:"運作狀態",
			"mac_filter_rule_label"				:"過濾規則",
			"deny_r"							:"拒絕不在列表中的 MAC 位址連線至網際網路。",
			"permit_r"							:"允許不在列表中的 MAC 位址連線至網際網路。",
			"mac_filter_list_panel"				:"MAC 位址過濾規則設定",
			"mac_describe_label"				:"規則名稱",
			"mac_status_label"					:"狀態",
			"mac_status_options"				:"['啟用','停用']",
			"mac_rule_label"					:"權限",
			"mac_rule_options"					:"['允許','拒絕']",
			"mac_filter_label"					:"來源 MAC 位址",
			"mac_day_label"						:"時間管理",
			"mac_time_label"					:"指定時段",
			"mac_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"mac_filter_tab_panel"				:"MAC 過濾規則列表",
			"mac_filter_list_thead"				:"['ID','規則名稱','權限','MAC 位址','週期','時間','修改']"
		},
		"dns_filter":{
			"txt"								:"網域名稱過濾",
			"domain_filter_panel"				:"網域名稱過濾",
			"dns_filter_enable_label"			:"運作狀態",
			"dns_filter_rule_label"				:"過濾規則",
			"deny_r"							:"拒絕連線至不在列表中的關鍵字網頁。",	
			"permit_r"							:"允許連線至不在列表中的關鍵字網頁。",
			"domain_filter_list_panel"			:"網域名稱過濾規則設定",
			"dns_des_label"						:"規則名稱",
			"dns_status_label"					:"狀態",
			"dns_status_options"				:"['啟用','停用']",
			"dns_rule_label"					:"權限",
			"dns_rule_options"					:"['允許','拒絕']",
			"dns_key_label"						:"關鍵字",
			"dns_day_label"						:"時間管理",
			"dns_time_label"					:"指定時段",
			"dns_time_options"					:"['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30','04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30','23:59']",
			"domain_filter_tab_panel"			:"網域名稱過濾規則列表",
			"dns_filter_list_thead"				:"['ID','規則名稱','權限','關鍵字','週期','時間','修改']"		
		}
	},
	"qos":{
		"txt"									:"頻寬管理",
		"qos":{
			"config_panel"						:"頻寬管理",
			"qos_enable_label"					:"運作狀態",
			"qos_rule_label"					:"規則",
			"qos_rule_label_a"					:"上行頻寬",
			"qos_rule_label_b"					:"下行頻寬",
			"qos_rule_label_c"					:"(0 代表不限制。)",
			"qos_rule_label_d"					:"(0 代表不限制。)",

			"qos_set_panel"						:"頻寬管理規則設定",
			"qos_des_label"						:"規則名稱",
			"qos_status_label"					:"狀態",
			"qos_status_options"				:"['啟用','停用']",
			"qos_sele_label"					:"主機",
			"qos_sele_options"					:"['全部主機','單一主機','指定網段','IP範圍']",
			"qos_ip_label"						:"IP 位址",
			"qos_mask_label"					:"子網路遮罩",
			"qos_ip_start_label"				:"起始 IP 位址",
			"qos_ip_end_label"					:"結束 IP 位址",
			"qos_min_label"						:"保證頻寬",
			"qos_min_label_a"					:"上行頻寬",
			"qos_min_label_b"					:"下行頻寬",
			"qos_min_label_c"					:"(KB/s) (0 代表不限制。)",
			"qos_min_label_d"					:"(KB/s) (0 代表不限制。)",
			"qos_max_label"						:"受限制頻寬",
			"qos_max_label_a"					:"上行頻寬",
			"qos_max_label_b"					:"下行頻寬",
			"qos_max_label_c"					:"(KB/s) (0 代表不限制。)",
			"qos_max_label_d"					:"(KB/s) (0 代表不限制。)",

			"qos_list_panel"					:"頻寬管理規則列表",
			"qos_rule_list_thead"				:"['ID','規則名稱','狀態','IP 位址範圍',{head:'保證頻寬',con:['上行','下行']},{head:'受限制頻寬',con:['上行','下行']},'修改']"
		}
	},
	"ddns":{
		"txt"									:"DDNS",
		"ddns":{
			"txt"								:"DDNS",
			"ddns_panel"						:"DDNS",
			"ddns_enable_label"					:"運作狀態",
			"ddns_sp_label"						:"服務供應商",
			"ddns_sp_options"					:"['No-IP','Dyndns']",
			"ddns_sp_after"						:"<a href='http://www.meibu.com/reg.asp'>www.noip.com</a>",
			"ddns_username_label"				:"使用者名稱",
			"ddns_password_label"				:"密碼",
			"ddns_domain_label"					:"網域名稱",
			"ddns_port_label"					:"通訊埠",
			"ddns_info_label"					:"連線狀態",
			"ddns_tips_info"					:"提示：如果您已經成功連線，當您要變更DDNS設定時，請先將DDNS功能停用再啟用才能進行設定。"
		}
	},
	"forward":{
		"txt"									:"通訊埠轉發",
		"virtual":{
			"txt"								:"虛擬伺服器",
			"vir_server_panel"					:"虛擬伺服器規則設定",
			"vir_name_label"					:"規則名稱",
			"vir_ip_label"						:"IP 位址",
			"vir_proto_label"					:"通訊協定",
			"vir_proto_options"					:"['ALL','TCP','UDP','HTTP','HTTPS','FTP','POP3','SMTP','DNS','TELENT','IPSEC','PPTP','Windows 終端機用戶端','GuruGuru','H323 VoIP 電話','Soribada']",
			"vir_outport_label"					:"外部通訊埠",
			"vir_inport_label"					:"內部通訊埠",
			"vir_tab_panel"						:"虛擬伺服器規則列表",
			"virtual_server_list_thead"			:"['ID','規則名稱','IP 位址','通訊協定','外部通訊埠','內部通訊埠','修改']"
		}
	},
	"advanced":{
		"txt"									:"進階設定",
		"vpn":{
			"txt"								:"VPN",
			"vpn_panel"							:"VPN 穿透設定",
			"pptp_enable_label"					:"PPTP 穿透",
			"l2tp_enable_label"					:"L2TP 穿透",
			"ipsec_enable_label"				:"IPSEC 穿透"
		},
		"igmp":{
			"txt"								:"IGMP",
			"igmp_panel"						:"IGMP",
			"igmp_enable_label"					:"運作狀態"
		},
		"dmz":{
			"txt"								:"DMZ",
			"dmz_panel"							:"DMZ",
			"dmz_enable_label"					:"運作狀態",
			"dmz_ip_label"						:"IP 位址",

			"super_dmz_panel"					:"超級 DMZ",
			"super_dmz_enable_label"			:"運作狀態",
			"super_dmz_addr_label"				:"MAC 位址"		
		},
		"portTrigger":{
			"txt"								:"通訊埠觸發",
			"port_trigger_panel"				:"通訊埠觸發規則設定",
			"port_select_label"					:"常用規則",
			"port_select_options"				:"['--手動設定--','GuruGuru','BuddyBuddy','Enppy','Pruna TCP','Pruna UDP']",
			"app_name_label"					:"規則名稱",
			"trigger_proto_label"				:"觸發通訊協定",
			"trigger_proto_options"				:"['TCP','UDP']",
			"app_port_label"					:"觸發通訊埠",
			"forward_proto_label"				:"進入通訊協定",
			"forward_proto_options"				:"['TCP','UDP']",
			"forward_port_label"				:"連入通訊埠",
		
			"trigger_tab_panel"					:"通訊埠觸發規則列表",
			"app_port_list_thead"				:"['ID','規則名稱','觸發通訊協定','觸發通訊埠','進入通訊協定','連入通訊埠','修改']"
		},
		"ftp":{
			"txt"								:"FTP 通訊埠轉發",
			"ftp_port_panel"					:"FTP 通訊埠轉發",
			"ftp_enable_label"					:"運作狀態",
			"ftp_port_label"					:"通訊埠"
		},
		"upnp":{
			"txt"								:"UPnP",
			"upnp_panel"						:"UPnP 設定",
			"upnp_enable_label"					:"運作狀態"
		},
		"binds":{
			"txt"								:"IP & MAC 綁定",
			"binds_set_panel"					:"IP & MAC 綁定",
			"binds_rule_label"					:"綁定規則",
			"deny_r"							:"允許不在列表中的裝置連線至網際網路。",
			"allow_r"							:"拒絕不在列表中的裝置連線至網際網路。",

			"contr_binds_panel"					:"IP & MAC 綁定規則設定",
			"binds_des_label"					:"規則名稱",
			"binds_ip_label"					:"IP 位址",
			"binds_mac_label"					:"MAC 位址",
			"binds_port_label"					:"網路介面",
			"binds_port_options"				:"['LAN','WAN']",
			"binds_tab_panel"					:"IP & MAC 綁定規則列表",
			"binds_list_thead"					:"['ID','規則名稱','IP 位址','MAC 位址','網路介面','修改']"
		},
		"arp_list":{
			"txt"								:"ARP 列表",
			"arp_list_panel"					:"ARP 列表",
			"arp_list_thead"					:"['ID','IP 位址','MAC 位址']"
		},
		"routing":{
			"txt"								:"固定路由",
			"routing_panel"						:"固定路由規則設定",
			"route_des_label"					:"規則名稱",
			"route_type_label"					:"類型",
			"route_type_options"				:"['網段','單一主機']",
			"ip_value_label"					:"目的地IP 位址",
			"mask_value_label"					:"子網路遮罩",
			"gateway_value_label"				:"預設閘道",
			"route_tab_panel"					:"固定路由規則列表",
			"static_routing_list_thead"			:"['ID','規則名稱','類型','IP 位址','子網路遮罩','預設閘道','修改']"
		},
		"interface_mode":{
			"txt"								:"連接埠設定",
			"mode_panel"						:"WAN 連接埠設定",
			"wan_label"							:"WAN 連接埠",
			"wan_options"						:"['自動','10M 全雙工','10M 半雙工','100M 全雙工','100M 半雙工']"
		},
		"wakeup":{
			"txt"								:"遠端喚醒",
			"wakeup_panel"						:"遠端喚醒設定  ",
			"wakeup_mac_label"					:"主機MAC 位址"
		}
	},
	"misc":{
		"txt"									:"系統工具",
		"update":{
			"txt"								:"韌體升級",
			"update_panel"						:"韌體升級",
			"version_label"						:"目前版本",
			"file_label"						:"韌體檔案",
			"updata_file_label"                 :"韌體檔案",
			"load_panel"						:"韌體升級",
			"tip_update_info"					:"提示：升級過程中請勿關閉無線寬頻分享器電源。"
		},
		"sys_time":{
			"txt"								:"時間設定",
			"time_set_panel"					:"時間設定",
			"time_now_label"					:"目前時間",
			"time_type_label"					:"類型",
			"ntp_r"								:"NTP伺服器",
			"hand_r"							:"手動設定",
			"time_date_label"					:"日期",
			"time_date_after"					:"年",
			"time_date_after2"					:"月",
			"time_date_after3"					:"日",
			"time_time_label"					:"時間",
			"time_time_after"					:"時",
			"time_time_after2"					:"分",
			"time_time_after3"					:"秒",
			"timezone_label"					:"時區",
			"timezone_options"					:"['(GMT-12:00) 愛尼維托, 瓜加林島','(GMT-11:00) 中途島, 薩摩亞','(GMT-10:00) 夏威夷','(GMT-09:00) 阿拉斯加','(GMT-08:00) 美國太平洋時間 (美國加拿大); 洛杉磯','(GMT-07:00) 美國山區時間 (美國加拿大); 亞利桑納','(GMT-06:00) 美國中部時間 (美國加拿大); 墨西哥市','(GMT-05:00) 美國東部時間 (美國加拿大); 波哥大, 紐約, 利馬','(GMT-04:00) 大西洋時間(加拿大); 卡拉卡斯, 拉帕茲','(GMT-03:00) 巴西利亞, 布宜諾斯艾利斯, 佐治敦, 格陵蘭','(GMT-02:00) 大西洋中部','(GMT-01:00) 維德角群島, 亞述群島','(GMT) 格林威治時間; 都柏林, 愛丁堡, 倫敦, 里斯本','(GMT+1:00) 阿姆斯特丹, 柏林, 羅馬, 斯德哥爾摩, 巴黎','(GMT+2:00) 開羅, 雅典, 伊斯坦堡, 明斯克, 耶路撒冷','(GMT+3:00) 巴格達, 科威特, 利雅德, 莫斯科, 聖彼得堡','(GMT+4:00) 阿布達比, 馬斯喀特, 巴庫, 第比利斯, 葉里溫','(GMT+5:00) 伊科得林堡, 伊斯蘭馬巴德, 喀拉蚩, 塔什干','(GMT+6:00) 阿馬提, 諾曼斯比爾斯科, 阿斯坦納, 達卡','(GMT+7:00) 曼谷, 雅加達, 河內','(GMT+8:00) 北京, 香港, 台北, 新加坡','(GMT+9:00) 東京, 大阪, 札幌, 首爾, 雅庫次克','(GMT+10:00) 布里斯本, 關島, 坎培拉, 墨爾本, 雪梨','(GMT+11:00) 馬加丹, 索羅門群島, 新卡倫多尼亞','(GMT+12:00) 斐濟, 馬紹爾群島, 奧克蘭, 威靈頓','(GMT+13:00) 努庫阿洛法']",
			"ntp_panel"							:"NTP 伺服器",
			"time_server_label"					:"NTP 伺服器IP/名稱",
			"time_server_after"					:"(選填)"
		},
		"diagnostic":{
			"txt"								:"網路診斷",
			"diagnostic_panel"					:"網路診斷",
			"tools_type_label"					:"網路診斷",
			"ping_r"							:"Ping",
			"trac_r"							:"Tracert",
			"tools_ip_url_label"				:"IP 位址/網域名稱",
			"result_head_info"					:"診斷結果",
			"result_info"						:" "
		},
		"remote":{
			"txt"								:"遠端管理",
			"remote_panel"						:"遠端管理",	
			"remote_enable_label"				:"運作狀態",
			"remote_port_label"					:"通訊埠"	
		},
		"passwd":{
			"txt"								:"管理密碼",
			"change_pwd_panel"					:"變更密碼",
			"old_user_label"					:"使用者名稱",
			"old_pwd_label"						:"目前密碼",
			"old_pwd_after"					    :"(請輸入字元：a-z、A-Z、0-9。)",
			"new_user_label"					:"新使用者名稱",
			"new_user_after"					:"(請輸入字元：a-z、A-Z、0-9。)",
			"new_pwd_label"						:"新密碼",
			"new_pwd_after"						:"(請輸入字元：a-z、A-Z、0-9。)",
			"new_pwd_confirm_label"				:"確認新密碼",
			"new_pwd_confirm_after"				:"(請輸入字元：a-z、A-Z、0-9。)"
		},
		"backup":{
			"txt"								:"備份與還原",
			"backup_panel"						:"備份設定",
			
			"restore_panel"						:"還原設定",
			"tip_restore_info"					:"提示： 還原程序將會持續大約一分鐘。 在此期間，請勿關閉電源或按下無線寬頻分享器上的任何預設按鈕，以免造成任何損壞。",
			"file_label"						:"備份檔案",
			"file_up_label"						:"備份檔案",
			"load_panel"						:"還原"
			
		},
		"sys_log":{
			"txt"								:"系統記錄檔",
			"sys_log_panel"						:"系統記錄檔",
			"sys_log_thead"						:"['ID','時間','事件']"
		},
		"statistics":{
			"txt"								:"統計資料",
			"status_sys_panel"					:"路由器狀態",
			"run_time_label"					:"系統運作時間",
			"cpu_label"							:"CPU 使用率",
			"mem_label"							:"記憶體使用率",

			"statistics_panel"					:"流量統計資料",
			"statistics_list_thead"				:"['類型','已傳送封包','已接收封包','已傳送資料 (KB)','已接收資料 (KB)']"
		},
		"default":{
			"txt"								:"恢復原廠預設值",
			"tip_default_info"					:"提示： 全部設定值將恢復到出廠值。",
			"default_panel"						:"恢復原廠預設值",
			"load_panel"						:"恢復原廠預設值"
		},
		"reboot":{
			"txt"								:"重新開機",
			"tip_reboot_info"					:"提示： 重新開機過程中網路將會暫時中斷。",
			"reboot_panel"						:"重新開機"
		}
	}
};



//Extra part（to be translated）           ：“歡迎使用 netis 無線 N 路由器”
//Extra part（to be translated）           ：“選擇語言”
//Extra part（to be translated）           ：“快速設定”
//Extra part（to be translated）           ：“網際網路連線類型”
//Extra part（to be translated）           ：“無線設定”
//Extra part（to be translated）           ：“進行登入...”
//Extra part（to be translated）           ：“使用者名稱或密碼錯誤”
//Extra part（to be translated）           ：“IP 位址與 WAN 位址發生衝突！ 請變更路由器的 LAN IP 位址。”
